### ISSUE TITLE
Server requires "country" field but there is no good error indication for this

### ISSUE THREAD

**Issue by rix0rrr** [Felienne/hedy#1026]
The server checks and requires that the "country" field is given, but this is not checked on the client. The result is that the error becomes very nondescriptive:

<img width="478" alt="image" src="https://user-images.githubusercontent.com/524162/137587378-20a98882-2d8e-4e10-b7f2-0ef03814b7f1.png">

The server said:

<img width="299" alt="image" src="https://user-images.githubusercontent.com/524162/137587386-7eb51626-be33-470f-9e4e-3597e27e45b2.png">

We should find a way to unify server and client side validation.

**Comment by rix0rrr** [comment]
Oh same for gender by the way:

<img width="269" alt="image" src="https://user-images.githubusercontent.com/524162/137587420-cf62be72-94fc-4fa4-9f41-14440e45c707.png">

**Comment by Felienne** [comment]
@fpereiro Can you make those two fields optional on the server?

**Comment by fpereiro** [comment]
Could this be considered as closed after merging #1117?

**Comment by Felienne** [comment]
> Could this be considered as closed after merging #1117?

I think so (cc @boryanagoncharenko just to be sure, @fpereiro maybe you can also test it yourself to see if it all works now?)

**Comment by fpereiro** [comment]
Tested, it works well with both fields being left blank!
