### ISSUE TITLE
Split tests in grammar tests and others

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1039]
The set of tests is getting quite long and so tests are quite slow but come first alphabetically. It is not so pretty to rely on the order and name them _z_ as we do now.

A better solution would be to create two folders that can be run separately but that will also require some changes to the test runner I think

**Comment by aelhamah** [comment]
Hi @Felienne ! Could I potentially take on this issue as well? If so, what should the file structure be within the `tests` directory? From your description it sounds it should be something like :
```
.
├── Tester.py
├── ab_test_setup.sh
├── test_abproxying.py
├── test_distance_algo.py
├── test_dynamo.py
├── test_level
│   ├── test_level_01.py
│   ├── test_level_02.py
│   ├── test_level_03.py
│   .
│   .
│   .
│   ├── test_level_16.py
│   ├── test_level_17.py
│   └── test_level_18.py
├── test_querylog.py
├── test_utils.py
├── test_z_adventures.py
├── test_z_defaults.py
├── tests_z_yamlfile.py
└── test_translation_level
    ├── test_translation_level_01.py
    ├── test_translation_level_02.py
    ├── test_translation_level_03.py
    .
    .
    .
    ├── test_translation_level_16.py
    ├── test_translation_level_17.py
    └── test_translation_level_18.py

```
Also, would it likely be necessary to change the command that the CI Workflow uses in `build-tools/github/validate-tests`?

**Comment by Felienne** [comment]
Thanks for picking this up! Yes that is what I had in mind, with one little change:

```
.
├── Tester.py
├── ab_test_setup.sh
├── test_abproxying.py
├── test_distance_algo.py
├── test_dynamo.py
├── test_level
│   ├── test_level_01.py
│   ├── test_level_02.py
│   ├── test_level_03.py
│   .
│   .
│   .
│   ├── test_level_16.py
│   ├── test_level_17.py
│   └── test_level_18.py
├── test_querylog.py
├── test_utils.py
└──test_snippets <---- new folder
|    ├──test_adventures.py <----- remove _z_
|    ├── test_level_defaults.py <------ remove _z_ and add levels for extra clarity
├── tests_z_yamlfile.py
└── test_translation_level
    ├── test_translation_level_01.py
    ├── test_translation_level_02.py
    ├── test_translation_level_03.py
    .
    .
    .
    ├── test_translation_level_16.py
    ├── test_translation_level_17.py
    └── test_translation_level_18.py
```

So adventures and defaults both test snippets and we can remove the _z_ prefix that I only used for organization.

And yes I guess some changes will be needed to the test running scripts too.
