### ISSUE TITLE
Quiz could be a bit wider?

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1046]
There seems to be some whitespace on the right hand side where the quiz could be larger. Esp when folding the palette in this would give us more room. Not sure to fix this in the quiz itself (@LterHaar) or in the iframe (@fpereiro or @TiBiBa)?

![image](https://user-images.githubusercontent.com/1003685/137896473-6c22980e-55e3-489f-9407-001b535f5171.png)

**Comment by fRedelaar** [comment]
Closing issue since MR #1381 has been merged
