### ISSUE TITLE
Unify form validation between client and server

### ISSUE THREAD

**Issue by rix0rrr** [Felienne/hedy#1057]
(This is a refactoring/cleanup task.)

---

Right now, form validation code is duplicated between client and server.

For example, user signup is validated here on the server:

https://github.com/Felienne/hedy/blob/c778f7c221e7721e725460db3b49a4df006b72bc/website/auth.py#L124-L133

And the same validations are performed here on the client:

https://github.com/Felienne/hedy/blob/c778f7c221e7721e725460db3b49a4df006b72bc/static/js/auth.js#L46-L52

This duplication leads to issues (for example #1026) where the logic between the two doesn't agree; also the maintenance cost of these two sets of rules is increased. 

There is one difference, and that is that the client has information about WHERE to display the error message, and the client localizes the error message.

It would be better if the server was the only component validating, and it replied with enough information that the client could parse the response and show the same, localized, appropriate error messages highlighting the appropriate fields.

**Comment by rix0rrr** [comment]
Flask itself suggests using a library called `WTForms`: https://flask.palletsprojects.com/en/2.0.x/patterns/wtforms/

**Comment by Felienne** [comment]
Hi @TiBiBa and @rix0rrr!

Yesterday we closed ttps://github.com/Felienne/hedy/issues/1164 and I think it is somewhat similar to this one? Is extra work needed here?

**Comment by TiBiBa** [comment]
> Hi @TiBiBa and @rix0rrr!
> 
> Yesterday we closed #1164 and I think it is somewhat similar to this one? Is extra work needed here?
> 
> This issue's title seems to be more generic but seemingly also applies to auth only?

I think it would be best to leave this open as wel still perform some duplicate data validation that can be cleaned-up. Will take a look later this week!
