### ISSUE TITLE
Support range keys in DynamoDB abstraction

### ISSUE THREAD

**Issue by rix0rrr** [Felienne/hedy#1060]
(This a deep internals task)

------------

Because the original database design only used DynamoDB partition keys, and never range keys, the abstraction that we have to support offline development never grew the feature to define range keys, and use any of those features.

It would be good to add support for range keys, then we can use those and can probably do with fewer indexes on the tables.

**Comment by Felienne** [comment]
Closed by https://github.com/Felienne/hedy/pull/1340
