### ISSUE TITLE
Show feedback after answer in quizzes

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#1066]
In the quiz yaml files I've filled in the line 'feedback' after each answer option, but the feedback isn't shown anywhere.

**Comment by LterHaar** [comment]
![Capture](https://user-images.githubusercontent.com/86956321/140725378-44c8f776-fce3-4920-8c2a-2c12ebe8f752.PNG)

De feedback van het laatste antwoord is wel te zien (zie gehighlighte text)

![Capture2](https://user-images.githubusercontent.com/86956321/140725389-8f605ce1-fade-4f67-ab63-6cb033d82919.PNG)

Ik zt eraan t denken de feedback te verplaatsen voor elke poging naar het groene deel. En dan daar of text, of een feedback knop (die text toont, zoals de andere hint knop) te tonen.

**Comment by Felienne** [comment]
Closed by #1221
