### ISSUE TITLE
Missing pictures on for-teachers page

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1069]
On the for-teachers page at the "preparations" section there is a placeholder for two images, however they aren't there. I'm not sure how the page was originally structured, but for some reason the pictures don't show up. Tested on the dutch and English for-teachers page, both show the same message.

**Comment by Felienne** [comment]
Hi @TiBiBa!

I am cleaning up issues and I am not sure this is still an issue? If it is, can you point me to the place in the code or the UI where this happens because I can't seem to find it

**Comment by TiBiBa** [comment]
Can't seem to find the issue anymore (might already be fixed). I think it can be deleted!
