### ISSUE TITLE
Improve navigation bar with :hover and clear differentiation

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1073]
Currently the buttons in the navigation bar are all the same color as well as the background which might make it unclear to the user that these are actually the buttons to navigate to differente pages. I would suggest adding a :hover element to give more user feedback when selecting a menu option as well as adding some border to make the difference between each menu option more clear.

**Comment by Felienne** [comment]
Hi @TiBiBa, @johannadekker & @maximedongen, I am not sure what the status of this is (since so much has already changed in the UI), do we need to keep it open?

**Comment by TiBiBa** [comment]
This one is already implemented! If I remember correctly we implemented :hover on the nav buttons with the overall re-design when we implemented the user drop-down menu as well.

**Comment by Felienne** [comment]
Great!! (doing an end of year cleanup of issues haha)
