### ISSUE TITLE
Code blocks in quiz always start indented

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1076]
Can be confusing for kids (quiz level 7, question 7)

![image](https://user-images.githubusercontent.com/1003685/138294854-a4b9ff43-73e9-4b87-bff9-9b03859ab95b.png)

**Comment by LterHaar** [comment]
![image](https://user-images.githubusercontent.com/86956321/141965244-189acb88-b986-4e2c-a1c2-dd1524e11499.png)

Ik heb de indenting veranderd door ml-6 (margin left) weg te halen en de span om de <code> tags.
