### ISSUE TITLE
Show error location for errors from skulpt

### ISSUE THREAD

**Issue by bjorn3** [Felienne/hedy#1079]
`err.traceback` contains an array of the error locations in the form of an object like `{ filename: "<stdin>.py", lineno: 3, colno: 0 }`. We should probably filter for the filename `<stdin>.py` to ensure that if the error happens while calling a standard library function we get the user code as error location.

related to #845

**Comment by Felienne** [comment]
I like this idea but I am afraid it will not work because the error locations are in the generated Python that is really different from the Hedy (f.e. because we put the import turtle and random at the top)

**Comment by bjorn3** [comment]
Of course.
