### ISSUE TITLE
Distinguish error production rules in grammar

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1102]
Some production rules, like `invalid` or `print_nq` are not regular rules but `error production'. It would be nice if that was clearer in the grammar, for example with a clear error_ prefix. This will require updates in the grammars but also in hedy.py because the transformation matches the production rule exactly.

**Comment by racertop** [comment]
Since apparently no one has taken this one, can I assign this to myself?

**Comment by Felienne** [comment]
> Since apparently no one has taken this one, can I assign this to myself?

Yes, by all means! Would be nice to clean up the grammars a bit more!

**Comment by racertop** [comment]
> > Since apparently no one has taken this one, can I assign this to myself?
> 
> Yes, by all means! Would be nice to clean up the grammars a bit more!

Great!! Do you have anything specific in mind?

**Comment by Felienne** [comment]
Maybe prefix them with `error_`?
