### ISSUE TITLE
[BUG] Lvl 13 variables with '' are still printed as variables

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#1126]
**Describe the bug**
The output of the code  is 'banaan', but it should be 'eerstefruit' 

**Paste the Hedy code & level**
fruit is ['banaan', 'appel', 'kers']
eerstefruit is fruit[1]
print('eerstefruit')

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/80678586/139262765-ca9c0ab8-dcba-4865-a935-6b4266d26d83.png)

**Comment by Felienne** [comment]
Closed by #1139
