### ISSUE TITLE
NL version Hedy, Level 7, automatic fill in is incorrect

### ISSUE THREAD

**Issue by RicardoKoos** [Felienne/hedy#114]
In the dutch version of Hedy, at level 7 there is an error. Whenever you press one of the 2 buttons in the attached picture, the code that is automaticly filled in is incorrect.

![error](https://user-images.githubusercontent.com/58550825/101905281-7d2bab80-3bb7-11eb-86ea-7ad5aba71b32.png)

It is missing de necessary tabs.

In the picture below it is shown how it should look.
![correct](https://user-images.githubusercontent.com/58550825/101905835-5cb02100-3bb8-11eb-878a-226edbd74bd1.png)

**Comment by dvberkel** [comment]
This is a problem in all languages.
