### ISSUE TITLE
[BUG] Unclear error message if last line of program only contains spaces in levels 1 and 2

### ISSUE THREAD

**Issue by jpelay** [Felienne/hedy#1140]
**Describe the bug**
If the last line of a program in levels 1 and 2 contains only spaces, the resulting error won't be very clear.
![image](https://user-images.githubusercontent.com/45865185/139564491-7c3b9f33-a283-401f-8465-90762bd63e8f.png)
This happens because the `UnexpectedCharacters` exceptions gets the character `'\n'` and not `' '` (which is what happens in later levels. 

**Paste the Hedy code & level**
`print hello world!`
` `

**Expected behavior**
It should return "You typed space, but that is not allowed". Unless we want to execute or fix code that has spaces in the last line.

**Comment by Felienne** [comment]
Hi @racertop!

Thanks for finding yet another issue!! I tried this PR but for me it still shows the old error (level 1)

![image](https://user-images.githubusercontent.com/1003685/139574260-0a5b74dc-7000-428a-95b0-3d10c2bf40cb.png)

**Comment by racertop** [comment]
Hi @Felienne! I didn't fix that it doesn't execute the code, just that in levels 1 and 2 it won't say that you typed a space. In my screenshot you can see that it says 'You typed , but that is not allowed' in your screenshot it does say space.

Now, would this be valid code and should be executed? I think that that has to do with the grammar rules. Or maybe do a bit of preprssing and remove empty lines before parsing the input. What do you think?

**Comment by racertop** [comment]
@Felienne I kept working on this issue and found that we can actually fix the code by just changing the rule `invalid_space` from: `_SPACE text` to `_SPACE text?` now line containing only spaces in levels 1 and 2 (and 3, 4, 5 and 6 if you check #1142) will thrown InvalidSpaceException.

**Comment by Felienne** [comment]
Ah fantastic!! Going to check out your PR now.

**Comment by Felienne** [comment]
Closed by #1141

**Comment by racertop** [comment]
Hi @Felienne! Is this issue stil open? It seems like it's been deployed to production already. Or is there anything else I can do to improve the message?
![image](https://user-images.githubusercontent.com/45865185/140773119-205d2da5-0a3d-432f-a9dd-a3a51226e83f.png)

**Comment by Felienne** [comment]
> Hi @Felienne! Is this issue stil open? It seems like it's been deployed to production already. Or is there anything else I can do to improve the message? ![image](https://user-images.githubusercontent.com/45865185/140773119-205d2da5-0a3d-432f-a9dd-a3a51226e83f.png)

It is not fixed in the parser, but in the editor! By this one #898. So I guess we can close it indeed, I did not realize, sorry!

**Comment by racertop** [comment]
Hi

> > Hi @Felienne! Is this issue stil open? It seems like it's been deployed to production already. Or is there anything else I can do to improve the message? ![image](https://user-images.githubusercontent.com/45865185/140773119-205d2da5-0a3d-432f-a9dd-a3a51226e83f.png)
> 
> It is not fixed in the parser, but in the editor! By this one #898. So I guess we can close it indeed, I did not realize, sorry!

Yes, but only when the line has text, not when the line contains only spaces. Example of level 3, when invalid_space rule is still not added, it throws an error:

![image](https://user-images.githubusercontent.com/45865185/140788148-855f867c-6b70-419c-b669-0fe9b412ab4d.png)

**Comment by Felienne** [comment]
Good catch! I have not looked into this in depth, but I suspect the error then happens because there is a newline in the code that can't be processed by the grammar. Leaving this open for you to look into :) Let me know if you need help!

**Comment by racertop** [comment]
Ok, great!

**Comment by Felienne** [comment]
Or do you think we should give an error in this case to warn against the space on line 5?

**Comment by jpelay** [comment]
No, I think this is ok!
