### ISSUE TITLE
[UI idea] Make logout button accesible from every page

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1149]
**Idea incl level**
Currently there is a "login" button in the menubar, being accessible for every page on the website. However, when logged in this button is replaced by the "my programs" button. To logout we have to navigate to "my profile" and then use the logout button. I propose to implement a logout button within the menu-bar, making it clearly visible to the user.   I create a simple mock-up as example, which can be found in the screenshots below. However, it might be nice to do some menubar styling together with this button implementation.

**Additional context: Proposed new UI design**
![Schermafbeelding 2021-11-02 om 19 45 43](https://user-images.githubusercontent.com/38155424/139926025-d0214f2d-b223-4887-b778-926f403d385d.png)
![Schermafbeelding 2021-11-02 om 19 45 54](https://user-images.githubusercontent.com/38155424/139926037-7308b4eb-3232-475a-bb18-a4e2da6ca295.png)

**Comment by TiBiBa** [comment]
It seems `app.ts` is not accessible on the homepage, making it impossible to logout. This should be looked at first before attempting to implement this UI change.

**Comment by Felienne** [comment]
I thought about this a bit more and I like this idea but I think ultimately we want something more like all websites have where the login button changes into a button with a persons username linking to their profile. But updating that part of the site for now is not all that important.
