### ISSUE TITLE
[BUG] for-teachers page accessible when not a teacher

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1157]
**Describe the bug**
When not a teachers we are still able to visit the for-teachers page by directly using the url of the page. For example, on alpha every use is able to visit the page with: [](https://hedy-alpha.herokuapp.com/for-teachers). This is undesired behavior and it should be verified if a user is a teacher otherwise we should re-direct them to the homepage (for example)

**Add a screenshot (optional): Not logged in, still on the for-teachers page**
![Schermafbeelding 2021-11-03 om 14 35 09](https://user-images.githubusercontent.com/38155424/140069814-5fb59a25-fb08-4c10-81f7-d72d7901dcf0.png)

**Expected behavior**
Re-direct user that is not a teacher (or not logged in at all) to the homepage when trying to reach the for-teachers page

**Comment by Felienne** [comment]
Closed by #1160
