### ISSUE TITLE
[BUG] Allow what's next adventure to use code of the next level...

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#1170]
**Describe the bug**
Now the what's next adventure is not allowed to actually show you what's next. So it should be tested for the next level instead of the current one. 

**Paste the Hedy code & level**
Right now level 7 has a level 8 what's next code that is being blocked. 

**Add a screenshot (optional)**
Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.

**Expected behavior**

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
- What browser you were using (Chrome, Edge, Safari)

**Comment by Felienne** [comment]
Closed by #1156
