### ISSUE TITLE
[BUG] Level 11 (new) - numbers are saved as strings in variables

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#1172]
**Describe the bug**
Variables that contain a number are saved as string instead of number. Which makes it impossible to use maths with variables.

**Paste the Hedy code & level**
print 'Het digitale spaarvarken'
wens is ask 'Wat zou je graag willen hebben?'
prijs is ask 'Hoeveel kost dat?'
gespaard is ask 'Hoeveel geld heb je al gespaard?'
zakgeld is ask 'Hoeveel zakgeld krijg je per week?'
sparen is prijs - gespaard
weken is sparen / zakgeld
print 'Dus jij wil graag een ' wens ' hebben.'
print 'Een ' wens ' kost ' prijs ' euro.'
print 'Je hebt al ' gespaard ' euro gespaard.'
print 'Je moet dus nog ' sparen ' euro sparen.'
print 'En je krijgt ' zakgeld ' euro in de week.'
print 'Dat betekent dat je over... ' weken ' weken een ' wens ' kunt kopen!'

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/80678586/140354616-6a636824-0acf-4598-91cc-ed3fb68acc43.png)

**Expected behavior**

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
- What browser you were using (Chrome, Edge, Safari)

**Comment by Felienne** [comment]
Closed by #1156
