### ISSUE TITLE
Block the try buttons in the example codes after a while

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#1176]
I noticed in my lessons that my students love playing with the example codes, but therefore they barely do any coding themselves. So I'd like them to be able to use the example code 3 times (or so) and then the code should be removed from their input screen and the try button should be blocked. So they have to type in the code themselves if they want to keep playing. 

Another option would be for the teacher to be able to block the try button in their students' adventures.

**Comment by Felienne** [comment]
I think this is a good idea, do you think it is feasible @TiBiBa? It has the added benefit that once the buttons have been tried x times, we can remove the whole sidebar (with the logic that we already have in the hide button) and we have more room for the rest of the interface.

**Comment by TiBiBa** [comment]
I like the idea! However, I think it would be too restrictive for general users to implement this overall. It might be a nice solution to only have this restriction when the current user is in a class? However, I'm cautious with implementing too much "small" fixes and would rather have a class customization page as suggested in #775. Where the teacher has the choice to maybe hide example programs, customize the adventures and/or give each student the option to use x amount of example codes per level.

**Comment by TiBiBa** [comment]
> I think this is a good idea, do you think it is feasible @TiBiBa? It has the added benefit that once the buttons have been tried x times, we can remove the whole sidebar (with the logic that we already have in the hide button) and we have more room for the rest of the interface.

I think it is feasible! However, as there are also a lot of example programs in the adventure tabs we would have to take a look how to nicely structure the UI after all attempts are used. (We might also want to warn students that they only have x attempts). For example with "As you're in a class, you are only able to try example programs three times."

**Comment by Felienne** [comment]
> > I think this is a good idea, do you think it is feasible @TiBiBa? It has the added benefit that once the buttons have been tried x times, we can remove the whole sidebar (with the logic that we already have in the hide button) and we have more room for the rest of the interface.
> 
> I think it is feasible! However, as there are also a lot of example programs in the adventure tabs we would have to take a look how to nicely structure the UI after all attempts are used. (We might also want to warn students that they only have x attempts). For example with "As you're in a class, you are only able to try example programs three times."

Good point @TiBiBa. What do you think @MarleenGilsing, should we also disable the adventure examples after a while (we can simply remove the copy-paste button so kids are more motivated to type the code)?

**Comment by Felienne** [comment]
> I like the idea! However, I think it would be too restrictive for general users to implement this overall. It might be a nice solution to only have this restriction when the current user is in a class? However, I'm cautious with implementing too much "small" fixes and would rather have a class customization page as suggested in #775. Where the teacher has the choice to maybe hide example programs, customize the adventures and/or give each student the option to use x amount of example codes per level.

I agree it would be fantastic to have this in the teacher-class customizations (that they can set an "example tries" limit for a class) but I am not sure what we think the timeline is on that? MY guess is @MarleenGilsing would like to have this feature soonish to use in her current series of lessons.

**Comment by MarleenGilsing** [comment]
Yes please! It would really help to encourage them to make their own codes.

**Comment by TiBiBa** [comment]
> > I like the idea! However, I think it would be too restrictive for general users to implement this overall. It might be a nice solution to only have this restriction when the current user is in a class? However, I'm cautious with implementing too much "small" fixes and would rather have a class customization page as suggested in #775. Where the teacher has the choice to maybe hide example programs, customize the adventures and/or give each student the option to use x amount of example codes per level.
> 
> I agree it would be fantastic to have this in the teacher-class customizations (that they can set an "example tries" limit for a class) but I am not sure what we think the timeline is on that? MY guess is @MarleenGilsing would like to have this feature soonish to use in her current series of lessons.

That might indeed be more of long-term feature. I can take a look later today if we can implement the feature that students currently in a class have a maximum of three "copy" attempts per level. However, as we keep track of this value on the front-end they will be able to re-load the page or switch levels back and forth to "outsmart" the counter. For a more "hack-proof" solution we would have to do some back-end magic. But that might be better to align with #775 on the long-term.

**Comment by TiBiBa** [comment]
I did some "knutselen" and create an example of how it could work. See the video below for clarification. Currently every session/level gets three attempts on example code. I would like to alter this to only have this restriction for users that are currently in a class. But will have to look into the code to get that working.

https://user-images.githubusercontent.com/38155424/140536748-bb39dff2-d221-4b48-9e5c-5ca7d36b4313.mov

**Comment by TiBiBa** [comment]
In the current PR there is no fix for removing the copy button from the adventure code snippets (yet). Will take a look to implement that as well
