### ISSUE TITLE
Exception parameters are used inconsistently

### ISSUE THREAD

**Issue by rix0rrr** [Felienne/hedy#1178]
(This is a refactoring/cleanup task.)

----------------

The following occurs side-by-side, and may get confusing to contributors:

```py
class ParseException(HedyException):
    def __init__(self, level, location, keyword_found=None, character_found=None):
        super().__init__('Parse')
        self.level = level
        self.location = location
        self.keyword_found = keyword_found
        self.character_found = character_found

class UndefinedVarException(HedyException):
    def __init__(self, **arguments):
        super().__init__('Var Undefined', **arguments)
```

There are differences in two dimensions:

## Parameters

Are they enumerated (`level, location, keyword_found, character_found`), or do we just implicitly accept everything that's given (`**arguments`) ?

The former is probably better against accidental misuse, while the second is less typing 🤗.

It would *probably* be a good idea to use the style of the former to protect against accidents, while potentially even adding in the concept of *mandatory* keyword arguments:

```py
    def __init__(self, *, level, location, keyword_found=None, character_found=None):
```

The `*` in there makes it so that the arguments *can not* be passed positionally, they *must* be passed as keyword arguments. So:

```py
ParseException(5, [0, 1], 'xyz', 'abc')        # Not allowed

ParseException(level=5, location=[0,1], keyword_found='xyz')  # Must be this
```

The mandatory keyword arguments make it hard to accidentally swap two positional arguments around: it's very clear what you are doing.

## Storage

Are arguments passed up to the superclass, or stored on the exception object itself?

If they get passed to the superclass, then they all get stored in the `ex.arguments` dictionary. This dictionary is used in `hedy_error_to_response` to pass all the arguments into the error formatting strings found in `coursedata/texts/$LANG.yaml:HedyErrorMessages`.

That's very convenient, and the uniform mechanism removes the need for helper functions like `parse_error_to_response`.

At the same time, `hedy_error_to_response` also looks for an attribute called `location` on the exception and copies it into the response object if it exists, so that the client can use it to render error locations into the editor.

So there's no getting around either having:

```py
        self.location = location
```

In the exceptions for which `location` makes sense, OR treating the `location` argument specially in the `HedyException` class (and storing it in a location where `hedy_error_to_response` will be able to find it back).

I don't have a super strong opinion here. I think the following:

```py
class ParseException(HedyException):
    def __init__(self, *, level, location, keyword_found=None, character_found=None):
        super().__init__('Parse', level=level, keyword_found=keyword_found, character_found=character_found)
        self.location = location
```

And getting rid of `parse_error_to_response` would be a reasonable compromise.

`self.location` would still be a bit of an oddball in this scheme, so we might want to invent a better mechanism for that... or we could just accept it 😺

**Comment by rix0rrr** [comment]
The forced keyword arguments are probably a bridge too far. Let’s not do those 😅

**Comment by Felienne** [comment]
> The forced keyword arguments are probably a bridge too far. Let’s not do those 😅

Yeah I agree that is a bit too much Python magic for newcomers. But I like the idea of making the exceptions more systematic.

In fact I am not so upset with the two types because they are really different types of things: one comes from the parser, the other is something we throw ourselves. Maybe they should not have the same superclass and ParseException should not be a HedyException?

As for the two options, I really like the ** style but i can see how that is confusing for newcomers too, happy to unroll that for all exceptions although that would indeed lead to lots of more code.
