### ISSUE TITLE
[BUG] In levels 4-7 if and command separated by newline is valid, but adding an else makes it invalid

### ISSUE THREAD

**Issue by racertop** [Felienne/hedy#1196]
**Describe the bug**
Right now in levels 4 up to 7, when indents are added, this is valid code:
```
if name is Hedy
print 'awesome :)'
```
But once you add an else, it throws an ugly error:
```
if name is Hedy
print 'awesome :)'
else
print 'awesome too all names are beautiful'
```
![image](https://user-images.githubusercontent.com/45865185/140660022-336e84c6-24bc-4227-a0fc-a28f8944658d.png)
This happens because the rule `ifelse` does not contain the option for accepting newlines.

**Expected behavior**
It should be valid code and throw no errors.

**Comment by Felienne** [comment]
Closed by #1217
