### ISSUE TITLE
[BUG] If line contains only spaces in levels 8+ it throws parse error

### ISSUE THREAD

**Issue by racertop** [Felienne/hedy#1197]
**Describe the bug**
After indentation is introduced in level 7, if you type a line consisting of only spaces it will throw a ParseException, and the resulting error does not say space, it just says `" "`

**Paste the Hedy code & level**
```
repeat 3 times
    food is ask 'What do you want?'
    if food is 'pizza'
        print 'nice!'
         
```
**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/45865185/140667159-8f356e96-c88b-4f6e-b163-866f6ff7ca25.png)

**Expected behavior**
If this isn't valid code, say "You typed a space, but that's not allowed". I'd personally prefer this to be valid code

**Comment by Felienne** [comment]
Hi @racertop!

Thanks to #1211 this is now a bit better:

![image](https://user-images.githubusercontent.com/1003685/140897283-1445f6b8-bcbe-4543-9608-cdde899efe2e.png)

But I totally agree that it should be valid code!
