### ISSUE TITLE
A bulb icon image should be created

### ISSUE THREAD

**Issue by fRedelaar** [Felienne/hedy#1200]
At the moment a branch has been created where light bulb icon appears whenever (fixable) code fails to run. The light bulb icon has been taken from a website called [Free Icons Library](https://icon-library.com/). This was done to just have the code ready, and show the concept to other programmers.

The copy rights are not entirely clear however on this website. To protect Hedy from any Copyright Infringement risks, we could create a bulb icon ourselves.

Please create a similar bulb icon in .jpg .png, .jpeg or .svg. Please make sure to compress the image to decrease website loading time. 

Please make two versions so if people hover the icon, the bulb "lights up"

**Comment by TiBiBa** [comment]
As a light bulb is a relative easy shape, it might also be an option to use a built-in svg path. Such as `https://iconmonstr.com/light-bulb-thin-svg/`. This way we don't need any external resources or files.

**Comment by johannadekker** [comment]
@Felienne [Here is the light bulb](https://anonfiles.com/f7xdxfV0u9/Hedylightbulb_1_svg), the hovering icon where it lights up is currently being worked on.  As Github comments don't support .svg files, I added a link to download the file. I also added a little preview for anybody interested :)
![Screenshot 2021-11-16 at 11 28 23](https://user-images.githubusercontent.com/90705403/141972552-b19e9f5b-ffda-4a34-bb1a-032c433abc37.png)

**Comment by fRedelaar** [comment]
![image](https://user-images.githubusercontent.com/33595265/141974019-3412011d-f0aa-4854-9e96-bad9c7cf590c.png)

To give context view

**Comment by johannadekker** [comment]
[The hovering icon](https://anonfiles.com/J5E9x6V7ua/Hedylightbulb_2_svg) can be downloaded here as an .svg file.
![Screenshot 2021-11-16 at 12 24 32](https://user-images.githubusercontent.com/90705403/141977271-7c0ff286-baaf-43e4-8537-479af0a17ad8.png)

**Comment by fRedelaar** [comment]
https://user-images.githubusercontent.com/33595265/141980337-78cc1f91-e2b0-4fe6-a5a3-68b0d5a7ba23.mov

**Comment by Felienne** [comment]
Love the Hedy-bulb!! Can't wait to see it in action

**Comment by fRedelaar** [comment]
@Felienne I was wondering whether you are still interested in a 'Poof' animation? :) 

https://codepen.io/Dreamdealer/pen/mXZYNb (This one has a poof on deleting/clicking on one of the items, but I'm mentioned it as a reference)

**Comment by fRedelaar** [comment]
Closing this issue to reduce duplications. Issue #1378 is more relevant. The SVG file should be adjusted slightly.
