### ISSUE TITLE
[BUG] Green bar remains, confetti button is shown on each run

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1201]
**Describe the bug**
Every time I run code, the confetti button appears and also the green bar remains forever.

It is weird because I tried it yesterday and then it worked like your video in the PR (https://github.com/Felienne/hedy/pull/1189) so maybe one of the other changes accidentally changed this behaviour?

https://user-images.githubusercontent.com/1003685/140726929-670a466d-ed08-4ae3-95ab-50272f511496.mov

**Comment by fRedelaar** [comment]
Thanks for spotting it and creating an issue! Just so I understand correctly.. should the confetti behave like this? (Showing once, then disappearing after it has been clicked, **not** reappearing when clicking on the adventure tabs, and **reappearing** when going to the next level?)

Also, should the green bar disappear by itself after a couple of seconds? @Felienne 

https://user-images.githubusercontent.com/33595265/140733970-ef8d03ee-38e9-4cb4-a922-dc181176af9a.mov

**Comment by Felienne** [comment]
Yes I think it is fine like this, thanks for the quick fix!

**Comment by Felienne** [comment]
Closed by #1202
