### ISSUE TITLE
Come up with 5 succes-messages for different languages

### ISSUE THREAD

**Issue by fRedelaar** [Felienne/hedy#1220]
Stuff like "Well done", "Goob job!" etc.

**Comment by maximedongen** [comment]
Hi

**Comment by johannadekker** [comment]
French:
- Bien fait! (Goed gedaan)
- Bon travail!
- Bravo!
- Continuez comme ça! (Ga zo door)
- Beau boulot! (Good job)

**Comment by johannadekker** [comment]
Chinese: 做得好! (Well done)
Russian: Ты хорошо постарался, молодец! (You did a good job, well done!)
