### ISSUE TITLE
[Language idea] Lvl 11- Make quotation marks required after if commands

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#1227]
**Language idea incl level**
In level 11 the students learn to use quotation marks like this:

name is 'Hedy'
print name

This should also apply after the if command. 
So only allow _if name is 'hedy'_ and not allow _if name is hedy_

**Comment by Robernc** [comment]
Hello, @MarleenGilsing and @Felienne! Me and @[lexcov](https://github.com/lexcov) were wondering if we could work on this issue? I noticed that no one has done any work on this issue previously. I've already cloned the repo and been able to run it locally. Any suggestions would be greatly appreciated.

**Comment by Felienne** [comment]
For sure!

Let me know if you need help!

**Comment by Robernc** [comment]
I noticed that this issue is already implemented in level 12. Should this issue also be implemented in other levels?

**Comment by Felienne** [comment]
Ah sorry then those issue can be closed!
