### ISSUE TITLE
[BUG] UI horizontal scrollable when confetti is shown

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1233]
**Describe the bug**
Currently, when we press the newly implemented confetti icon the website turns wider than the screen. Enabling us to scroll horizontally. This issue stays until the confetti animates is done and disappears. In this case the width will return to normal and the scrollbar will disappear. Still, it would be nice to prevent this from happening at all.

**Paste the Hedy code & level**
It is super helpful if we can copy-paste the Hedy code to test, so please paste the code here, and don't forget to tell us what level you were in.

**Add a screenshot (optional)**
![Schermafbeelding 2021-11-11 om 14 37 31](https://user-images.githubusercontent.com/38155424/141307771-c47c6e82-4df9-4736-9c83-95751d50616d.png)

**Expected behavior**

**What machine and browser you were using (optional)**
Safari 15.0 on MacOS 11.6

**Comment by TiBiBa** [comment]
@fRedelaar maybe you can take a look? If I remember correctly you implemented the confetti animation (which I really like btw!)

**Comment by fRedelaar** [comment]
Hi @TiBiBa ! Wow well spotted. I guess I was so excited about the confetti that I didn't notice the horizontal scrollbar :D. I've just taken a look at it, and you are completely right. I'll take a look at the code.
