### ISSUE TITLE
Add space after echo

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1258]
Since #898 `echo` gets weird since there is no more space after it:

![image](https://user-images.githubusercontent.com/1003685/141490872-49a898c8-496a-407c-928d-d8a79f23b9ff.png)

We need to fix that in `echo` itself by adding a space after the string, here:

https://github.com/Felienne/hedy/blob/4a478d16c47a33af418cf1e5e97122828edf10a7/hedy.py#L636

**Comment by eylu4090** [comment]
Hi, new to open source and looking to contribute! I've been able to build and run Hedy, and looking to tackle some first good issues and familiarize myself with the codebase. I was wondering if I would be able to claim this issue?

**Comment by Felienne** [comment]
> Hi, new to open source and looking to contribute! I've been able to build and run Hedy, and looking to tackle some first good issues and familiarize myself with the codebase. I was wondering if I would be able to claim this issue?

For sure! Let me know if you need help!

**Comment by eylu4090** [comment]
@Felienne #1269 resolves this issue. If this pr could be reviewed and linked to this issue, that would be awesome! Currently the workflow awaiting approval as I submitted changes from a forked repo!
