### ISSUE TITLE
[UI idea] "Development mode"

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1276]
At one point, kids want to make proper big programs and do not need the tabs anymore, but would rather have more space. Can we make a special "development mode" or something where the whole width of the screen is input and output (so no more grey side bars, and the menu bars using the whole width of the page)

We could maybe allow kids to resize the balance between input and output with a draggable separator (like in https://replit.com/)

(@TiBiBa let me know if this description makes sense!)

**Comment by TiBiBa** [comment]
Love the idea! Will make an example UI later today! I think we can add some toggle switch to change between "adventure / learning mode" and "hardcore programming mode".

**Comment by TiBiBa** [comment]
I just created an implementation and made a PR with an example. The resizing of the input and output with a draggable separator is not implemented (yet). I think it would be best to solve this in a separate issue as I (think) this is quite some work to implement.
