### ISSUE TITLE
[BUG] Class names can be duplicate

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1278]
**Describe the bug**
Currently, we are able to create multiple classes with an identical name. I think this is undesirable and should be prevented. Might be best to tackle this issue at the same time as #1152.

**Paste the Hedy code & level**
It is super helpful if we can copy-paste the Hedy code to test, so please paste the code here, and don't forget to tell us what level you were in.

**Add a screenshot (optional)**
Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.

**Expected behavior**

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
- What browser you were using (Chrome, Edge, Safari)

**Comment by TiBiBa** [comment]
We've written a fix for #1152 but for this issue we need database access. @fpereiro do you know if it is possible to retrieve the classes of a teacher by classname? Currently we are only able to use the class id to look up classes.

**Comment by Felienne** [comment]
> We've written a fix for #1152 but for this issue we need database access. @fpereiro do you know if it is possible to retrieve the classes of a teacher by classname? Currently we are only able to use the class id to look up classes.

Hi @TiBiBa! I can give you access to the tables in AWS (see Slack). I do not think we have an index on class by name now, but of course you can add it.
