### ISSUE TITLE
Use Syntax highlighting in quiz code

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1290]
We now make all code pink, but it would be nicer to use level-dependent syntax highlighting. 

![image](https://user-images.githubusercontent.com/1003685/141991678-4967013c-42fc-4996-8c7f-2afc089d5cbf.png)

We already have some logic for that in place, in use on the teacher's page: https://github.com/Felienne/hedy/pull/1148

**Comment by Felienne** [comment]
Ow and maybe you can take a stab at this too @TiBiBa? Should not be so hard since we already have it in the adventures and teacher's manual?

**Comment by TiBiBa** [comment]
Completely missed this message, will take a look!

**Comment by TiBiBa** [comment]
We currently don't have a function that can convert HTML elements into ace editors on demand. We will have, after merging #1812. So I think it would be best to wait until that PR is merged to prevent doing duplicate work.
