### ISSUE TITLE
Correct answers have newline issues

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1291]
For example in level 7:

![image](https://user-images.githubusercontent.com/1003685/141991645-bc19769d-66a8-4c07-9f34-d042f87c3a67.png)

**Comment by Felienne** [comment]
I am too lazy to check but is this issue still there @LterHaar? If so, can you try to fix it, or will we pick it up?

**Comment by LterHaar** [comment]
This is still an issue. I believe it can be fixed to show the correct answers as a code snippet? And not as text, when indentation is needed?

**Comment by Felienne** [comment]
> This is still an issue.

Thanks for checking!

> I believe it can be fixed to show the correct answers as a code snippet? And not as text, when indentation is needed?

There are two cases, sometimes the answer is code indeed, but here the output is text *with newlines*.

so it should be something like:

Het juiste antwoord is:

De kinderen riepen
Hoera! We gaan op vakantie!
Hoera! We gaan op vakantie!

It would be really nice if it could be shown as white text on a black background but at least we want the newlines.

Do you want to pick this up? If not also totally fine than @TiBiBa can maybe do it?

**Comment by TiBiBa** [comment]
I think we can simply fix this with HTML! @LterHaar you can try adding `style="white-space: pre-wrap;"` to the `<div>` enclosing the answer. This way the newlines are preserved. (There might also be a tailwind class supporting this, but not sure).

**Comment by Felienne** [comment]
Hi @TiBiBa! Lotus is almost finishing her project, maywe we can pick this up ourselves?

**Comment by TiBiBa** [comment]
Will take a look today! Should be easily fixable.
