### ISSUE TITLE
Thematic confetti for different Hedy levels

### ISSUE THREAD

**Issue by johannadekker** [Felienne/hedy#1294]
Now the confetti at the end of each level is the same. During a discussion with Felienne, she came up with the idea to customise the confetti for each level thematically.

**Additional context**
For example: 'Haunted House' gets ghost emoji confetti.
<img width="604" alt="Screenshot 2021-11-16 at 16 31 29" src="https://user-images.githubusercontent.com/90705403/142015206-78feffd6-90b7-4b7d-a39f-75df28af63ba.png">

**Comment by maximedongen** [comment]
hi

**Comment by fRedelaar** [comment]
Hi team, I made a contribution to this because I felt excited to work on it. I made it easier to customize the emojis per level. Please fetch the latest changes from the branch (thematic-confetti). Feel free to check it out, make changes (if necessary), and make a merge request :)

**Comment by fRedelaar** [comment]
Closing this since MR #1411 has been merged.
