### ISSUE TITLE
[UI idea] Allow teachers to customize "try-out" threshold and other overall settings

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1299]
**Idea incl level**
Currently teachers are able to create a class and get overall information of students. However, we would like to offer teachers a more customizable experience. Within the class overview they should be able to select the "try-out" threshold. But, it might also be nice to allow them to set restrictions on levels or adventures which will have to be completed before getting access to new levels. This would add a great deal of functionality for the actual teaching of Hedy to students.

**Additional context**
Below we summarize the functionality we want teachers to have (@OnnoEbbens it would be great if you have any suggestions!):

- Restrict students to specific levels
- Restrict students the next level until several conditions are met (x amount of programs, keyword usage)
- Customize the usage of try-out programs (x amount of times, only specific keywords are allowed)
- Customize adventures shown (Maybe only show first x or new adventures will have to be "achieved")

**Comment by TiBiBa** [comment]
I made a first attempt at class customization:

![Schermafbeelding 2021-11-17 om 13 13 08](https://user-images.githubusercontent.com/38155424/142198541-0f6d57e1-71f7-4315-b0d3-ca582bee74db.png)

**Comment by TiBiBa** [comment]
https://user-images.githubusercontent.com/38155424/142256085-456bc795-de17-47e5-9356-233f3b0f10ad.mov

**Comment by Felienne** [comment]
>  Schermopname.2021-11-17.om.18.54.24.mov

Wow awesome @TiBiBa!! This is going to be so useful for teachers!

Little question: Wat betekent "aantal volgend level"?

**Comment by Felienne** [comment]
> **Idea incl level** Currently teachers are able to create a class and get overall information of students. However, we would like to offer teachers a more customizable experience. Within the class overview they should be able to select the "try-out" threshold. But, it might also be nice to allow them to set restrictions on levels or adventures which will have to be completed before getting access to new levels. This would add a great deal of functionality for the actual teaching of Hedy to students.
> 
> **Additional context** Below we summarize the functionality we want teachers to have (@OnnoEbbens it would be great if you have any suggestions!):
> 
> * Restrict students to specific levels
> * Restrict students the next level until several conditions are met (x amount of programs, keyword usage)
> * Customize the usage of try-out programs (x amount of times, only specific keywords are allowed)
> * Customize adventures shown (Maybe only show first x or new adventures will have to be "achieved")

Something that we can consider (surely not for now!) is a feature where teachers can write their own adventures, with an option to "donate" them to the Hedy code base.

**Comment by TiBiBa** [comment]
> >  Schermopname.2021-11-17.om.18.54.24.mov
> 
> 
> 
> Wow awesome @TiBiBa!! This is going to be so useful for teachers!
> 
> 
> 
> Maybe we want something like a preview for the adventures so people do not have to switch from the teacher to the student view to decide which to use?
> 
> 
> 
> Little question: Wat betekent "aantal volgend level"?
> 
> 
> 
> 

Currently we only retrieve the adventure name and supported level to reduce server load. But I will take a look if we can also extract, for example, the explanation.

"Aantal volgend level" is the amount of correct programs required before the next level will be available. Will have to write that a bit clearer.

**Comment by Felienne** [comment]
> Currently we only retrieve the adventure name and supported level to reduce server load. But I will take a look if we can also extract, for example, the explanation.

Ah yeah makes sense. For now this is totally ok!

> "Aantal volgend level" is the amount of correct programs required before the next level will be available. Will have to write that a bit clearer.

Cool, so this is a bit of an unlocking feature too! I guess we also want to give teachers the option to open/close an entire level in a class (independent of student performance you probably want to prevent kids from going too far form the rest of the class)

**Comment by TiBiBa** [comment]
> > Currently we only retrieve the adventure name and supported level to reduce server load. But I will take a look if we can also extract, for example, the explanation.
> 
> 
> 
> Ah yeah makes sense. For now this is totally ok!
> 
> 
> 
> > "Aantal volgend level" is the amount of correct programs required before the next level will be available. Will have to write that a bit clearer.
> 
> 
> 
> Cool, so this is a bit of an unlocking feature too! I guess we also want to give teachers the option to open/close an entire level in a class (independent of student performance you probably want to prevent kids from going too far form the rest of the class)
> 
> 

That is already possible with the "hide level" checkbox (however, the back-end will still have to be implemented).

**Comment by Felienne** [comment]
> That is already possible with the "hide level" checkbox (however, the back-end will still have to be implemented).

Ah super!!
