### ISSUE TITLE
Small fixes to French translation

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#131]
From an email (Dutch)

- in niveau 5 (line 85 van de broncode) staat   nievau  terwijl niveau bedoeld wordt,
- in niveau 7 is de tekst bij de tweede stap in het Engels: What is 5 plus 5?  i.p.v. Combien font 5 plus 5?
- in niveau 6 stel ik alleen een wijziging voor in het derde voorbeeld om beter aan te sluiten bij de eerste twee voorbeelden van dit niveau:
-        Exemple: if reponse is 20 repeat 3 times print 'hurra! ' else repeat 2 times print 'désolé! '.

**Comment by fpereiro** [comment]
@Felienne https://github.com/Felienne/hedy/pull/153 this fixes the first and second point.

Regarding the third point, it's a good idea. But we should then change it on every language. Do we want to go ahead with this? If so, I'll do it on a different issue & PR.

Thanks!

**Comment by Felienne** [comment]
Yeah let's update in all langs, I agree it is a good suggestion.

Could also be a nice getting to know task for one of the students @fpereiro
