### ISSUE TITLE
Make expansion of lists non-terminals possible in the merger

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1311]
Several levels now redefine the list of commands with a lot of repetition, for example:

level 3:
`command: print | ask | turtle | assign | assign_list | add | remove | sleep | invalid_space | ask_dep_2 | echo_dep_2 | comment | invalid`

level 4:
`command: print | ask | turtle | assign_list | add | remove | sleep | ask_no_quotes| assign | print_no_quotes | comment | invalid
`

Would be nicer if we would define something like += and generate proper Lark in the merger

**Comment by Felienne** [comment]
Related to #921 (which I forgot I already wrote haha)

**Comment by racertop** [comment]
Hi! I'm interested in taking this one! Just to be sure, this would mean defining the list of commands for each level, isn't it? Because sometime we remove a command, in that case just a += wouldn't suffice. Although I'm not sure if this happens after level 2 when we remove echo?

**Comment by Felienne** [comment]
> Hi! I'm interested in taking this one! Just to be sure, this would mean defining the list of commands for each level, isn't it? Because sometime we remove a command, in that case just a += wouldn't suffice. Although I'm not sure if this happens after level 2 when we remove echo?

Yes, as a nice to have we might also want to be able to define something like -= to remove something, but I guess if we only do += first, that makes things already a bit better, so we can do -= separately.
