### ISSUE TITLE
Update to lark 1.0

### ISSUE THREAD

**Issue by bjorn3** [Felienne/hedy#1312]
https://github.com/lark-parser/lark/releases/tag/1.0.0

The new grammar composition feature of lark should make it possible to replace the current grammar merging of hedy.

**Comment by Felienne** [comment]
Yeah I saw that, it looks really promising! 

It will be a big refactor to update this (both fixing things that the update might break, and implementing the composition) 

Are you interested in picking that up @bjorn3?

**Comment by Felienne** [comment]
Closed by #1314
