### ISSUE TITLE
Usability: Explain why people should create an account

### ISSUE THREAD

**Issue by jdittrich** [Felienne/hedy#134]
There is the possibility to create an account, yet it is not clear why one should do so (I guess to retain progress? Otherwise, that might be stored in cookies or so, too)

The explanation should be added at least to the  [signup template](https://github.com/Felienne/hedy/blob/master/templates/signup.html) for account creation

**Comment by fpereiro** [comment]
Hi @jdittrich ! Indeed, the purpose of creating an account is to have the ability to save and restore programs.

We might add more functionality in the future (such as tracking your progress along a learning program) but for now that's not implemented yet.

I'll discuss with @Felienne , but to add an explanation is indeed a great idea.
