### ISSUE TITLE
[CONTENT] Remove support for the literal values 'right' and 'left' with the turn command from level 2 and up

### ISSUE THREAD

**Issue by boryanagoncharenko** [Felienne/hedy#1347]
**Describe the issue**
Currently, the turn command accepts integers and the literal values 'right' and 'left' for all levels.
With this issue, we want to make the turn command a bit closer to Python by removing the support for 'right' and 'left' literals starting from level 2. Thus, level 1 supports: `turn left`, `turn right` and `turn 190`, while level 2 and up support only `turn 190`.

**Expected text**
In level 2 there should be a brief description that the turn command supports only integers and no longer the keywords 'right' and 'left'.

**Comment by Felienne** [comment]
Guess this one is for you too @boryanagoncharenko?
