### ISSUE TITLE
[BUG] When an ask is present in a program, the turtle arrow disappears

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1361]
**Describe the bug**
When an `ask` is present in a program, the turtle arrow disappears but otherwise, turtle programs work fine.This seems to happen at all levels and it does not matter if the ask has anything to do with the turtle code (like entering a value that is used in the turtle, that is *not* needed for this bug to happen)

I have no clue what can cause this!

**Paste the Hedy code & level**
For example level 1:

```
ask Wat is je lievelingskleur?
turn right
forward 50
turn left
forward 50
```

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/1003685/143011774-cbe1deef-723d-4e22-9e9f-01544a2925e0.png)

**Expected behavior**
Turtle should be shown.

**Comment by TiBiBa** [comment]
It should be fixed with the referencing commit, will make a PR!
