### ISSUE TITLE
Vanaf level 3 klopt de quiz niet meer.

### ISSUE THREAD

**Issue by apdekker93** [Felienne/hedy#1380]
De quiz van level 3 gaat over level 4. Het lijkt erop dat level 2 nieuw is, maar dat nog niet alles daarop aangepast is. Dat begint bij "Vooruitblik" in level 3: "In level 4 wordt dit probleem opgelost door aanhalingstekens te gebruiken, kijk maar eens in level 3." (die laatste 3 moet denk ik ook 4 zijn). De quiz gaat nog over de oude level 3 (nu level 4).

**Comment by Felienne** [comment]
Ja dat klopt, we zijn hier al van op de hoogte en er wordt aan gewerkt! Zie verder #1320.

Als je wilt kan je natuurlijk ook zelf een pull request maken om het op te lossen!
