### ISSUE TITLE
[UI idea] Allow teachers to load students into class

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1386]
For example from a csv file with username, email, and password so kids do not have to click. 

After loading, this feature should:

* Generate an account for each email address
* Add the accounts to the class
* Send email to change password to all accounts

**Comment by Felienne** [comment]
Hi @jpelay!

Hope it is ok if we assign this to @TiBiBa instead? We can use your brains better on the grammar stuff, you are one of the few people that know how it works :)

**Comment by TiBiBa** [comment]
I just started working on this and have some issues how we would like to approach the issue. I think reading a .csv file is cumbersome. Teacher have to provide it in the correct format and we have to use some library to read, parse and store the data. Other than that we still have some thinks to keep in mind:

- What do we do with the optional sign-up fields?
- Do we automatically set the account language to the teacher language?

I made a first UI attempt with (what I think) would be a good approach. Create an overview where teachers can add x amount of placeholders, for which they can fill usernames, mail-addresses and passwords. One useful thing to add might be that teachers can right away put the account in their class.

![Schermafbeelding 2022-02-01 om 14 38 15](https://user-images.githubusercontent.com/38155424/151978970-ed51767c-ac80-4a90-ba71-ca6094ab24b2.png)

**Comment by jpelay** [comment]
> Hi @jpelay!
> 
> Hope it is ok if we assign this to @TiBiBa instead? We can use your brains better on the grammar stuff, you are one of the few people that know how it works :)

Yes no problem, sorry for not being able fo complete it 🥺. I'm not that good on front-end stuff.

**Comment by Felienne** [comment]
> sorry for not being able fo complete it 🥺. I'm not that good on front-end stuff.

No problem, we are happy with all your contributions! But indeed your help is most valuable at the grammar I think.
