### ISSUE TITLE
[UI idea] Frequently made mistakes page needs an update

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#1389]
Not only the content (which I will take care of myself) but also the lay-out of this page needs an update. Right now, somehow most mistakes are mentioned twice and the indentation with the bulletpoints looks very messy. 

Maybe @TiBiBa can take a look at it and maybe add some buttons, so that the teachers can select the level of which they want to see the frequently made mistakes? Because now it's just a long messy list. 
Maybe you or @Felienne have some other ideas as well about how we can make it more structured and look more clear?

**Comment by TiBiBa** [comment]
> Not only the content (which I will take care of myself) but also the lay-out of this page needs an update. Right now, somehow most mistakes are mentioned twice and the indentation with the bulletpoints looks very messy.
> 
> Maybe @TiBiBa can take a look at it and maybe add some buttons, so that the teachers can select the level of which they want to see the frequently made mistakes? Because now it's just a long messy list. Maybe you or @Felienne have some other ideas as well about how we can make it more structured and look more clear?

Agree! The problem is that we are pretty limited on styling the page due to the code structure with which we use .md-files for our texts. We are unable to clearly "see" the content and therefore style accordingly. I would propose to re-structure the page to use *.yaml files, enabling us to better structure (and adjust to) the content. What do you think @Felienne?

**Comment by TiBiBa** [comment]
I will make an attempt today with re-structuring the file using *.yaml structure, creating a dedicated file for the for-teachers page (as it will probably become a large file on the long-run).

**Comment by Felienne** [comment]
That would be great, because it would also make translation easier!

Felienne

**Comment by TiBiBa** [comment]
I re-structured the for-teachers page from the dependency on a .md file on the *.yaml structure, using a similar dict structure as used for storing the adventures. Currently all 'nl' texts are copied, which also seems to solve some duplicate text errors we had when using the .md files. Changes can be found in [this](https://github.com/Felienne/hedy/tree/cleanup_for-teachers_structure) branch. @MarleenGilsing @Felienne can you both take a look if this is the preferred solution? If so, I will copy the content for other languages as well.
