### ISSUE TITLE
[UI idea] Check for duplicate translations of keywords on the translation page

### ISSUE THREAD

**Issue by teundemast** [Felienne/hedy#1402]
There can not be duplicate translations for keywords, for example: elif and else can't be both translated to the same word. 
With PR #1376 a warning was added on the [translatepage](https://hedycode.com/translate/en/new): 
<img width="371" alt="Capture" src="https://user-images.githubusercontent.com/36051227/143310522-677f64a8-6a3b-4a9d-ae3d-c933d73a9899.PNG">
With this PR there is made sure that when transforming the keyword yaml files to lark files, there can not be any duplicate translations in the yaml file. 
But what would be nicer, that an error is given when a duplicate translation is filled in at the translate page. Something like this:

![duplicate](https://user-images.githubusercontent.com/36051227/143579559-897ac568-35f2-4fb4-b80c-38d3cafe2c2c.png)

**Comment by Felienne** [comment]
This is a tricky issue because in some cases we do allow the same words for keywords (`for x in range x TO y` and  `add X to Y` , or `for x in N` and `in x in N`. So a generic warning can not be given. I now manually need to do some actions to create a new lang anyway so I can keep an eye on this.
