### ISSUE TITLE
Not showing For teachers, My profile and My programs tabs [BUG]

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#1425]
**Describe the bug**
When I go to hedycode.com I only see only 4 tabs: Home, Hedy, Learn More and Log in and not the three tabs (For teachers, My profile and My programs) that I need. When I go to Log in I am already logged in. Only when I logout and log back in again the 3 tabs (For teachers, My profile and My programs) appear. Every time I reopen my browser I have to do this again. I tried deleting my cookies but it did not help.

**Paste the Hedy code & level**
NA

**Expected behavior**
It would be nice if I can stay logged in and see all relevant tabs every time I go to hedycode.com 

**What machine and browser you were using (optional)**
I use Windows 10 with Firefox. I got the same problem when using Edge and Chrome.

**Comment by rix0rrr** [comment]
I don't know exactly but I have a good suspicion what's causing this. Will have a thorough look in a couple of days. Thanks for reporting!
