### ISSUE TITLE
Running the forward example after the echo example in level 1 [BUG]

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#1427]
**Describe the bug**
In level 1, if I first run the `echo` example and then the `forward` example the output screen remains black and no line is shown. With the examples I mean the command examples from the pane on the left. This also happens when I use the `turn` example instead of the `forward` example. I think it has something to do with the `ask` command but I am not sure.

**Paste the Hedy code & level**
first I use this:
```
ask What is your favorite color?
echo so your favorite color is 
```
after running I replace the code with this:
`forward 100`

The feedback is positive but no line is drawn (see screenshot)

![image](https://user-images.githubusercontent.com/10562903/144061095-34c3efd9-7e20-42c4-8690-e0df0e071ff4.png)

**Expected behavior**
I want to see a line when I run `forward 100`

**Comment by TiBiBa** [comment]
I've found a fix! This is due to us using `hide()` on the turtle canvas when we get user input. But, we forget to toggle the canvas again on a new run (so it is still hidden...). Will make a PR with a fix right away and it should be fixed in a minute.

**Comment by OnnoEbbens** [comment]
Thanks!
