### ISSUE TITLE
No output when running the print example after the forward example, related to #1427 [BUG]

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#1437]
**Describe the bug**
In level 1, when I run the `print Hello welcome to Hedy!` example after running the `forward 100` example I don't see the output. This is probably related to #1427.

**Paste the Hedy code & level**
first I use this:
 `forward 100`

after running I replace the code with this:
`print Hello welcome to Hedy!`

The feedback is positive but no text is printed.

**Expected behavior**
I want to see Hello welcome to Hedy when I use `print Hello welcome to Hedy!`

**Comment by TiBiBa** [comment]
I can't seem to re-produce this issue locally or on hedycode.com!

**Comment by Felienne** [comment]
Same as @TiBiBa, for me this combination on programs works fine. Maybe a hard refresh can help @OnnoEbbens? I deployed this morning so maybe you are/were looking at an old version?

**Comment by OnnoEbbens** [comment]
A hard refresh solved the problem, thanks!
