### ISSUE TITLE
[UI idea] Keep the scrollbar in the output screen down with long codes.

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#1448]
When you're running longer codes, everytime you answer a question the output screen scrolls up after you answer the question. So you have to scroll down to see the rest of the code. It would make more sense if you didn't jump to the beginning of the code everytime you answer a question. 

For example: play the calculator game in level 9 (till the end) and you'll know what I mean.

**Comment by Felienne** [comment]
Maybe this is a task for you @fRedelaar?

**Comment by fRedelaar** [comment]
> Maybe this is a task for you @fRedelaar?

I’ll take a look at it :)
