### ISSUE TITLE
[BUG] Page titles are inconsistent

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1449]
**Describe the bug**
Page titles are currently inconsistent. The pages that rely on a .md file had a correct page_title as this is given in the file itself. However, all other pages such as for-teachers and login just so the url. This is not likely and should be solved.

**Expected behavior**
Each page should so a clear page title

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
- What browser you were using (Chrome, Edge, Safari)

**Comment by Felienne** [comment]
As a small addition to this issue, /admin has no title at all which is annoying since I keep losing the tab (guess this is only annoying for me but if we are fixing page titles anyway, I'd like that to be fixed too)

**Comment by TiBiBa** [comment]
Will take a look into that as well! I don't think there is a place where we store the (translated) page names? I noticed we have a file for translated menu names, but that isn't complete either (missing my profile for example).
