### ISSUE TITLE
Rename main folder

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1459]
Since #1447 the main folder only contains the menu, maybe we can rename it of move menu to `/`?

Not hard to do but it requires a good test to see if we do not break something cause this is not really tested (maybe we could add a few e2e tests to protect the menu against future issues?)

**Comment by rahulchandra17** [comment]
hey I want to work on this issue please assigne it to me.

**Comment by Felienne** [comment]
Thank you @rahulchandra17! Let me know if you need any help

**Comment by rahulchandra17** [comment]
can we move menu to '/'  and delete main folder

**Comment by Felienne** [comment]
Yeah that seems like a fine solution if it doesn't break anything

**Comment by rahulchandra17** [comment]
make a pull request please review it

**Comment by Felienne** [comment]
Closed by #1464
