### ISSUE TITLE
[UI idea] Update my profile page

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1467]
**Idea incl level**
Currently the my profile page contains the user information as well as the logout button and the option to change the user password. I would like to expand this page to contain more useful information. Will have to be brainstormed about, but for example:

- Total programs saved
- Maximum level saved
- Current classes (Students have no idea in which classes they are enrolled)

Also I would like to improve the overall UI to better align with the rest of the Hedy website. Especially shifting the logout button to a different place. In aligned with #1466 it would be great to implement a visual nice way to show the logout button when a user is logged in. As icons are already implemented, we might even be able to do this with a nice button.

**Comment by Felienne** [comment]
Nice idea @TiBiBa!

> **Idea incl level** Currently the my profile page contains the user information as well as the logout button and the option to change the user password. I would like to expand this page to contain more useful information. Will have to be brainstormed about, but for example:
> 
> * Total programs saved
> * Maximum level saved

Boryana was working on a similar issue but for teachers to see such stats (#1242) and for ourselves (#665) Maybe you can share some code?

> * Current classes (Students have no idea in which classes they are enrolled)

Hmmm this at one point was in the profile page (Not with a lik or anything but just a flat list) Is that somehow removed?

> Also I would like to improve the overall UI to better align with the rest of the Hedy website. Especially shifting the logout button to a different place. In aligned with #1466 it would be great to implement a visual nice way to show the logout button when a user is logged in. As icons are already implemented, we might even be able to do this with a nice button.

Good idea! Guess that is easier now that we got rid of the md's?
