### ISSUE TITLE
General introduction level 5 not scrollable at first[BUG]

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#1468]
**Describe the bug**
When I go to level 5 I start at the tab "level 5" with the general introduction. This tab has a lot of explanation which I think is great but because of this I cannot see the coding and output panes immediately. When I click on one of the adventures and go back to the "level 5" tab, the explanation tab changed and is scrollable now. Now I can see the coding and output panes. It would be nice if the "level 5" tab will always be a scrollable pane.

**Paste the Hedy code & level**
NA

**Add a screenshot (optional)**
When first arriving in level 5:
![image](https://user-images.githubusercontent.com/10562903/144741742-1e247d5c-9205-4ce0-8a1c-a926ea3d211c.png)
After clicking on an adventure and going back (desired configuration):
![image](https://user-images.githubusercontent.com/10562903/144741939-d23e3d83-25be-477c-86dc-50ddeaadf87c.png)

**Expected behavior**
A scrollable explanation pane at the moment I arrive in level 5, see second screenshot.

**What machine and browser you were using (optional)**
Windows with firefox

**Comment by TiBiBa** [comment]
Weird! It seems to be the case for each level. It might have something to-do with the order in which we load the styling and the adventures. Will take a look later today!

**Comment by TiBiBa** [comment]
Fixed! Just made a PR that solves the issue.
