### ISSUE TITLE
is, = and ==?

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1475]
### Discussed in https://github.com/Felienne/hedy/discussions/1274

1. In current level 6 when we add calculations, change `is` in assignments to `=` 
2. [NEW!] And change `is` in _conditions_ to `=` too 
3. In current level 12 where we introduce < and >, we also switch `is` in conditions to `==`

I think in all situations we want to allow both, or give a warning but not a hard error for the use of `is`.

**Comment by hapiel** [comment]
`=` is an action, `is` is a conclusion. Maybe it is an option to replace `is` as `=` with `becomes`
`count becomes 1` == `count = 1`
`count is 1` == `count == `

Just a random idea, can't tell if it's worth considering or if this overcomplicates stuff.

**Comment by Felienne** [comment]
> `=` is an action, `is` is a conclusion. Maybe it is an option to replace `is` as `=` with `becomes`: `count becomes 1` == `count = 1` `count is 1` == `count == 1`
> 
> Just a random idea, can't tell if it's worth considering or if this overcomplicates stuff.

Yeah initially we use `is` for both assignment and conditions and we slowly want to move to Python, so the switch is part of that.

I could see how `becomes` would be a great word initially for assignment, better conceptually that `is` but that does create two different words, which we deemed too complex

**Comment by Felienne** [comment]
Closed by #1504

**Comment by Felienne** [comment]
Closed entirely by #1580
