### ISSUE TITLE
[UI idea] When logged in, set language automatically to user preferred language

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1478]
**Idea incl level**
Currently the UI is set to a user selected language. When logging in the language will stay the same. However, when we built upon #1477 the language selection will disappear from the menubar when logged in. In this case we would like the user to selected a preferred language in the profile settings to use every time the user is logged in. This should be aligned with #1467 to make sure users are able to change their preferred language on the profile page.

**Comment by Felienne** [comment]
Lovely idea! 

I guess we can ask preferred language on signup for new accounts, and ask existing users to set it once in their profile?
