### ISSUE TITLE
Set the local_lang_bool to True only when running tests

### ISSUE THREAD

**Issue by emil-meyknecht** [Felienne/hedy#1482]
@Felienne 

Currently, the local_lang_bool is set to false as the translation structure is not compleet and might interfere with the live hedy site.
Now the boolean has to be manually changed when running tests which otherwise the translation tests are not run.

By changing the boolean to False or 'pytest' in sys.argv[0] we can set the boolean to true only when running tests

![Screenshot 2021-12-06 184706](https://user-images.githubusercontent.com/45172042/144895942-7a4b3c6f-b3d8-4041-bee9-1e5ab217e6d3.png)

This could be done in hedy.py where the boolean is found

**Comment by Felienne** [comment]
Good idea!
