### ISSUE TITLE
Level 7 error

### ISSUE THREAD

**Issue by fpereiro** [Felienne/hedy#149]
Happens January 28 2021 onwards, after replacing 82d2a634a97d3fed1ac23c5891ebe3383650682a with 7655e9e70d19549177503d4ea5e70cfbea32e383.

Changes: https://github.com/Felienne/hedy/compare/82d2a634a97d3fed1ac23c5891ebe3383650682a...7655e9e70d19549177503d4ea5e70cfbea32e383

```
Unexpected token Token(__ANON_11, " print 'xyz!'") at line 5, column 21."Expected one of: "	* __ANON_1"	* __ANON_6"	* _EOL"	* __ANON_5"
```

**Comment by Felienne** [comment]
I don't know that the error is here because there is no example program given, closing
