### ISSUE TITLE
[BUG] Not accounting for new lines when translating code with with for example an if-else statement

### ISSUE THREAD

**Issue by teundemast** [Felienne/hedy#1493]
**Describe the bug**
When translating the following piece of code:
<img width="442" alt="Capture" src="https://user-images.githubusercontent.com/36051227/145073426-07abbc52-5874-4126-ad4c-fc0794971825.PNG">
The output is as follows:
<img width="669" alt="Capture1" src="https://user-images.githubusercontent.com/36051227/145073451-b39bd5e6-9f34-4a71-970b-77510495783e.PNG">
The problem is that the translator does not include a new line for the else statement.

**Comment by Felienne** [comment]
Fixed!
