### ISSUE TITLE
Calling translate_keywords

### ISSUE THREAD

**Issue by Livavdv** [Felienne/hedy#1498]
We are working on the translate_keywords function in hedy_translation.py. We want to call on this function so it will translate the keywords in the written code when you change the language on the website. However, we can't find a way to do this without parsing the code. Do you have any suggestions on where and how we could implement this? @Felienne @brucemartens

**Comment by Felienne** [comment]
I don't see how this is possible without parsing the code! (which also seems to me to be a fine solution, why would we want to avoid that?)

**Comment by Felienne** [comment]
Closing this, we will not translate all language snippets but instead add a switcher in the UI (see #1577)
