### ISSUE TITLE
[BUG] The example codes in what's next adventures don't always work

### ISSUE THREAD

**Issue by teundemast** [Felienne/hedy#1506]
If the language is Dutch, running the demo code in 'Vooruitblik' (or Fortune Teller in English) gives an error. Is this the intention, because it is in 'Vooruitblik', @Felienne ? 
<img width="503" alt="Capture" src="https://user-images.githubusercontent.com/36051227/145233083-a58b2b8c-1e45-48df-8900-4f78e1974b83.PNG">

**Comment by MarleenGilsing** [comment]
The fortune teller adventures do work. The what's next (vooruitblik) adventures sometimes don't work yet.

**Comment by Felienne** [comment]
Yeah that is the case because it is level 8 code shown at level 7, @MarleenGilsing will change the examples.

**Comment by Felienne** [comment]
Hi @MarleenGilsing! 

Thanks for working on this issue! In principle we don't close issues until the PR's are tested and merged, so is m reopening this one until I merge your fixes :)

**Comment by Felienne** [comment]
Closed by #1557
