### ISSUE TITLE
[BUG] Re-direct to class customization after creation is broken

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1510]
**Describe the bug**
Due to the re-structure of class customizations as a sub-url of the `/for-teachers/` section the re-direct url of the class customization is incorrect. Resulting in a 404 error page. Directly navigating to class customization from the for teachers page does work, only the re-direct after creation is broken. Can be solved easily by adjusting the re-direct url on the creation function to include `/for-teachers/`.

**Expected behavior**
After class creation you should correctly be re-directed to the class customization page.

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
- What browser you were using (Chrome, Edge, Safari)

**Comment by ThomasKluiters** [comment]
Seems like #1543 fixed this :) Awesome!
