### ISSUE TITLE
[UI idea] Implement "unlocking levels through achievements"

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1516]
**Idea incl level**
Currently users are able to navigate through all levels and from the moment of entering the Hedy environment execute code on all these levels. It would be nice to have a bit more of an "enforced" level-structure. We already have a "forbidden" level structure implemented through the level customization dashboard so we are already able to hide specific levels for users. We can built upon this concept and the idea is as follows:

- We define achievements per next level (keywords used, programs created etc.)
- Students can see these achievements and receive badges when meeting the requirements
- When a certain threshold of achievements is achieved (for example, 60%; the next level is unlocked)

We should include this into the teacher customization to allow the teacher the following additional settings:

- Define relevant achievements
- Customize amount for these achievements (x amount of keywords used etc.)
- Customize threshold

Several other nice to have features would be:

- Global ranking of badges achieved
- Public profile with user overview of general statistics
- Profile overview of all achieved and to-be achieved achievements
- Implement some "global" achievements that only one user can have (most programs, most classes etc.)
- Implement "hidden" achievement which are a surprise until you get it!

**Food for thoughts**

- Should we implement the achievements as a dict on the user table or create a new table?
- For achievements (total amount of programs created for example) we have to keep track of a lot more of user data
- Might be useful to create an additional POST at every run containing relevant program info

**Comment by Felienne** [comment]
This (closed) PR  aimed to do something a bit similar, maybe that can be helpful when you start to work on this? https://github.com/Felienne/hedy/pull/1483

**Comment by TiBiBa** [comment]
> This (closed) PR aimed to do something a bit similar, maybe that can be helpful when you start to work on this? #1483

That looks great! After fixing the issues with the profile page UI and improvements I will start working on this issue. Hopefully I will get it done this week.

**Comment by Felienne** [comment]
Ah I closed this but technically, this is not ready since we don't use achievements to *unlock* levels. Shall we rephrase this a bit to just be achievements and open a new issue for unlocking levels?

**Comment by TiBiBa** [comment]
> Ah I closed this but technically, this is not ready since we don't use achievements to _unlock_ levels. Shall we rephrase this a bit to just be achievements and open a new issue for unlocking levels?

Agree! With change the title so this one can be closed and will create a new issue specifically for the level unlocking.
