### ISSUE TITLE
Have teacher accounts and enable teachers to add accounts to their class

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#152]
This is really a feature for the far future, but it would be so lovely for teachers to be able to see what kids in their class build to help and monitor. I use this all the time in teaching, but I look directly in the DB :)

**Comment by moorlag** [comment]
As a teacher, I'd love to see a total overview of a class (and/or year).
Who is 'productive'.  GitHub activity view is a great way to see if a
student is staling, not as a means of control but as a means of 'what are
we doing'.

[image: Screenshot 2021-02-16 at 12.49.21.png]

>

**Comment by fpereiro** [comment]
Interesting! Off the top of my head:
- We should be able to create and manage groups and have one or more "teacher accounts".
- We should have usage statistics per user (that's a separate task that we should task first).
- We should summarize/itemize the individual progress into a "teacher dashboard".

**Comment by moorlag** [comment]
I would also love to see a 'bolletjes' progress in the top of the window. 
So that with one glance I could keep track of progress looking across the classroom.

**Comment by moorlag** [comment]
https://skyline.github.com/

Also a cool gift when students finish the course. 3D-print on demand? Ever
x gets a free print?
-- 
Via Gmail mobile. This email may be shorter due to a small keyboard.

**Comment by Felienne** [comment]
> * We should be able to create and manage groups and have one or more "teacher accounts".
> * We should have usage statistics per user (that's a separate task that we should task first).
> * We should summarize/itemize the individual progress into a "teacher dashboard".

@fpereiro You had some good ideas here :) 

Shall we make a few users stats to show in the teacher's dashboard? Maybe longest program? Did you have some others in mind?

**Comment by fpereiro** [comment]
Great! Closing via #665
