### ISSUE TITLE
[CONTENT] Typos in English level 1 questions 7 and 9

### ISSUE THREAD

**Issue by johannadekker** [Felienne/hedy#1531]
I have attached screenshots from the English-language level 1 quiz below. You can see that in both questions, option B has some mistakes. 7b) states "In line 1 **moet** print needs to be replaced with echo". 9b) states "print in line should be **aks**".

![Screenshot 2021-12-09 at 13 08 21](https://user-images.githubusercontent.com/90705403/145598983-29b47cf9-983c-4abb-805a-0e6eb5ff1d00.png)
![Screenshot 2021-12-09 at 13 08 41](https://user-images.githubusercontent.com/90705403/145598994-e2fa297a-ebf1-473b-92fe-0ea6e1f3a607.png)

**Comment by Felienne** [comment]
Closed by #1532
