### ISSUE TITLE
[BUG] English language level 2 quiz only has one question

### ISSUE THREAD

**Issue by johannadekker** [Felienne/hedy#1533]
In the screenshot below, you can see that the level 2 English-language quiz only has 1 question. The .yaml file does contain all four questions needed. I am unsure as to where the error is exactly.

![Screenshot 2021-12-10 at 16 44 18](https://user-images.githubusercontent.com/90705403/145607247-99e274d6-5441-4626-bd26-a912849232c0.png)

**Comment by bjorn3** [comment]
The questions after question 1 are indented one level too much, causing them to be fields on question 1 instead: https://github.com/Felienne/hedy/blob/0a428143d27e18354624b397def6623d39732e1a/coursedata/quizzes/en.yaml#L168-L183 Notice how the last line in this snippet doesn't have the same indent as the first line.
