### ISSUE TITLE
[CONTENT] "No such Hedy level" message missing in langs other than English and Dutch

### ISSUE THREAD

**Issue by eddieantonio** [Felienne/hedy#1538]
**Describe the bug**

When accessing a level that is not translated in my language (e.g., as of 2021-12-13, level 10 is not available in Spanish), I get an error message _in English_:

> No such Hedy level!
>
> <kbd>Go back to main page</kbd>

**Paste the Hedy code & level**

Currently this occurs on levels 9 and 10 in Spanish, and level 10 in Italian. Either put your browser's primary language in Spanish or Italian, or add the query param `?lang=es` to the level URL, i.e.,

<https://www.hedycode.com/hedy/10?lang=es>

**Add a screenshot (optional)**

![Screenshot of Hedy in Spanish, however the error message is in English reading 'No such Hedy level!'](https://user-images.githubusercontent.com/2294397/145787611-a20e8c2e-243f-443a-bf98-efa9f6b09641.png)

**Expected behavior**
If the level is not translated yet, put a polite error message **in the appropriate langauge**. i.e,

> Este nivel aún no está listo. Por favor, espere hasta que esté disponible. 🙇
>
> <kbd>Atrás</kbd>

**What machine and browser you were using (optional)**

macOS 11.6.1; Chrome 96.0.4664.93. `Accept-Language` header

    Accept-Language: es-US,es;q=0.9,en-IE;q=0.8,en-CA;q=0.7,en;q=0.6,es-419;q=0.5

**Comment by Felienne** [comment]
Ah thanks for pointing this out @eddieantonio!! In principle, we already have the architecture for this. If you would add field 

no_such_level: 'No such Hedy level!' (to be found here: https://github.com/Felienne/hedy/blob/5345052fe62a01c9f78cab1bda5489cf1557de04/coursedata/texts/en.yaml#L44)

Of course another solution would be to translate the missing levels haha!

to es.yaml this would work!

So this is not so much a bug as it is a content issue, when we encounter fields that do not yet have a translation, we fall back to En.

**Comment by Felienne** [comment]
Hi @eddieantonio!

I did not close this yet because you said in #1539 that this issue was not yet fixed that PR, but I do not understand why not, can you let me know?

**Comment by eddieantonio** [comment]
Hi @Felienne.

#1539 did indeed fix the initial issue I had: the error message was not translated into Spanish, and #1539 provided translations for Spanish! 🚀 

However, I'm interpretting this issue's title in a persnickety, overly litreral way; namely, '"No such Hedy level" message missing in langs **other than English and Dutch**', which I assume is still true for many languages :/

Feel free to close this issue if you find my interpretation overly pedantic — it's definitely finished for Spanish. Do you have some automated way to track translation coverage for other languages? That is, do you measure how much UI text or course text is fully-translated, relative to more "complete" languages like English and Dutch?

**Comment by Felienne** [comment]
Hi @eddieantonio, currently, we have no good way of tracking missing content, and we tend to not open issues for that or we would have hundreds :) So I hope it is ok if I close this one.

In the new year, we will work on a better tracking system for yaml files where translators can subscribe to content and get a notification when things are changed.

The best thing we have currently is the translation UI, for example for Spanish: https://hedycode.com/translate/en/es

You can click 
![image](https://user-images.githubusercontent.com/1003685/146341828-716ba018-95a5-444a-a913-b40fd77f25d7.png)
 to see the things that still need a translation.
