### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by henrikmidtiby** [Felienne/hedy#1572]
The webpage https://www.hedycode.com/ contains a mixture of text written in English and Dutch. See the attached pdf
The issue is that some the the headlines are in dutch, while the rest of the text is in english.

[Hedy - A gradual programming language.pdf](https://github.com/Felienne/hedy/files/7761162/Hedy.-.A.gradual.programming.language.pdf)
.

**Comment by Felienne** [comment]
Yes, we know, has already been fixed: https://github.com/Felienne/hedy/pull/1569

Test env already shows the new version: https://hedy-alpha.herokuapp.com/ we will deploy to the main site shortly.
