### ISSUE TITLE
[UI idea] Show overview of all shared programs in admin view

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1573]
Would be really nice if we have an overview of all shared programs!

/admin is already quite full so I guess we want a fresh page?

**Comment by TiBiBa** [comment]
I can take a look at this! Think that the explore page in #1656 is pretty close to this idea! However, the admin is unable to select a favorite program there and filtering can only be performed on level and adventure. I can imagine that the admin might want some more advanced filtering options.

**Comment by Felienne** [comment]
> I can take a look at this! Think that the explore page in #1656 is pretty close to this idea! However, the admin is unable to select a favorite program there and filtering can only be performed on level and adventure. I can imagine that the admin might want some more advanced filtering options.

Thanks @TiBiBa but I think we have this covered with the explore page. 

For me as admin to search, we can more easily integrate this into the stats that @boryanagoncharenko is already making!

@boryanagoncharenko could we add "is_shared" as a field we can search on in the stats? I guess that is pretty simple and allows me to see the shared programs.

**Comment by boryanagoncharenko** [comment]
> @boryanagoncharenko could we add "is_shared" as a field we can search on in the stats? I guess that is pretty simple and allows me to see the shared programs.

Do you mean an is_shared field in log search part? So parse logs should contain the data whether a program is shared and then the /stats page would have another box that lets you filter on is_shared? That should be no prob.

**Comment by boryanagoncharenko** [comment]
I am a bit unclear how to correlate a program run with a shared program. The parse logs (which are used in the /stats page) contain info for program code executions. I thought that when a program is ran, we know whether it is saved / shared or not. But it seems that the only to know whether a given code is a saved / shared program is through comparing the executed code with the code of saved user programs. However, in this case there could be multiple saved programs with identical code, so it would be hard to determine which one to pick. Am I missing anything?

May be it is easier to query dynamo's PROGRAMS table to get an overview of the shared programs. Querying in the AWS console would allow to validate if this is enough and then we could add shared program searching in the /stats page as a separate accordion page.

**Comment by Felienne** [comment]
Never mind I can use explore for this!
