### ISSUE TITLE
[UI idea] Make public overview of all shared programs

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1575]
Also related to #1573, make a public version here kids can browse all shared programs, like Scratch has:

![image](https://user-images.githubusercontent.com/1003685/147063787-37a9fa75-2b1e-4f28-9d71-15d32b048218.png)

Guess we have to think about if we also want thumbnails or just links (guess just links is totally fine for now)

**Comment by TiBiBa** [comment]
I really like this idea! I think it is relatively easy to implement this in a dedicated "explore" page. We have one edge case to consider: A submitted program is also a shared program; but I assume it is undesirable that these are available on this page as well.

**Comment by Felienne** [comment]
Yeah I like it too, I think one of our "big hairy goals" for 2022 should be to turn Hedy more into a community where kids can also learn from and get inspired by each other (fit also with your plan to make public user profiles!)

**Comment by Felienne** [comment]
> I really like this idea! I think it is relatively easy to implement this in a dedicated "explore" page. We have one edge case to consider: A submitted program is also a shared program; but I assume it is undesirable that these are available on this page as well.

Ah interesting point! Guess we might not want to because then kids can "spiek" each others work (however, I guess they will find ways to share the programs via whatapp or email haha)

I am ok with not treating them as a special case for now to keep things simple.

**Comment by TiBiBa** [comment]
It might be nice to align this with the public profile and public high score page? Will create quite a big issue, but we have to ask user consent for all of these anyway. Or are we already allowed to show all shared programs? In that case we can implement this one first and then take a look at the other possible public pages.

**Comment by Felienne** [comment]
> It might be nice to align this with the public profile and public high score page? Will create quite a big issue, but we have to ask user consent for all of these anyway. 

Yes ultimately we want to align public profiles so that people can browse programs and then navigate on to users.

> Or are we already allowed to show all shared programs? In that case we can implement this one first and then take a look at the other possible public pages.

Yes users get a warning that their program will be made public so that is ok and we could start with that (also making the scope a bit smaller)
