### ISSUE TITLE
[BUG] Translation code does not preserve is/equal symbol

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1579]
The translation code works well but has one small caveat since we allow `is` and `=` for assignment from level 6 on (since https://github.com/Felienne/hedy/pull/1504), code that uses `is` (which is allowed) get translated to `=` because in the grammar (and thus in the AST) we do not distinguish between the two.

There is a test for this in the code since https://github.com/Felienne/hedy/pull/1578, describing the current (undesirable) state.

https://github.com/Felienne/hedy/blob/c0effe1c66c2115848dda65b3e4c8b0373e6aeda/tests/test_translation_level_06.py#L41

What we want is code remains as is when translating, so code with lines with a `=` keep that and lines using a `is` keep the `is`.

This is not a big deal of course because the code will still work in the new form but I think it is not pretty. And in conditions (allowed since #1561) the example code uses `is` but then when you would translate it, it would become `=`.

And there will a similar issue with `is` versus `=` versus `==` when we address 3. of #1475 too!

The solution is not hard perse, but is a bit intricate and would involve:
1. making separate rules for an assignment with `is` and one for assignment with `=`
2. rewriting the parser so both rules map to the existing code and output the same Python
3. updating the translation code for both rules differently.

**Comment by Felienne** [comment]
Maybe this would be a fun issue for you @racertop? Involves a bit of parser work that you now are quite comfortable with I guess and helps Spanish speakers!

**Comment by racertop** [comment]
Yes, of course! Thank you for considering me!
