### ISSUE TITLE
[Tests idea] Make Multilanguage tester

### ISSUE THREAD

**Issue by racertop** [Felienne/hedy#1589]
**Language idea incl level**
Right now the tests for the Hedy translator are hardcoded in each language. So, for example, if we want to test a feature there we'd call the test something like: `test_is_spanish_english` and it would include Spanish keywords.

I see 2 problems with this approach: only people who can speak the language can write the tests or understand it at first glance (I can understand Dutch tests, but I have to go to the grammar and see each definition),  and also, more importantly, we can only test one language at a time. 

Maybe we can do something like the Multilevel test, but for languages? We'd build each test so it take a generic placeholder like `lang['nl']['is]` and iterate through a language dictionary that contains all keywords for each language. Or perhaps this is not needed? Since the keywords for each language shouldn't affect the grammar and a test in a single language is all that is needed.

I'd love to read your input!

**Comment by Felienne** [comment]
Hi! 

I think this is a good idea that is not all too hard to implement. We could indeed make a dictionary of keywords and then use a parametrized test (like we do here, for example):

https://github.com/Felienne/hedy/blob/bede1281e6983d8ddc19b3f4a35763058f3a5326/tests/test_z_adventures.py#L60

You are right that, in principle, we should not have to tests all keywords for all languages, but I would say adding more tests is never bad, we don't know what weird interactions might occur when add more languages.

If you want to pick this up, please feel free to do so, if not, someone in the core team can do it too.

**Comment by racertop** [comment]
Great, I can take this one, but can't probably work on this until next week, if that's ok.

**Comment by Felienne** [comment]
> Hi! Thank you for your input. And yes, I can take this one, but can't probably work on this until next week, if that's ok for you.

Yeah no rush, we do have a few Dutch and Spanish tests now so we should be good for a while.
