### ISSUE TITLE
[UI idea] Make pop-up modal less intrusive on confirmation

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1594]
**Idea incl level**
Currently we confront the user with quite a lot of modal pop-ups. When storing, sharing or submitting a program. As well as deleting one or joining or leaving a class. When we require user feedback it is relevant that the pop-up is intrusive and the user's attention is drawn to the question at hand. However, when returning some confirmation as feedback for which we **don't** require user interaction it would be nice to make the information less intrusive. I propose to create a separate modal that only shows a minimalistic information bar in this case. Concrete, this happens when:

- A user saves a program
- A user shares/unshares a program
- A user deletes a progrma
- A user joins a class
- A user leaves a class

This improvement is in line with our long-term goal to change saving of programs into a more intuitive way of working for children. Note that there is already a `timeoutMS` attribute on which we can apply a value after which the `alert()` function is automatically hidden. However, I don't like this implementation and the feedback to users is unclear if the modal just disappears.

**Comment by Felienne** [comment]
Great idea @TiBiBa!

In another issue I was thinking about the 'ok' on the modal, maybe that should also be changed. In most cases the ok button means 'close modal' so maybe we should simply have a little X in the corner to close it. I know ok on a popup in many cases means close this popup but I find is a bit confusing.

https://github.com/Felienne/hedy/pull/1585#issuecomment-1001493110

**Comment by TiBiBa** [comment]
> Great idea @TiBiBa!
> 
> 
> 
> In another issue I was thinking about the 'ok' on the modal, maybe that should also be changed. In most cases the ok button means 'close modal' so maybe we should simply have a little X in the corner to close it. I know ok on a popup in many cases means close this popup but I find is a bit confusing.
> 
> 
> 
> https://github.com/Felienne/hedy/pull/1585#issuecomment-1001493110

Agree! This change should solve this problem as all modal pop-ups with only an "ok" (we just return the user some feedback) will be replaced with a new modal.

**Comment by TiBiBa** [comment]
I just noticed that the PR I just made conflicts with the solution of @fpereiro for the copy issue. Because I assumed the `alert` was only used for feedback and did not require user interaction both implementations won't align. Maybe we can use the `confirm` modal for the copying of the share link? Then it should work correctly next to each other.
