### ISSUE TITLE
[BUG] Sample code on level 13 fails

### ISSUE THREAD

**Issue by boryanagoncharenko** [Felienne/hedy#1608]
**Describe the bug**
Locally or on alpha, navigate to level 13 (lang en) and execute the sample code. The error "Unexpected end-of-input. Expected one of: * _SPACE * _SPACE" is returned, which is not expected.

**Paste the Hedy code & level**
Level 13
Code:
```
name = ask 'what is your name?'
leeftijd = ask 'what is your age?'
if name is 'Hedy' and age is 2
    print 'You are the real Hedy!'
```

**Add a screenshot (optional)**
![Screenshot 2022-01-03 at 21 09 38](https://user-images.githubusercontent.com/3010723/147970121-905c7498-3dd1-4320-bce1-777cf7ff7f2d.png)

**Expected behavior**
Sample code should not fail. It should work as it does on production.

**Comment by Felienne** [comment]
Hmmmm so weird, the tests should have caught this! I will investigate.

**Comment by Felienne** [comment]
Ha @TiBiBa is the culprit here :D 

The code in fact parses, but something goes wrong in the achievement verifier. I think I can fix this up though.
