### ISSUE TITLE
Output f-strings in level 6: 

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1615]
See: https://github.com/Felienne/hedy/blob/a950da6cb798b5476ee337aa3ce89b2bd1bef586/hedy.py#L1277

**Comment by jpelay** [comment]
I think this issue is solved! We are already generating f-strings now:

https://github.com/Felienne/hedy/blob/665c0becce567839cd5792cedd104bcf9cfa1cd6/hedy.py#L1795

**Comment by Felienne** [comment]
Yes, indeed, thanks for checking @jpelay!
