### ISSUE TITLE
Suggestion for misspelling commands prefers echo above ask command level-1

### ISSUE THREAD

**Issue by MarinusVanDijk** [Felienne/hedy#162]
Nice error message when typing askquestion without space:

![image](https://user-images.githubusercontent.com/37830964/108330595-0ec62380-71ce-11eb-9899-7f6b224ec9fa.png)

But then when typing askechoquestion without space:

![image](https://user-images.githubusercontent.com/37830964/108330774-4df47480-71ce-11eb-8934-7a3cff30a331.png)

Error message suggestion preference is the command echo.

I expect a suggestion for the ask command, because the command line starts with ask command?

And perhaps also give a suggestion for the echo command?

**Comment by Felienne** [comment]
We now give suggestions by a very simple string distance algorithm, see https://github.com/Felienne/hedy/blob/master/hedy.py lines 9-32. 

For now it is fine I think, the goal is to be better than "command not found" 

But if you are interested to improve it, as the comment also says "could be more sophisticated MACHINE LEARNING!" :)

Feel free to improve!

**Comment by MarinusVanDijk** [comment]
Here is the improvement:

# 
#  closest_command() searches for known commands in an invalid command.
#
#  It will return the known command which is closest positioned at the beginning.
#  It will return '' if the invalid command does not contain any known command. 
#

def closest_command(invalid_command, known_commands):
    min_position = len(invalid_command)
    min_command = ''
    for known_command in known_commands:
        position = invalid_command.find(known_command)
        if position != -1 and position < min_position:
            min_position = position
            min_command = known_command
    return min_command

Just replace the older one.

Do I have access to the source in terms of pushing commits? Making branches and push requests?

**Comment by MarinusVanDijk** [comment]
Here is my improvement (I do not have access to make branches).

![image](https://user-images.githubusercontent.com/37830964/108557254-9b6d0080-72f8-11eb-9279-3fe908634e14.png)
