### ISSUE TITLE
[CLEANUP] Multiple js console errors on non-exist calls / files

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1638]
**Describe the bug**
Currently visiting any page on the Hedy website results in multiple javascript console errors with different causes. They don't have any influence on the user experience, but as they describe some incorrect function call, non-existing file or any other undesirable behavior it would be nice to fix them. See the screenshot below for clarification:

![Schermafbeelding 2022-01-06 om 17 25 41](https://user-images.githubusercontent.com/38155424/148424770-e6f1c588-9dd4-4957-8db8-2be3e478a43f.png)

**Expected behavior**
When visiting any page no Javascript console errors occur (unless due to user behavior).

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
- What browser you were using (Chrome, Edge, Safari)

**Comment by Felienne** [comment]
Closed by #1637
