### ISSUE TITLE
Difficult errors after printask command in level-2

### ISSUE THREAD

**Issue by MarinusVanDijk** [Felienne/hedy#164]
Difficult error appears after printask command not typing a space behind.

I expected something like: Do you mean print? or ask?

![image](https://user-images.githubusercontent.com/37830964/108475815-827d3480-7291-11eb-9e69-4c7609b68422.png)

After entering a space:

![image](https://user-images.githubusercontent.com/37830964/108476276-21a22c00-7292-11eb-9db6-2f7abc95471a.png)

**Comment by Felienne** [comment]
We are aware of issues with leaky error messages, a student is working in a fix for this.
