### ISSUE TITLE
[BUG] wrong "go back to main page" redirect at quiz end  

### ISSUE THREAD

**Issue by ogoletti** [Felienne/hedy#1655]
**Describe the bug**
At the end of a quiz, the "go back to main page" button redirects inside the iframe and creates a nested page view.
When the quiz is empty (in the French version) the user directly lands on this page.

URL: https://www.hedycode.com/hedy#end

**Add a screenshot (optional)**
![Screenshot 2022-01-11 at 09 21 44](https://user-images.githubusercontent.com/22364279/148906542-78c9f3ea-9c51-4da6-b9bf-a9e4e541089f.png)
![Screenshot 2022-01-11 at 09 21 49](https://user-images.githubusercontent.com/22364279/148906557-3fc3e4b1-da53-4f6a-976e-a52b1626e78d.png)

**Expected behavior**
The main page should be reloaded instead of just the quiz subpage.

**Comment by TiBiBa** [comment]
Hi @ogoletti! I just wrote a fix, can you verify that it's working on the linked branch?

**Comment by ogoletti** [comment]
FYI I don't have a local Hedy deploy to test your fix ;) 
Do you have a test env with the fix deployed ?
