### ISSUE TITLE
Difficult error after replacing ask for print level-2

### ISSUE THREAD

**Issue by MarinusVanDijk** [Felienne/hedy#166]
This works fine!

![image](https://user-images.githubusercontent.com/37830964/108479775-6cbe3e00-7296-11eb-94fd-f8fbc3a56c9e.png)

But after replacing ask for print command in line 2:

![image](https://user-images.githubusercontent.com/37830964/108480132-da6a6a00-7296-11eb-8ef6-b1951748433e.png)

1. I expect an error as: do you mean ask instead of print?
2. I do not see the code anymore because the error message is too big.

**Comment by Felienne** [comment]
Similar to https://github.com/Felienne/hedy/issues/164
