### ISSUE TITLE
[CLEAN-UP][UI idea] Improve UI of 403, 404 and 500 pages

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1660]
**Idea incl level**
The 404 page can use an UI upgrade to better align with the rest of our website as well as being more responsive to the message given. For example, doe we always want to return the user to the main page? Maybe we want to return the user to the previous page in some cases? We also currently use three different templates for the 403, 404 and 500 error pages. However: these are identical! The dependencies on the variables can be easily parsed on the back-end and we should merge them into one template.

**Comment by Felienne** [comment]
I was thinking about the quiz issue and maybe we want to add a link to the translation UI for errors related to missing translations (see also #1605)

**Comment by TiBiBa** [comment]
> I was thinking about the quiz issue and maybe we want to add a link to the translation UI for errors related to missing translations (see also #1605)

That sounds great! I think the only location where we throw a 404 due to non-translated content is within the quiz. I think we should align this with the adventures in one go how to handle these situations (exactly as discussed in #1605).
