### ISSUE TITLE
[BUG] Sleep gives error that the code takes too long to run

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#1671]
**Describe the bug**
If you use sleep for more than 2 seconds it says the program takes too long to run. It happens when using sleep 3 or two times sleep 2 etc. 

**Paste the Hedy code & level**
![image](https://user-images.githubusercontent.com/80678586/149292431-83e3e774-e66f-4693-a50e-518863d94fb1.png)

**Comment by TiBiBa** [comment]
I know the cause of this! We have a check on the front-end to prevent programs that are too long from running indefinitely (and possibly crashing the browser). If I remember correctly this value I set to 3 seconds for textual programming and 20 seconds when using the turtle. Will take a look If we can implement it so to skip this check when using `sleep`.

**Comment by MarleenGilsing** [comment]
@TiBiBa You also get a new compliment each time after the sleep command is executed, like you've made multiple codes. Not that that's bad, but it is kinda strange.
