### ISSUE TITLE
[UI idea] Better error message when using two words in a variable level 2-11

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#1677]
For example:
![image](https://user-images.githubusercontent.com/80678586/149344988-0c09f86c-d186-4fc6-8201-b062dc5a5b2b.png)

We could use a better error message for these situations.

**Comment by boryanagoncharenko** [comment]
This issue seems to be resolved now. Tested levels 2-11 and they all seem to happily work without errors.
