### ISSUE TITLE
Exception missing in stats?

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1680]
I found a program that does give an error (A parse error) but that does not have an exception in the logs:

![image](https://user-images.githubusercontent.com/1003685/149386521-867fd2f6-14d7-4ed6-91a7-ccece48b50a3.png)

Not sure if this is a fluke or that we do not always log exceptions properly?

**Comment by boryanagoncharenko** [comment]
This is not a bug, but a missing feature. The log was created with a version of Hedy that did not log exceptions yet (commit 2ed462). So in this case the "version" field in the logs proved to be useful.
