### ISSUE TITLE
[BUG] turn [int] keyword works in level 1 where it shouldn't

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1684]
**Describe the bug**
In level 1 users should only be able to use either `turn left` or `turn right`. However, `turn [int]` as taught level 2 and onwards also works in level 1. See the screenshot below for clarification:

![Schermafbeelding 2022-01-14 om 12 08 34](https://user-images.githubusercontent.com/38155424/149506023-d51c6ed5-7772-453c-a60f-e771d3de85ea.png)

**Paste the Hedy code & level**
Hedy level 1

```
forward 25
turn 40
forward 25
turn 40
forward 25
turn 40
forward 25
turn 40
```

**Expected behavior**
`turn [int]` results in an `wrong level` error when used in level 1

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
- What browser you were using (Chrome, Edge, Safari)

**Comment by Felienne** [comment]
Yeah I was a bit too lazy to implement two rules :) Will fix that in an upcoming turtle update
