### ISSUE TITLE
[CONTENT] remove language pref header

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1688]
I think we can diable the header? Guess everyone has seen it now? (in theory we could track who has seen it and only show it to people who have not seen it or (easier) show it to people who have not set a preferred lang?)

![image](https://user-images.githubusercontent.com/1003685/149526513-38116dc1-3191-4069-9970-57763d01c938.png)

**Comment by TiBiBa** [comment]
It is already only shown to logged in users without a set preferred language!

**Comment by Felienne** [comment]
Haha guess who did not set a preferred language :D
