### ISSUE TITLE
[BUG] Incomplete inputs are not handled

### ISSUE THREAD

**Issue by racertop** [Felienne/hedy#1695]
**Describe the bug**
In level 18, incomplete inputs are not detected and are instead treated as assignments (it also yields an error but not the correct one). 
 Also, on a related bug, a program that contains input without text inside yields a parsing error:

**Paste the Hedy code & level**
Level 18
```
x is input
```
```
x is input()
```

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/45865185/149646996-dde30ba7-a59f-48cd-b42e-e26e9a1abe59.png)

![image](https://user-images.githubusercontent.com/45865185/149647061-b485214e-3633-41f3-85ff-f2b801dd0c5d.png)

**Expected behavior**
It should raise a `IncompleteCommandException`

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
- What browser you were using (Chrome, Edge, Safari)

**Comment by Felienne** [comment]
> **Add a screenshot (optional)** ![image](https://user-images.githubusercontent.com/45865185/149646996-dde30ba7-a59f-48cd-b42e-e26e9a1abe59.png)

Good catch @racertop! First I was like... but this is an assignment! But I have to agree with you, it is a lot more likely that the kid here wanted to do an input and forgot the quotes and text, so the incomplete exception is more appropriate.
