### ISSUE TITLE
vertaal foutjes in level 12, restaurant

### ISSUE THREAD

**Issue by harmvdb** [Felienne/hedy#1697]
In level 12 zitten vertaal foutjes: (food, ipv eten; dinks ipv dinken)
prijs = 0
eten = ask 'Wat wil je eten?'
drinken = ask 'Wat wil je drinken?'
if eten is 'hamburger'
    prijs = prijs + 6.50
if **food** is 'pizza'
    prijs = prijs + 5.75
if **drinks** is 'water'
    prijs = prijs + 1.20
if **drink** is 'frisdrank'
    prijs = prijs + 2.35
print 'Dat wordt dan ' prijs ' euro, alsjeblieft'

**Comment by Felienne** [comment]
Thanks voor het melden @harmvdb! 

Als je wilt, kun je de verbetering zelf maken! Via deze link kan je de edits maken en dan onder aan de pagina een pull request maken: https://github.com/Felienne/hedy/edit/main/coursedata/adventures/nl.yaml#L1414

Als dat niet lukt, geen probleem, dan pakt @MarleenGilsing het van de week wel op!

**Comment by MarleenGilsing** [comment]
Opgelost!
