### ISSUE TITLE
[BUG] Repair modal not completely visible 

### ISSUE THREAD

**Issue by fRedelaar** [Felienne/hedy#1718]
**Describe the bug**
When making a mistake in the code, the Hedy Bulb pops up. Whenever the bulb is clicked, the repair modal appears. The modal however seems to be positioned too high in the browser. This causes the modal to not be fully readable. 

**Add a screenshot**

https://user-images.githubusercontent.com/33595265/149893890-59056b90-4035-4b32-b18d-3e47e2791262.mov

**Expected behavior**
Lowering the modals viewing height.

https://user-images.githubusercontent.com/33595265/149893917-d58a0287-ad2d-4508-a4c1-990bd269f6a5.mov

**Comment by TiBiBa** [comment]
One option might be to scroll automatically to the top when showing the modal using `window.scrollTo(0, 0);`. However, that is not a really user friendly solution. What might be nicer is the less intrusive alert modal solution, for which we use `style="top: 10%; left: 50%; transform: translate(-50%, -50%);`. Changing this to `top: 50%;` should always display the modal in the middle of the user view!

**Comment by Felienne** [comment]
Nice to see you are doing good work even before the thesis starts @fRedelaar!
