### ISSUE TITLE
Unexpected error in level 6 [BUG]

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#1720]
**Describe the bug**
When I run the code below multiple times in level 6 I get different results.

```
eten is hamburger
prijs = 0
if eten is hamburger prijs = 12
print prijs

```

Sometimes I get no output, a green popup with "bravo" and a yellow pop up with this text:
```
Let op!

Deze code werkt wel, maar print niks. Voeg een print commando toe aan je code of gebruik de schildpad om output te krijgen.
```
Sometimes I get the green popup and the output `12` as expected.

![image](https://user-images.githubusercontent.com/10562903/149969495-299e9bda-a5a6-4572-8fb6-c8138dacaa4c.png)

**Comment by Felienne** [comment]
This has the same root cause as #1721 so I can fix them together!
