### ISSUE TITLE
No or incorrect output [BUG]

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#1724]
Sometimes when my students run a program they don't get any or incorrect output. It is hard to pinpoint when exactly this happens. I think it has to do with pressing "Run Code" while a program is still running. Student do this a lot and I see this issue multiple times per lesson. Running the program keeps on giving incorrect results once this has happened. My workaround is to save the program, refresh the webpage in the browser and try again. This usually works.

One example of this issue arises when I run the code below and press the "Run Code" button multiple times during execution. At one point it will create two figures and raise an error (see screenshot). However the issue is certainly not limited to drawings, it also happens when using the `repeat` and `ask` commands.

```
hoek = 90
repeat 10 times
    turn hoek
    forward 50
forward 100
```

![image](https://user-images.githubusercontent.com/10562903/150156604-ddb95243-c88f-4ff3-a791-db2dda773c86.png)

**Comment by Felienne** [comment]
Thanks for reporting this @OnnoEbbens! I also have the feeling I have this issue sometimes (and I refresh to solve it)

@TiBiBa Can you try to see if you can reproduce and to understand this?

**Comment by TiBiBa** [comment]
> Thanks for reporting this @OnnoEbbens! I also have the feeling I have this issue sometimes (and I refresh to solve it)
> 
> @TiBiBa Can you try to see if you can reproduce and to understand this?

Yes, will take a look! It does seem like a weird bug as pressing the run button should terminate all running processes.

**Comment by Felienne** [comment]
Yeah it is really hard to reproduce precisely, which is why I did not yet create an issue. I have the feeling it happens after you had an error, on run right after that (with our without the same error)

**Comment by TiBiBa** [comment]
> Yeah it is really hard to reproduce precisely, which is why I did not yet create an issue. I have the feeling it happens after you had an error, on run right after that (with our without the same error)

Yes, I'm trying to reproduce the error but no luck so far. It might have something to-do with the front-end timeout we have. Maybe it does not reset correctly in the case of a faulty run, will dive into the code to try and find the cause.

**Comment by TiBiBa** [comment]
It might have something to-do with switching browser tabs? @OnnoEbbens The timer continues to run, but for some reason the turtle pauzes when you are on another browser tab. This way I was able to easily reproduce the error:


![Schermafbeelding 2022-01-19 om 17 29 57](https://user-images.githubusercontent.com/38155424/150173381-f095b069-c725-4f97-978c-4fbbecc743c0.png)

**Comment by TiBiBa** [comment]
I found a way to always re-produce this error. Run a programming containing `repeat` and presses run again while it is still executing. It might have something to-do with use clearing the `output` and `turtlecanvas` but not stopping the actual executing of the program. This might be a quite complex bug to solve. Code to re-produce:

`repeat 50 times 'Hedy is leuk!'`

![Schermafbeelding 2022-01-20 om 08 33 28](https://user-images.githubusercontent.com/38155424/150293662-e36639fd-6e7b-41e2-b643-d279b799f584.png)

**Comment by OnnoEbbens** [comment]
Nice that you found a way to reproduce it @TiBiBa. This example seems to reproduce exactly what I ran into.

I don't think it has to do with switching browser tabs. I also had this issue when I just have one tab open.

**Comment by TiBiBa** [comment]
I think I've found a bit more of information. It seems that code is always run async, independent of how many times we press the run button. This is, of course, undesirable. We would like to kill all running processes each time we press the run button. But, now the weird part: By running multiple processes at the same time some don't seem to correctly return a promise. Our global counter for running programs only decreases 1 after receiving this promise (and knowing that the program is done). We only output anything if `window.State.programsInExecution  =< 1`. Resulting in the following situation:

- We have a `window.State.programsInExecution` value that is stuck at higher than 1
- Some programs don't return a promise -> result in a timeout
- We don't have any output as implemented based on `window.State.programsInExecution`

The solution would be too `hardInterrupt` all running Skulpt processes each time we call the `RunPythonProgram` function. But, that seems harder that it sounds. I found some similar issues on the web but am still figuring out how we can implement this ourselves:

https://github.com/skulpt/skulpt/pull/470

**Comment by Felienne** [comment]
Good detective work @TiBiBa!

I was under the impression that while the code is running, the run button should be disabled. But I guess that is only the case when we are waiting for an `ask` input? Would it be possible to disable the button while running? Maybe that is easier than your proposed solution (which indeed seems complex and brittle)

**Comment by TiBiBa** [comment]
> Good detective work @TiBiBa!
> 
> I was under the impression that while the code is running, the run button should be disabled. But I guess that is only the case when we are waiting for an `ask` input? Would it be possible to disable the button while running? Maybe that is easier than your proposed solution (which indeed seems complex and brittle)

I think I almost have a working solution with killing the process when running a new program! If it doesn't work somewhere this morning I will just disable the run button until the promise is returned.
