### ISSUE TITLE
[BUG] Remove doesn't remove the correctly given answers

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#1726]
**Describe the bug**
I want to use the remove command in educational games. If the player gives the right answer, this question is removed from the list, so the player only gets questions that they haven't answered yet or have answered wrong. 

In the code below I made a game to practise the timetables. number1 should be removed after the right answer was given. But as you can see in the screenshot, it is not. 

**Paste the Hedy code & level**
```
score = 0
number2 = ask 'Which table of multiplication do you want to practice?'
repeat 3 times
    numbers = 1, 2, 3, 4
    number1 = numbers at random
    correct_answer = number1 * number2
    print 'What is ' number1 ' times ' number2 '?'
    answer = ask 'Type your answer here...'
    print 'Your answer is ' answer
    if answer is correct_answer
        score = score + 1
        remove number1 from numbers
print 'Great job! Your score is... ' score ' out of 10!'
```

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/80678586/150303889-5146f5c6-6c63-46ef-b2bd-c5daa78ceee0.png)

**Comment by lexcov** [comment]
Hi @MarleenGilsing and @Felienne! I'm new to open-source contributing and I was wondering if I could work on this issue? I noticed it's not on the core team board. I've already cloned the repo and been able to run it locally. Let me know if you have any pointers!

**Comment by Felienne** [comment]
Absolutely! With all the grammar changes maybe it has been fixed but then
it's an easy issue to close 😅

**Comment by Felienne** [comment]
Ah "good" news, the bug is still there at level 9 :) 

Good luck squashing it, if you need help, let me know!

**Comment by Felienne** [comment]
btw, we also have a Slack we use to chat about Hedy, let me know if you want to be added (feel free to reach out to hedy@felienne.com)

**Comment by Robernc** [comment]
Upon inspection of this code, it appears there is a bug within the provided Hedy code. The list assignment was done within the repeat loop (assigning the list of 1,2,3,4 at the beginning of each loop) instead of outside the loop, thus the list was reset at the beginning of each loop. 
One possible version of Hedy code that has the desired behavior could be: 
```
score = 0
numbers = 1, 2, 3, 4
number2 = ask 'Which table of multiplication do you want to practice?'
repeat 3 times
    number1 = numbers at random
    correct_answer = number1 * number2
    print 'What is ' number1 ' times ' number2 '?'
    answer = ask 'Type your answer here...'
    print 'Your answer is ' answer
    if answer is correct_answer
        score = score + 1
        remove number1 from numbers
print 'Great job! Your score is... ' score ' out of 10!'
```


I have also included a picture of the output (I printed out the items remaining in the list to show that items are correctly removed)
![image](https://user-images.githubusercontent.com/59849852/160526496-952e9b53-5f2e-4a57-9af2-9090ae28b4f8.png)

Please let me know If the bug is not fixed :)

**Comment by Felienne** [comment]
Haha so this was @MarleenGilsing's own errror! Thanks for diving into it, this can be closed indeed!

**Comment by MarleenGilsing** [comment]
😅 Whoops! Thanks @Robernc
