### ISSUE TITLE
[UI idea] Notify kids of class invite in Hedy site

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1735]
**Idea**
When teachers make a link, they have to somehow get the link to the kids. We envisioned teachers would do that via an LMS (on highschool) or email, but it turns out some elementary schools either do not have email addresses that kids use (they exist but kids don't log in) or block emails that contain links or block emails form third parties.

So, it would be better if kids get a notification that they are invited that they can accept from within Hedy, without the need for explicitly sharing the link.

**Comment by TiBiBa** [comment]
I think a nice solution would be to create some "invitations mailbox" for each user. The teacher can invite children on their username, after which they receive the link in their "mailbox" which they can accept. This implementation also offers possibilities later on for sending adventures to students.  We can also simply create an additional banner in the profile page with:

`Hi! Just have been invited for class {{name}}, would you like to join? Click here!`

I'm not sure what would be the best solution for now. In both cases we need some additional db to keep track of the invitations and add some (invited/accepted) overview to the class overview page of the teacher. I think I'll be able to implement one of both options before Monday!

**Comment by TiBiBa** [comment]
Few things we have to keep in mind while implementing this:

- Return an error if the user doesn't exist or is already in your class
- Remove pending invitations when the class is removed
- Where do we show the invitation? Profile page? Overlay banner?
