### ISSUE TITLE
[BUG] Indentation in quiz blocks does not show correctly

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1738]
f.e. C and D look the same ![image](https://user-images.githubusercontent.com/1003685/150512382-078afdb9-b055-440e-a5f3-b5c514183c49.png)

But the code differs:

https://github.com/Felienne/hedy/blob/4f899077956002c2b126dc17d4cf264309cebab1/coursedata/quizzes/nl.yaml#L1281

**Comment by LterHaar** [comment]
I've changed the code so that the indentation is now shown correctly (the tag <pre> is added). Also the placing in the option blocks is changed.
![UI revision 2 d](https://user-images.githubusercontent.com/86956321/150763957-c3a410c7-9a6e-4517-9aa0-9b94d30ffc09.PNG)

**Comment by Felienne** [comment]
Maybe you can pick this one up too @TiBiBa? I am not sure what the status is now.

**Comment by TiBiBa** [comment]
Wil take a look!

**Comment by TiBiBa** [comment]
This seems to be fixed!
