### ISSUE TITLE
when variable name exist in a previous line, a not understandable error is given

### ISSUE THREAD

**Issue by ericverschoor** [Felienne/hedy#1754]
Given the following program at level 2:
Print Ik ben moe, jij ook?
moe is ask Ben jij ook moe?

When the variable name (moe) is also mentioned in line above., the error is not clear what is wrong: “name ‘moe’ is not defined”
And, (for me a minor issue) this message is in english instead of in dutch

Then I expect an error similar like:
Error in line 1: The name ‘moe’ is used as a variable in line 2, therefore it can not be used before line 2.

And to clarify the error message, the variable name ‘moe’ and ‘moe’ in line1 should be highlighted

![115852BC-AE98-45C9-91FB-729288F4CAA1](https://user-images.githubusercontent.com/45706519/150598946-0f415a4c-6322-4675-bf35-3940f168ae43.jpeg)

**Comment by Felienne** [comment]
Thanks for noticing @ericverschoor, this issue is known to us and already an open issue: https://github.com/Felienne/hedy/issues/1503 (I understand it sounds different but it is the same core issue)

This is not easy to fix but we are aware it should be improved, so I am closing this one.
