### ISSUE TITLE
[Language idea] print without any text will output a blank line

### ISSUE THREAD

**Issue by ericverschoor** [Felienne/hedy#1755]
I think from level 1, a print command without text can output a blank line.
Because print can be considered as a valid command, even without text after it,

Given:
Print hello world!
Print
Print hello mars!

Should output
hello world!

hello mars!

**Comment by Felienne** [comment]
I understand the idea, but at the earlier levels we want to stress the idea that some commands need arguments. Level 1 is quite limited so it is a good place to get used to the idea of mandatory form, which can differ per command (like echo and turn do not need arguments but may have them)

I think in this case the error message is really clear, and if you really want a break you can use something like `print ------`
