### ISSUE TITLE
[CONTENT] Exam level 1, question 2

### ISSUE THREAD

**Issue by ericverschoor** [Felienne/hedy#1756]
I write this issue in dutch because i think it is dutch related

Level 1, vraag 2 is: Met welk commando kun je tekst laten verschijnen?
Het verwachte antwoord is ‘Print’

Maar, mijn zoon met een Taal-ontwikkeling-stoornis neemt teksten erg letterlijk op, maar dit geld denk ik ook voor meer kinderen.
Ik volgens hem zijn de opties: print, echo en ask allemaal goed. En hij heeft natuurlijk gelijk, want bij alle 3 commando’s tovert hij tekst op het scherm.
Ik denk dat deze vraag is scherper gesteld kan worden. “Met welk command kun je tekst in het zwarte scherm verschijnen” (dan zijn print en echo nog steeds valide 🧐) ik weet zo 1-2-3 geen betere

Ps… hele leuke podcast bij de Technoloog, en mijn zoon (10jr) is erg fan van hedy.

**Comment by Felienne** [comment]
Goed punt! Misschien kunnen we ervan maken:

"Welk commando laat *alleen* tekst verschijnen?"

Want `ask` en `echo` doen natuurlijk allebei nog iets anders ernaast. Is dat duidelijker?

**Comment by Felienne** [comment]
En wat superleuk dat je zoon fan is!! Als je mij je adres wilt sturen (hedy@felienne.com) dan stuur ik jullie met liefde wat Hedy goodies op!!

**Comment by ericverschoor** [comment]
> Goed punt! Misschien kunnen we ervan maken:
> 
> "Welk commando laat _alleen_ tekst verschijnen?"
> 
> Want `ask` en `echo` doen natuurlijk allebei nog iets anders ernaast. Is dat duidelijker?

Klinkt goed!

**Comment by MarleenGilsing** [comment]
Solved with #1932
