### ISSUE TITLE
[CONTENT] use smilies in the examples

### ISSUE THREAD

**Issue by ericverschoor** [Felienne/hedy#1757]
I use a lot of smilies in the examples when I write some examples for my som
Using smilies can perhaps make the static text more lively

![8CFD44F6-FC2B-43B9-BCF1-2FBE65B8794A](https://user-images.githubusercontent.com/45706519/150604631-e7dae167-a89f-4944-9084-53b5b882317f.jpeg)

**Comment by Felienne** [comment]
This is a lovely idea!! Many of our early content stems from a time that we did not support smileys, but now we can totally do this.

@MarleenGilsing can you add a few smileys in the texts? Maybe also as list elements, like this in level 4:

```
print He hears a sound
animals is 🦉, 🦔, 🐢
animal is ask What do you think it is?
add animal to animals
print it was a animals at random
```

**Comment by MarleenGilsing** [comment]
Great idea! I'll get to it!
