### ISSUE TITLE
[UI idea] the output should auto scroll down 

### ISSUE THREAD

**Issue by ericverschoor** [Felienne/hedy#1758]
I suggest the following:

When writing new lines the output window should autoscroll to the last line
See the below example, the last line ‘aaaa’ is not visible

![22FD9A06-AC4F-4183-858E-8FEA1BE8C030](https://user-images.githubusercontent.com/45706519/150605817-60fc16b1-9204-4b04-aa1b-2ccd9642addd.jpeg)

**Comment by Felienne** [comment]
I understand the suggestion but I think there are also many cases in which autoscrolling will be annoying/confusing, so we will leave this as it is for now. 

You can hover over the test field and scroll down manually.
