### ISSUE TITLE
Simplification and relaxing of grammar wrt spaces

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1772]
In #1771 we surround _COMMA with spaces in the level 1 grammar, simplifying further levels. This change can be made for other characters too, such as `=` and `()` and `[]`. 

There might be cases where we don't want to encourage using spaces (before an opening brace, for example) but I think we should allow it everywhere Python allows it too.

**Comment by Felienne** [comment]
@jpelay This has your name on it, doesn't it? :D

**Comment by jpelay** [comment]
Hahaha it does!! I'll work on it as soon as I can, either when I fix my computer or can buy another one :p
