### ISSUE TITLE
[UI idea] is ask / at random combination can be difficult to understand

### ISSUE THREAD

**Issue by ericverschoor** [Felienne/hedy#1776]
Given the program

    eten is ask wat wil je eten?
    vanavond is eten at random
    print wij eten vanavond 

This is of course a strange program to run. It first asks for input (is ask) and then choose a random value (at random) from the input value.
A random char is chosen from the array of chars.
This is, i think, hard to understand for beginners.

Perhaps a warning can be shown that when variable that is set via ‘is ask’, is used as input for ‘at random’

**Comment by Felienne** [comment]
Great catch @ericverschoor! This should have been caught by the type system! Tagging @boryanagoncharenko so she can have a peek at what went wrong here.

**Comment by Felienne** [comment]
Hi @ericverschoor, this is fixed now, thanks again for pointing it out (goodies are on the way to you!)
