### ISSUE TITLE
[BUG] drawing turtle using at random gives unexpected response

### ISSUE THREAD

**Issue by ericverschoor** [Felienne/hedy#1777]
Given the program should print the char E but in this level we chose to let the program descide the length of the lines.
This program however is drawing something strange, and I do not know why. 
I mention it here just for your information…. Perhaps it is of use for you.

    print We gaan de E tekenen
    a is ask doe je mee?
    lengte is 50, 75, 100
    
    boven is lengte at random
    midden is lengte at random
    onder is lengte at random
    hoogte is onder
    
    turn 180
    forward boven
    turn 270
    forward hoogte
    turn 270
    forward midden
    turn 180
    forward midden
    turn 270
    forward hoogte
    turn 270
    forward onder
    print  🎉🎉🎉🎉🎉🎉🎉

![44808548-22FF-48F7-AF96-F72E762B0937](https://user-images.githubusercontent.com/45706519/150853901-3fe400cd-1a3d-4082-946c-e4e4ee62d3dc.jpeg)

**Comment by Felienne** [comment]
Curious!! Will dive into this!

**Comment by ThomasKluiters** [comment]
I'll steal this one off you @Felienne ! If that's okay :)

**Comment by Felienne** [comment]
For sure!!

**Comment by ericverschoor** [comment]
🎉🎉 wouter is er blij mee 🎉🎉
