### ISSUE TITLE
[CONTENT] Failed hint in warning - level 1 - second task

### ISSUE THREAD

**Issue by kakulukia** [Felienne/hedy#1781]
**Describe the issue**
Language: tested for de, nl and en
Level 1

I just tried this out, but the warning after executing the print task and entering the color leaves me with big question marks. Whats that turtle trying to tell me? How does it help with the missing print?

**Add a screenshot (optional)**
<img width="1287" alt="Bildschirmfoto_2022-01-25_um_11_21_34" src="https://user-images.githubusercontent.com/96352/150960785-7daaef47-4ea8-4e33-961c-01ae8a824049.png">

**Expected text**
Please remove the turtle, or explain it. I seriously dont have a clue, whats thats supposed to tell me!

**Comment by Felienne** [comment]
Hi @kakulukia! 

You are right, we should have added turn and forward to the list of commands in the upper bar! We will fix that!

For now, if you click the final code on the side bar "Turn the drawing turtle with turn" and run the code, you will see that the turtle draws:

![image](https://user-images.githubusercontent.com/1003685/150962174-467ba6f4-6df4-4328-90f5-bbb756fe10b4.png)

**Comment by kakulukia** [comment]
Hi @Felienne ,

1st - Thanks for that awesome video (the introduction talk)!

2nd - There is no drawing turtle, just an arrow .. and the connection between the drawing mechanism and the missing print is still missing - even with the additional commands added to the list.

3rd - Exploring the other tabs i get the idea of a turtle following the line (i drawed?), but IMHO this totally contradicts the base philosophy of explaining new concepts first and then using them. Especially mentioning the turtle in a warning message! This should only be done when i definitely have read about it or even better saw how the turtle was brought to live.

I have explored a little more .. but found no turtle actually doing something - bummer! ;/

Reading about a turtle in a warning after first contact with Hedy, created (at least for me) the thought of: "Its only the second of the very first two super simple tasks. WTF? How could i have missed that turtle thing? And how on earth does a turtle help me to output something that went into that input box?"

The waning IMHO only makes sense after getting in contact with variables.

**Comment by kakulukia** [comment]
I just checked the page. The mysterious turtle is still there. Will that be fixed with the next release or is this ticket just closed, because Hedys base concepts don't apply to the web tutorial?

**Comment by Felienne** [comment]
Closed because we don't see a clear path forward, we need a bit more
thinking about the usefulness of the empty message anyway. It will change
in a way but keeping this (very overwhelming) issue open is not useful at
this point in time. If you want to send a PR with a concrete fix, of course
that is ok.
