### ISSUE TITLE
[BUG] Incorrect "Last Login" date in the class overview

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#1790]
In the class overview I see (as a teacher) a column with a timestamp of the latest login. Fairly often this timestamp is older (sometimes weeks older) than the latest program that a student has made. Maybe this timestamp is the last time a student actually entered their credentials to log-in. In that case it would be nice to have a column with the latest time a student has been active.

![image](https://user-images.githubusercontent.com/10562903/150990673-031bcdbd-bd3f-4c97-9073-f8380a90f279.png)

**Comment by TiBiBa** [comment]
I think this is quite complex! Currently we work with tokens. Each time a user logs in a new token is stored in the db, we base this timestamp on the last found token for a user. Storing a lot more tokens would result in an increase db load. To prevent increased db load we have think of a more efficient way to keep track of the users their activity:

- Store a timestamp on their profile, update on each db interaction?
   -  Such as saving a program or getting an achievement
   -  Update each x minute the user is actually logged in

I'm not sure what would be the most suitable way as our current structure is not at all implemented to support to keep track on such a value. In the long run the best idea might be to re-write our current structure with tokens and implement something more efficient. One thing just came to mind:

When a user requests the page we verify if there is already a cookie -> they are already logged in. Maybe we can update a new token to the db iff this cookie age is older than let's say 5 minutes. This way as long as the user has interaction with the website this timestamp is updated each 5 minutes. What do you think @Felienne ?

**Comment by TiBiBa** [comment]
I just made a fix! Currently we only record a login at the moment a user logs in. Due to the usage of cookies this moment can be a long time ago. With the current fix we record a new login each time the cookie is retrieved. This is basically always the case if the website is loaded from an empty browser. Is this a suitable solution? @OnnoEbbens

**Comment by OnnoEbbens** [comment]
Perfect solution, Thanks @TiBiBa
