### ISSUE TITLE
[BUG] Syntax highlighting in level 4, 6 and 8

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#1793]
Some syntax highlighting issues 
- from level 4 the syntax highlighting for `forward` and `turn` is off
- From level 6 you can use `=` instead of `is`. When `=` is used the syntax highlighting seems to stop after the `=` sign.
- in level 8 and higher the syntax highlighting does not work for `repeat . times`.

See the tabs for each level for the examples

**Comment by Felienne** [comment]
Yes, we are aware of this, in fact @TiBiBa is working on a fix already (PR #1709) Maybe when you finish, you can double check these issues are also solved?
