### ISSUE TITLE
[BUG] Unexpected result when printing variable names in level 5

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#1795]
In some cases when I print a variable name between quotes in level 5 it is replaced by the variable value. I wouldn't expect this as the variable name is between quotes. This only happens when the variable name is the only name between quotes and not when there is other text within the quotes.

```
naam is 'Daan'
woord1 is zomerkamp
print 'naam' ' is naar het' 'woord1'
print 'naam is naar het woord1'
```
![image](https://user-images.githubusercontent.com/10562903/150997661-cd2c16ed-9f72-4f6d-b47f-1c063c63e358.png)

**Comment by Felienne** [comment]
Interesting!! That clearly should not be the case. I will dive into this, I am suspecting it is something small, like a wrong fallback to a lower level.

**Comment by Felienne** [comment]
Soon to be deployed on hedycode.com:

![image](https://user-images.githubusercontent.com/1003685/151025828-0290e371-0696-44a8-b049-ad9c8e1fceed.png)
