### ISSUE TITLE
[UI idea] Hide save-bar when user is not logged in

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1836]
**Idea incl level**
The interface is getting pretty crowded so it would be nice to reduce UI elements as much as possible. In this case I would like to suggest to hide the save-bar in the case a user is not logged in. When a user is logged in, we show the bar; but maybe a slightly less intrusive version. Will have to think a bit about this, but it should be improved!

**Comment by TiBiBa** [comment]
Not sure we still want this with the added "commands button" on the same bar. It still can use a design improvement, but I'm hesitate to completely remove it. What do you think? @Felienne

**Comment by Felienne** [comment]
> Not sure we still want this with the added "commands button" on the same bar. It still can use a design improvement, but I'm hesitate to completely remove it. What do you think? @Felienne

Yes we could move the 🤫  and then do this, but I understand your hesitance. Maybe we have already made enough room for now removing the sidebar?

**Comment by TiBiBa** [comment]
> > Not sure we still want this with the added "commands button" on the same bar. It still can use a design improvement, but I'm hesitate to completely remove it. What do you think? @Felienne
> 
> Yes we could move the 🤫 and then do this, but I understand your hesitance. Maybe we have already made enough room for now removing the sidebar?

I think we do! Will close this issue and we can always re-visit styling the coding page UI in the near future.
