### ISSUE TITLE
[BUG] Cannot remove student from class 

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#1854]
When I try to remove a student from a class, using the 'verwijder ..' button in the class overview, I do get the question if I am sure. If I press 'yes' nothing happens, the student is still in my class. I tried this with multiple students it never seems to work. Also when I try to remove myself from a class as a student nothing happens.

**Comment by TiBiBa** [comment]
Weird! Is this on alpha, beta or locally? I think this is an error introduced with the re-structuring of the class overview. Will take a look right away!

**Comment by TiBiBa** [comment]
> When I try to remove a student from a class, using the 'verwijder ..' button in the class overview, I do get the question if I am sure. If I press 'yes' nothing happens, the student is still in my class. I tried this with multiple students it never seems to work. Also when I try to remove myself from a class as a student nothing happens.

I'm unable to re-produce this error locally, on alpha or beta!

**Comment by OnnoEbbens** [comment]
It happens when I go to hedycode.com, I guess that means I am using beta. Maybe it happens because my class was created before all the changes to the class overview. If you want you can use my log-in and try it out.

**Comment by TiBiBa** [comment]
> It happens when I go to hedycode.com, I guess that means I am using beta. Maybe it happens because my class was created before all the changes to the class overview. If you want you can use my log-in and try it out.

Weird! I just tested it with an old class as well and it seems to work fine. Can you try in incognito or private mode of your browser? Might it has something to do with our updated javascript files.

**Comment by OnnoEbbens** [comment]
I tried in incognito and still didn't work. I've tried in firefox, chrome and edge.

**Comment by OnnoEbbens** [comment]
I think this is the error message you are looking for:

XHRDELETEhttps://hedycode.com/class/b42e460333074d17a7f09d65e6b5f013/student/onno
[HTTP/1.1 404 NOT FOUND 40ms]

Object { readyState: 4, getResponseHeader: getResponseHeader(e), getAllResponseHeaders: getAllResponseHeaders(), setRequestHeader: setRequestHeader(e, t), overrideMimeType: overrideMimeType(e), statusCode: statusCode(e), abort: abort(e), state: state(), always: always(), catch: catch(e)
, … }
​
abort: function abort(e)​
always: function always()​
catch: function catch(e)​
done: function add()​
fail: function add()​
getAllResponseHeaders: function getAllResponseHeaders()​
getResponseHeader: function getResponseHeader(e)​
overrideMimeType: function overrideMimeType(e)​
pipe: function pipe()​
progress: function add()​
promise: function promise(e)
​
readyState: 4
​
responseText: "No such class"
​
setRequestHeader: function setRequestHeader(e, t)​
state: function state()
​
status: 404
​
statusCode: function statusCode(e)
​
statusText: "NOT FOUND"
​
then: function then(t, n, r)​
<prototype>: Object { … }
teachers.js:186:20
    ou teachers.js:186
    jQuery 6
    ou teachers.js:173
    confirm modal.js:115
    jQuery 8

**Comment by TiBiBa** [comment]
> I think this is the error message you are looking for:
> 
> XHRDELETEhttps://hedycode.com/class/b42e460333074d17a7f09d65e6b5f013/student/onno [HTTP/1.1 404 NOT FOUND 40ms]
> 
> Object { readyState: 4, getResponseHeader: getResponseHeader(e), getAllResponseHeaders: getAllResponseHeaders(), setRequestHeader: setRequestHeader(e, t), overrideMimeType: overrideMimeType(e), statusCode: statusCode(e), abort: abort(e), state: state(), always: always(), catch: catch(e) , … } ​ abort: function abort(e)​ always: function always()​ catch: function catch(e)​ done: function add()​ fail: function add()​ getAllResponseHeaders: function getAllResponseHeaders()​ getResponseHeader: function getResponseHeader(e)​ overrideMimeType: function overrideMimeType(e)​ pipe: function pipe()​ progress: function add()​ promise: function promise(e) ​ readyState: 4 ​ responseText: "No such class" ​ setRequestHeader: function setRequestHeader(e, t)​ state: function state() ​ status: 404 ​ statusCode: function statusCode(e) ​ statusText: "NOT FOUND" ​ then: function then(t, n, r)​ : Object { … } teachers.js:186:20 ou teachers.js:186 jQuery 6 ou teachers.js:173 confirm modal.js:115 jQuery 8

Thanks! Will look into this.

**Comment by TiBiBa** [comment]
I found the issue! We current use the following statement to verify if a user is allowed to delete a student:

`if not Class or Class ['teacher'] != user ['username'] or student_id != user ['username']:`

But this is wrong! Because this way we are only allowed to remove ourselves if we are the teacher of this class. We should change this to:

`if not Class or (Class ['teacher'] != user ['username'] and student_id != user ['username']):`

This way the teacher can remove a student **and** the student can remove themselves. What is also wrong is that we don't return any useful error message. Will fix this as well!

**Comment by TiBiBa** [comment]
@OnnoEbbens I just made a PR with a fix, can you verify that it is working?

**Comment by Felienne** [comment]
> Thanks for the fix! I would like to verify but I haven't set up a local version. Also my knowledge of Hedy is to limited to understand what is really happening. So I think it is better if someone else can check this. Sorry

np, I can check this later this week, or maybe @ThomasKluiters has time?
