### ISSUE TITLE
[BUG] 'ask' as variable name translated where it shouldn't

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1856]
**Describe the bug**
With the implementation of the language-switcher (#1717), users are able to switch between different languages; automatically translating the keywords. However, for some reason the word 'ask' is translated as well even when it's not a keyword. See the example below:

![151783045-1d0b6522-2d65-4058-ab97-78903ff83f7a](https://user-images.githubusercontent.com/38155424/151794288-c3f397fe-e998-492b-983d-cf91b8e75fda.png)
![151783057-be7acdf8-1239-4faf-92c8-9720cff530fc](https://user-images.githubusercontent.com/38155424/151794301-aa86d4ae-b6b5-40c7-a3dc-15e87f059620.png)

**Expected behavior**
When 'ask' is used as a variable name or within a string it should not be translated by the language-switcher.

**Comment by Felienne** [comment]
Hmmmm I am not able to reproduce this with a test, can you try if it still happens in the UI @TiBiBa? Maybe it was a result of the inconsistent state the switcher got into?
