### ISSUE TITLE
Suppress or translate 'bad input'

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#186]
f.e. this code at level4:

```
naam is ask hoe heet jij?
ifnaam is Hedy print 'leuk' else print 'minder leuk!'
```

**Comment by Felienne** [comment]
Placing some thought for myself about this issue for later reference:

The reason this happens that is Hedy sometimes produces invalid Python. When the invalid code is ran, Skult produces an error, of which we output just "bad input". Sadly the more detailed info (f.e. SyntaxError or RunTimeError) is not (easily) available.

**Comment by Felienne** [comment]
Here's a discussion for you @fpereiro to think about with me... The issue is that in Level 3 and up, we do not require '' around strings, but some kids use it (probably because they know it form other places/parents think it is needed or they generalize from print where it is needed. 

What to do with this?? We can remove the ''? 

![image](https://user-images.githubusercontent.com/1003685/110349976-8f40ad00-8033-11eb-8390-83d2d28858f6.png)

Or escape so it ends up in the string?

![image](https://user-images.githubusercontent.com/1003685/110349715-412ba980-8033-11eb-85c3-abd30b4c2e20.png)

What do you think?

**Comment by fpereiro** [comment]
@Felienne interesting question!

I really like the second option, of consider quotes as non-special characters *until* they become part of the syntax. So, if you put quotes, we merely return them. It keeps things consistent: either the characters are non-special (non-syntactic) or they are. It also gives it an "arcade" feeling, of throwing something at Hedy and Hedy returning it back unchanged (unless the quote means something syntactically). And for those who know that quotes are used to, um, quote strings, it might surprise them too in a good way. If we can help along the realization that a character can stand for itself or as a syntactic entity, this would be amazing.

Implementation wise, it means we'd have to escape the quotes.

Do we require quotes at a certain level? (embarassing of me to ask at this stage!) If so, after that point, the quotes are mandatory and if you want to print quotes, you'll actually have to escape them!

**Comment by fpereiro** [comment]
Hi @Felienne ! Agreed on all points. And escaping definitely should be done later. I like the idea of putting a cliffhanger there for kids that want to figure out how to print quotes when quotes become syntactic. It seems like that could be a level of its own, and quite later too.

Good to know there's no photoshop involved... I wonder what would take more effort, if photoshop or directly changing the grammar!

**Comment by Felienne** [comment]
This change had already been merged into master (not sure when, oops) so this can be closed for now, although there might be other cases of bad input when invalid Python is generated.
