### ISSUE TITLE
[BUG] var check needed in level 18

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1889]
**Describe the bug**
for in level 18 does not check for var existence, causing a Python error to leak out.

**Paste the Hedy code & level**
```
naam = 'Hedy'
print('ik heet', naam)
hánk = 1
hánk = 2
for i in range(hánk, hánk2):
    print(i)
```

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/1003685/152210501-05c5b66e-806a-44f7-952b-00b49cab93b4.png)

**Comment by Robernc** [comment]
It appears that this is no longer an issue. Hedy correctly checks for var existence and there is no leakage of a python error.
I have included images of the code running correctly below.
![image](https://user-images.githubusercontent.com/59849852/160698534-f47f903f-9630-4426-9802-c9c7db00c227.png)
![image](https://user-images.githubusercontent.com/59849852/160698702-084b4c45-294d-4976-b86c-fa3bd74b7442.png)

**Comment by Felienne** [comment]
ah thanks for checking @Robernc! Fixed bugs are my favorite ones :D
