### ISSUE TITLE
When #189 is closed, the characters need to be localized 

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#190]
I just translated Dutch and English, the other languages need to be translated to kids appropriate words for symbols, in this folder: https://github.com/Felienne/hedy/tree/master/coursedata/texts

**Comment by fpereiro** [comment]
Done [here](https://github.com/Felienne/hedy/pull/189/commits/37081187bd47f84e4f932a2bfd5c01d252e23868) in Portuguese & Spanish, only French missing!

**Comment by fpereiro** [comment]
The English placeholders in French are also added.

**Comment by fpereiro** [comment]
In #199 the French translations are added. Spanish and Portuguese are already there. I think we can safely close this @Felienne

**Comment by Felienne** [comment]
Yes, only German misses this, see my comment on #198
