### ISSUE TITLE
[BUG] Extra field needed for Hindi to make advance button look proper

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1926]
Currently, we have two fields for the advance button:

`{{ ui.advance_button }} {{ next_level }}`

https://github.com/Felienne/hedy/blob/ead6cadb5f68e6b0175318f75dc440024d6fb208/templates/incl-editor-and-output.html#L102

But some languages like Hindi need a different structure, something like: "goto 2nd level" where the number needs to go in between. We need to add an extra field in the UI text, make it empty for all non-Hindi languages and then render it properly. In the new Hindi translation (not yet in a PR) the translators will put a _ where the number should go so I know where the snap the text in half.

**Comment by TiBiBa** [comment]
I just implemented a possible fix, but I'm not sure if I understand the issue completely. Can you take a look at PR #2072 ?
