### ISSUE TITLE
Rename coursedata folder

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#1931]
The name `coursedata` stems from way back but we don't use the word course anywhere, so maybe `content` is better. Making an issue because it might involve some renaming in the codebase too and some thorough manual testing of all languages.

**Comment by ThomasKluiters** [comment]
Oh dear, this is gonna be fun! Will pick it up - but let's coordinate the merging with existing changes :)

**Comment by Felienne** [comment]
> Oh dear, this is gonna be fun! Will pick it up - but let's coordinate the merging with existing changes :)

Yeah it might be easier to make a fresh PR, and I think we do need to merge it immediately to not cause issues again.
