### ISSUE TITLE
[BUG] I can't reach the customize class page anymore

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#1933]
I get this error message:

![image](https://user-images.githubusercontent.com/80678586/153377574-787fbd88-c015-40f6-bfa5-cb627951babe.png)

**Comment by Felienne** [comment]
I have the same indeed @MarleenGilsing! Guess @TiBiBa needs to look at this when he is back from vacation.

**Comment by TiBiBa** [comment]
I'm also only able to re-product this on beta, weird! Might there be some difference in server settings between alpha and beta?

**Comment by TiBiBa** [comment]
This was an issue in the database, it is fixed and this issue can be closed!
