### ISSUE TITLE
[CONTENT] Add explanation on how to add and costumize lessons in Teacher Manual

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#1939]
All the cool new features should be mentioned in the teacher manual under preparations.

**Comment by TiBiBa** [comment]
Closed because this is covered by the teacher tutorial (however, we should still improve the teacher documentation!)

**Comment by Felienne** [comment]
> we should still improve the teacher documentation!

Do we have an issue open for this for @MarleenGilsing?

**Comment by MarleenGilsing** [comment]
Only #712 to add more frequently made mistakes

**Comment by Felienne** [comment]
An issue number with 3 digits, that must be very old :D

**Comment by MarleenGilsing** [comment]
It has its first birthday in just a couple of months 🥳

**Comment by Felienne** [comment]
Maybe we (by which I mean you, hahaha) can aim to close it before it turns 1 🤣 ?

**Comment by MarleenGilsing** [comment]
Well, I was planning to have a nice party for it, but alright, alright.. I'm on it ;)

**Comment by MarleenGilsing** [comment]
Done :) #2954
