### ISSUE TITLE
`repeat` level 11 and further

### ISSUE THREAD

**Issue by juliabolt** [Felienne/hedy#1942]
Right now, in level 10, `repeat` and `for` both work, but from level 11 on, only `for` works.
Maybe, we would want `repeat` to keep working.
After discussing this with @Felienne , we decided the following. (correct me if I'm wrong)
The SEMANTICS.md file will be adjusted to how Hedy works now, so `repeat` is not possible in level 11 and further, and that should be the same in the language for now, to keep things consistent.
Later on, `repeat` can be added in level 11 and further in the language and the semantics, if/when we have that working (but that might take a while).

So now, `repeat` should be removed from level 11 and further.

**Comment by Felienne** [comment]
This is quite doable too I think @huang-v, maybe easier even than the translation of the keywords that need indentation

**Comment by huang-v** [comment]
I am confused on what needs to be changed. Currently "from level 11 on, only for works." which I have tried and observed. If the issue is asking to remove repeat for level 11 and beyond, that is already the current observed behavior. Is the issue asking to reimplement repeat to work for level 11+?

**Comment by Felienne** [comment]
for indeed is fine as it is. The idea was to add repeat to levels over 11.

**Comment by huang-v** [comment]
I am currently working on this issue. 
I was able to successfully enable repeat for levels over 11 but am struggling to get the keyword repeat highlighted. 
![image](https://user-images.githubusercontent.com/102200726/160972202-fcae9c30-9d2c-411e-86b2-87ac15e52c72.png)
Where is highlight information stored?

**Comment by huang-v** [comment]
I noticed that keywords in other languages don't seem to be highlighted either. 
![image](https://user-images.githubusercontent.com/102200726/162607334-fba28b2a-2d28-46cb-811c-e25f085012a1.png)(from level 8)
Do I need to highlight the text? If so, could I get some assistance?

**Comment by Felienne** [comment]
@thjazi39 can probably help.

But note that keywords in other langs will only be highlighted if you enable the corresponding keyword lang in your profile!

**Comment by Felienne** [comment]
Highlighting info is here (f.e. for Spanish): 

https://github.com/Felienne/hedy/blob/main/static/js/syntaxLang-es.ts

**Comment by thjazi39** [comment]
> I am currently working on this issue. I was able to successfully enable repeat for levels over 11 but am struggling to get the keyword repeat highlighted. ![image](https://user-images.githubusercontent.com/102200726/160972202-fcae9c30-9d2c-411e-86b2-87ac15e52c72.png) Where is highlight information stored?

In level 11 and above, the repeat x times command doesn't exist anymore, that's why it's not highlighted !

**Comment by thjazi39** [comment]
oh, I hadn't read the whole thread, Sorry ! To add syntax highlighting on a command, it happens in the file : https://github.com/Felienne/hedy/blob/main/static/js/syntaxModesRules.ts

precisely here : https://github.com/Felienne/hedy/blob/b7405e5ba5f5421adfc3eabd8532c01954e3a851/static/js/syntaxModesRules.ts#L303

And the details of how it works is explained here : https://github.com/Felienne/hedy/blob/b7405e5ba5f5421adfc3eabd8532c01954e3a851/static/js/syntaxModesRules.ts#L115

Concerning the languages, it happens in the files `syntaxLang-XX.ts`, the comprehension of the file is quite easy.

If you want more explanation, don't hesitate to tag me, I could explain you more in detail !

**Comment by huang-v** [comment]
![image](https://user-images.githubusercontent.com/102200726/164135435-033ef0d9-6216-4e3c-a140-baeb93d63dc0.png)
Despite adding repeat to the list, I'm still having trouble highlighting the text
![image](https://user-images.githubusercontent.com/102200726/164135825-3ff46879-9199-4f81-ab84-dd924fb5ea47.png)
It doesn't seem like what I'm adding to syntaxModesRules.ts is affecting anything. When I remove an entry it still highlights that keyword
![image](https://user-images.githubusercontent.com/102200726/164135922-36f6e97c-007b-4f04-b4af-0d653544de59.png)
I do have this setup to update the text. Is there something wrong with how I'm running Hedy?

**Comment by Felienne** [comment]
Have you compiled the typescrict files after your changes?

**Comment by huang-v** [comment]
Yes, I ran build-tools/heroku/generate-typescript --watch

**Comment by Felienne** [comment]
Ok, then I don't know either, but since we are overhauling the highlighter anyway, I propose you do not pursue this further at this point in time.

**Comment by huang-v** [comment]
Should I make a pull request for the changes that enable repeat to work on levels 11+?

**Comment by Felienne** [comment]
> Should I make a pull request for the changes that enable repeat to work on levels 11+?

I don't understand this question, sorry. The issue is to _remove_ repeat from levels 11 and up for now.

**Comment by Felienne** [comment]
> Should I make a pull request for the changes that enable repeat to work on levels 11+?

Yes that is ok, and if it does not work with highlighting, that is ok, we can fix that later.

**Comment by thjazi39** [comment]
It's done by #2572
