### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by burkhardpranke** [Felienne/hedy#1969]
**Describe the bug**
A typo in the example code:
scisscors instead scissors

**Paste the Hedy code & level**
It is super helpful if we can copy-paste the Hedy code to test, so please paste the code here, and don't forget to tell us what level you were in.
Level 9: Rock, Paper, Scissors

Example code:
choices is rock, paper, scisscors
your_choice is ask 'What do you choose?'
print 'You choose ' your_choice
computer_choice is choices at random
print 'The computer chooses ' computer_choice
if computer_choice is your_choice
    print 'Tie'
if computer_choice is 'rock'
    if your_choice is 'paper'
        print 'You win!'
    if your_choice is 'scissors'

**Add a screenshot (optional)**
Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.

![grafik](https://user-images.githubusercontent.com/4788580/153953907-6ef01d74-3ee4-4ef5-8f9e-c4217ada1cdb.png)

**Expected behavior**

The program executes like this:

     You choose rock
     The computer chooses scisscors

And stops

It should say who is winning thou

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?) Linux
- What browser you were using (Chrome, Edge, Safari)  Firefox

**Comment by Felienne** [comment]
I am not sure what it up here, but maybe you can verify this @huang-v?

Giving extra information on vague issues is also a valuable contribution!

**Comment by huang-v** [comment]
Happy to help, 

I remember a mention of the same typo on #2186 but the typo doesn't currently appear on the live website so it appears to have been fixed at some point.  I checked on both Chrome on Windows and Firefox on Linux VM.
![image](https://user-images.githubusercontent.com/102200726/159967658-e58aecc5-59c5-4591-bae5-7f8fd9dc97b9.png)


As for the program not outputting the winner, the code provided is the same as the example code which is unfinished and only accounts for ties and the computer choosing rock. Since there is nothing to account for scissors (or scisscors) as the computer's choice, there is no output stating who won the exchange.

**Comment by Felienne** [comment]
Ah ok so this not really an issue? Maybe we should insert a blank (_) in the program to make it more clear that it has to be finished?

**Comment by huang-v** [comment]
A comment could be added to the end, something like `# finish this code`. This would allow users to still run the example code while providing them with a reminder when they're looking through the code.

**Comment by Felienne** [comment]
I like that idea! This is one of our oldest code snippets form before when we had blanks and comments! Would love it if you make a PR with this change!

**Comment by huang-v** [comment]
I noticed that the text is handled by separate .yaml files for each language. Is it fine to submit the PR with only modifications to the english file?

**Comment by Felienne** [comment]
> I noticed that the text is handled by separate .yaml files for each language. Is it fine to submit the PR with only modifications to the english file?

Yes that is ok! Weblate will mark the change so translators for other languages know it needs to be updated

**Comment by Liz433** [comment]
Hi, is this still an issue? I would like to contribute if it has not been fixed yet
