### ISSUE TITLE
[UI idea] Add more achievements related to class customizations and adventures

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1970]
**Idea incl level**
With the implementation of class customizations and custom adventures we provide a lot more functionality for teachers. It would be nice if we also have some achievements related to these. Also it might be nice to add some extra achievements on public profiles and the explore page.

**Comment by TiBiBa** [comment]
This one is a bit out of context without any priority. Closed for now, we can always add more achievements later on.

**Comment by Felienne** [comment]
Yeah maybe we should reserve [CONTENT] issues for *problems* with content and discuss new ideas for content (which this is too, in principle) on the Discord or in a discussion?
