### ISSUE TITLE
[BUG] Settings favorite program from programs page not working

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1976]
**Describe the bug**
Currently when clicking the 'favorite' icon on the programs page a message is returned that the program is successfully set as favorite. However, this change is not made in the back-end. Cause is unknown as the setting of a favorite program does work as expected when setting one in profile settings.

**Expected behavior**
When selecting a favorite program on the programs page this change should be made in the database.

**Comment by aelhamah** [comment]
Hi @TiBiBa , I'm new to open source contributing and would like to help! I recently cloned and ran Hedy locally, and I was wondering if I could take on/be assigned to this issue.

**Comment by TiBiBa** [comment]
> Hi @TiBiBa , I'm new to open source contributing and would like to help! I recently cloned and ran Hedy locally, and I was wondering if I could take on/be assigned to this issue.

Hi @aelhamah, welcome! Awesome that you are willing to help on Hedy, I just assigned you to this issue. If you need any help in general on contributing to our project, please take a look at the `CONTRIBUTING.md` file. If you have any other questions or suggestions, feel free to sent me a message!

**Comment by aelhamah** [comment]
> Hi @aelhamah, welcome! Awesome that you are willing to help on Hedy, I just assigned you to this issue. If you have any questions in general on contributing to our project, please take a look at the CONTRIBUTING.md file. If you have any other questions or suggestions, feel free to sent me a message!

Thank you @TiBiBa ! I was actually having trouble replicating the bug, do you have a specific user scenario where the buggy behavior occurs? Currently, I've just tried setting the favorite program on the programs page then heading over to the public profile to check if the favorite was updated and vice versa. Also, I just wanted to double-check that the user can only have one favorite program. In other words, when the user selects a new favorite program while another is already selected, it should deselect the original favorite program.

**Comment by TiBiBa** [comment]
> > Hi @aelhamah, welcome! Awesome that you are willing to help on Hedy, I just assigned you to this issue. If you have any questions in general on contributing to our project, please take a look at the CONTRIBUTING.md file. If you have any other questions or suggestions, feel free to sent me a message!
> 
> Thank you @TiBiBa ! I was actually having trouble replicating the bug, do you have a specific user scenario where the buggy behavior occurs? Currently, I've just tried setting the favorite program on the programs page then heading over to the public profile to check if the favorite was updated and vice versa. Also, I just wanted to double-check that the user can only have one favorite program. In other words, when the user selects a new favorite program while another is already selected, it should deselect the original favorite program.

Hi! Sorry, my description of the bug might have been a bit cryptic. I just tried and I was also unable to duplicate the bug, it id possible this has been solved already as we have done a lot of front-end clean-up that might accidentally solved this as well. The original issue was when settings a favorite program from the programs page a success message was returned, but the program itself was not correctly set as favorite.

Users can only have one favorite program. Because the program is not set as favorite on the program itself but rather on the public profile of the user, which can only have one favorite program value. So no need to de-select the old favorite program. For developing local Hedy uses a local database stored in the `dev_database.json` file, you can always check that file to get familiar with the database structure and verify that changes are correctly stored.

I will close this issue as it is no longer relevant, but if I want to pick up another one feel free to scroll through the issues and send me a message. Do you have any type of issues you prefer to work on? (Front-end, Database etc.) You of course are also free to roam the website and create an issue yourself if you find any bugs or unusual behavior!

**Comment by aelhamah** [comment]
>>> Hi @aelhamah, welcome! Awesome that you are willing to help on Hedy, I just assigned you to this issue. If you have any questions in general on contributing to our project, please take a look at the CONTRIBUTING.md file. If you have any other questions or suggestions, feel free to sent me a message!

>> Thank you @TiBiBa ! I was actually having trouble replicating the bug, do you have a specific user scenario where the buggy behavior occurs? Currently, I've just tried setting the favorite program on the programs page then heading over to the public profile to check if the favorite was updated and vice versa. Also, I just wanted to double-check that the user can only have one favorite program. In other words, when the user selects a new favorite program while another is already selected, it should deselect the original favorite program.

> Hi! Sorry, my description of the bug might have been a bit cryptic. I just tried and I was also unable to duplicate the bug, it id possible this has been solved already as we have done a lot of front-end clean-up that might accidentally solved this as well. The original issue was when settings a favorite program from the programs page a success message was returned, but the program itself was not correctly set as favorite.

> Users can only have one favorite program. Because the program is not set as favorite on the program itself but rather on the public profile of the user, which can only have one favorite program value. So no need to de-select the old favorite program. For developing local Hedy uses a local database stored in the dev_database.json file, you can always check that file to get familiar with the database structure and verify that changes are correctly stored.

> I will close this issue as it is no longer relevant, but if I want to pick up another one feel free to scroll through the issues and send me a message. Do you have any type of issues you prefer to work on? (Front-end, Database etc.) You of course are also free to roam the website and create an issue yourself if you find any bugs or unusual behavior!

Thank you for clarifying! I saw #2073 was unassigned. Could I potentially work on that issue?
