### ISSUE TITLE
[CONTENT] error quiz 9/10

### ISSUE THREAD

**Issue by thjazi39** [Felienne/hedy#1978]
When translating quiz 9, I noticed several errors:
The first one is a terminal error (10 instead of 3)

and when I wanted to test the code (to know if the upper bound is included) I realized that the for does not exist in level 9!

I think there is a level error for this quiz (the next questions are also about `for` commands) and this command appears only in level 10

![9-1](https://user-images.githubusercontent.com/48509466/154055410-8e5e8cec-418f-415a-9ab5-56d752ac1c5f.png)

**Comment by Felienne** [comment]
> When translating quiz 9, I noticed several errors: The first one is a terminal error (10 instead of 3)

Can you change the 10 to 3?

> and when I wanted to test the code (to know if the upper bound is included) I realized that the for does not exist in level 9!
> I think there is a level error for this quiz (the next questions are also about `for` commands) and this command appears only in level 10

Ah good catch @thjazi39!! This is because we made some changes to the levels. Can you move those two questions to level 10?

**Comment by thjazi39** [comment]
> Can you move those two questions to level 10?

Ok, I'll do it, but it's not only the first 2 questions of quiz 9 that are not in the right place, all the questions are related to the `for`

**Comment by thjazi39** [comment]
I think it's quiz 9 that should become a 10 (and the 10 of the next quiz that should become an 11)

**Comment by Felienne** [comment]
> I think it's quiz 9 that should become a 10 (and the 10 of the next quiz that should become an 11)

Ah sorry, misnumbered!
