### ISSUE TITLE
Fix parse errors in German

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#198]
Not sure why but in German, the nice grammar errors don't work (I guess we miss translations?)

![image](https://user-images.githubusercontent.com/1003685/109849329-8cb80f00-7c51-11eb-9658-dbf61b1709ee.png)

**Comment by fpereiro** [comment]
@Felienne I believe this is fixed in PR #201 so we can safely close it.

**Comment by Felienne** [comment]
it is partly solved, but we now still mis a bunch of translations for the Errormessages, see: 

![image](https://user-images.githubusercontent.com/1003685/110311502-2a219300-8004-11eb-9b8c-cef572a2312c.png)

Shall we close this one and make a new issue for the missing translations?

**Comment by fpereiro** [comment]
I think so, I'll modify the existing issue for missing German translations now. Feel free to reopen if you feel it's best!
