### ISSUE TITLE
[BUG] A valid public Hedy program hangs

### ISSUE THREAD

**Issue by boryanagoncharenko** [Felienne/hedy#1983]
**Describe the bug**
I encountered an interesting program in the production Explore page and was curious to see what happens when I run it. The result is that the Hedy page hangs and after a while the browser politely offers to exit the page. Please note that this is a public program which means that it is easily accessible to other users.

**Paste the Hedy code & level**
Level 1
```
forward 999999999999999999
```

**Add a screenshot (optional)**
![Screenshot 2022-02-15 at 15 35 53](https://user-images.githubusercontent.com/3010723/154073022-3d3e89ec-17e3-4509-99f5-64a8704cc3d4.png)

**Expected behavior**
Probably we should give an error when forward is given very large values. However, we should also determine what constitutes as "very large values".

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using? Mac
- What browser you were using? Chrome

**Comment by Felienne** [comment]
hmmm why does this hang and not stop after 3 seconds like Hedy programs are supposed to do?! Maybe we don't have that protection for the turtle?

**Comment by TiBiBa** [comment]
Interesting! It should automatically terminate after 20 seconds (when either a turtle or sleep is used). Will take a look!

**Comment by TiBiBa** [comment]
I just tried to figure this out and I don't think we will be able to fix this on the front-end. We can decrease the time-out to 10 seconds (instead of the current 20). But this doesn't make any difference as the program crashes from the start. Sculpt has two interesting built-in function we can user for other hangs:

- killableWhile
- killableFor

These two scan the programs for infinity loops and terminate the program. Really useful, but doesn't apply to our turtle issue. I think the best solution would be as suggestion by @boryanagoncharenko, have some limit on the turtle behavior. This doesn't have to be complex, as the maximum size of the canvas is around 600x300px we can simply say "no values allowed above 600". We have to adjust the parser to return a corresponding error, but this would be a feasible solution. Together with the above suggested functions we would be able to catch (almost) all front-end crashes.

**Comment by TiBiBa** [comment]
I was wondering as well: Currently we configure Skulpt each time we run a program. Is this really necessary? Aren't we able to simply configure it once at calling the code page and then never again? Might improve some speed on the front-end, but I'm not sure how Skulpt works exactly so correct me if I'm wrong.

**Comment by boryanagoncharenko** [comment]
I think this is not an easy problem to solve in the backend either. The program at hand uses a literal integer which we could internally try to parse as an int and validate. However, at level 3 already the user can do this:
```
steps is 1000, 2000, 3000
forward steps at random
```
which means we need to adapt the python code to regulate the value at runtime.

Ideally, we would give the user a warning which says: "You tried to use the command 'forward' with input that was too big, so we adjusted it to something that is allowed". However, we don't have a mechanism to get warnings from Skulpt, is that right @TiBiBa? If so, the only idea I have is to adjust the python code so that it parses the forward input, corrects it to default value if something is wrong (e.g. the value is too big or it is a string) and silently give that code to Skulpt to execute.

**Comment by boryanagoncharenko** [comment]
I pushed a branch containing experimental runtime adjustment of incorrect values for the turn and forward commands. The tests fail - I will not adapt them before getting validation on your end. Here is how it works:
- If the user passed a large number, it will be capped. So no more crashing. Unfortunately, we don't provide any feedback to the user that we capped.
- If the user supplied a non-integer value, we will provide an error message. Unfortunately, we cannot translate this error message (or at least not without further effort). I experimented here with converting non-integer input to something default (e.g. 0 or 50), but I found this to be very confusing. In my opinion it is better to provide an error message.

Or if you prefer the above explanation in code: https://github.com/Felienne/hedy/blob/issue-1983/hedy.py#L1203-L1211

Here is how it looks:
The command argument is capped to [-600, 600], so the turtle does go out of the screen, but the program does not crash:
![Screenshot 2022-02-22 at 11 19 33](https://user-images.githubusercontent.com/3010723/155101663-090bf882-ae2d-41c2-99c8-20bbd2a9482b.png)

![Screenshot 2022-02-22 at 11 18 39](https://user-images.githubusercontent.com/3010723/155101708-87905160-616e-4d0f-bb53-aad7169cffec.png)

This is how the error looks for non-integer input:
![Screenshot 2022-02-22 at 11 19 09](https://user-images.githubusercontent.com/3010723/155101808-f0ca103c-4b02-4154-952f-111c929270d1.png)

@Felienne @TiBiBa What do you think?

**Comment by Felienne** [comment]
Thanks for this @boryanagoncharenko! I think this is a good way to go, it nicely balances non-hanging (which we don't want) and good feedback (which sadly here we can't give fr the capping but visually it is clear I think)

**Comment by Felienne** [comment]
Feel free to run this into a PR!
