### ISSUE TITLE
[CONTENT] Level 5 example uses = instead of `is`

### ISSUE THREAD

**Issue by burkhardpranke** [Felienne/hedy#1986]
We is = and not `is` which the tests do not catch because the code also has `_`.

**Hedy code & level**
Level 5: rock,  paper, scissors
```
options = rock, paper, scissors
computer_choice is _
choice is ask What do you choose?
print 'you chose ' _
print 'computer chose ' _
if _ is _ print 'tie!' else print 'no tie'
```

in the first line the "=" should be replaced by "is"

**Add a screenshot (optional)**
Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.
![grafik](https://user-images.githubusercontent.com/4788580/154084391-edd2e2e7-425f-4f34-ad06-ab17c2298705.png)

**Comment by Felienne** [comment]
Let me know if you can pick this up @DerSibi! If not I can do it too!

**Comment by DerSibi** [comment]
Sure, why not :)
