### ISSUE TITLE
[UI idea] Support language switcher on all code snippets

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#1987]
**Idea incl level**
Current we only support the language switcher on the main code editor and the adventure tabs. It would be nice to support this everywhere. Such as the common mistakes page for teachers and the own adventures page. This requires some re-writing as we currently base the level on `window.State.level`. This value doesn't exist everywhere.

**Comment by Felienne** [comment]
>Current we only support the language switcher on the main code editor and the adventure tabs. It would be nice to support this everywhere.

Yes! And also (separate issue?) can we make a profile setting out of this too? I would love to be able to set it such that all code snippets will be shown in Dutch and I do not see the switcher anymore. 

Also also (yet another separate issue?) a teacher might want to set this for all students in a class.

**Comment by TiBiBa** [comment]
Will make some separate issues! I think both will be quite complex, but the workflow would be similar to how we implemented preferred languages.

**Comment by TiBiBa** [comment]
We can close this as this is no longer relevant. (We only show the switcher on the main editor, users set a keyword language in their profile settings).
