### ISSUE TITLE
[CONTENT] level 4 - verhaal vermeld onjuiste levelnummer

### ISSUE THREAD

**Issue by ericverschoor** [Felienne/hedy#1993]
In level 4 - verhaal wordt verwezen naar level 3, wat level 4 zou moeten zijn
![047E986E-B95A-47F4-8E79-EE48A6A5AB07](https://user-images.githubusercontent.com/45706519/154140790-b8cb5a71-7411-462a-bc20-9698700249b1.jpeg)

**Comment by Felienne** [comment]
Haha, oops! Ja die was vroeger level 3 en nu level 4. 

Misschien kun je voor dit soort kleine dingen ook een PR aanmaken? Dat zou wel superfijn zijn, en niet heel veel meer moeite 🙏 

De tekst voor de tabjes staat in adventures:
https://github.com/Felienne/hedy/blob/c46a4ce9fe1055830e06207692bcbdaf2fa82c58/content/adventures/nl.yaml#L255

En je kunt met edit vanuit de browser een PR aanmaken, hoef je niet eens te forken:
![image](https://user-images.githubusercontent.com/1003685/154211288-aefb1fbc-06d0-492a-a9cd-8dac115633d9.png)
