### ISSUE TITLE
[BUG] lvl 4 - print string variable includes quotation mark

### ISSUE THREAD

**Issue by ericverschoor** [Felienne/hedy#1994]
Given the following  program

    a is 'this is it'
    print a
    print 'this is it'

Print line 2 includes quotation marks, where print line 3 doesn’t

I expect the output to be similar

![03052A9C-2D62-4857-837D-2836F8ABE886](https://user-images.githubusercontent.com/45706519/154144555-1e3ca71e-8f78-423e-9973-7ec65c2a79d9.jpeg)

**Comment by ericverschoor** [comment]
Related to #1997

**Comment by Felienne** [comment]
Same as #1992, I appreciate you are testing weird edge cases like assigning with quotes, but these type of things are not what we optimize for at this point in time. 

Plus in this case, the behaviour it is consistent with the rules that we explain: with `is` you can assign anything, including quotes. For `print`, the quotes are needed and thus "eaten" on output.
