### ISSUE TITLE
[BUG] lvl 4 at random is not highlighted  as a command

### ISSUE THREAD

**Issue by ericverschoor** [Felienne/hedy#1995]
In lvl 3, the `at random` command is highlighted in red because it is a command
![E4FBA130-0912-407C-991E-6C25D48571DF](https://user-images.githubusercontent.com/45706519/154145317-bdb36335-2095-4db5-bbc3-918e87a0122a.jpeg)

but in lvl 4, `at random` is not highlighted
![66378A2E-6554-47A1-A8A5-6E1521514C8F](https://user-images.githubusercontent.com/45706519/154145366-d28309d1-7261-4a64-aba9-aaa28e3e1eb6.jpeg)

**Comment by Felienne** [comment]
Syntax highlighting is an open issue (#1285) that is currently being worked on (#1890).

**Comment by Felienne** [comment]
Ah this works for level 4 but not for level 5:

![image](https://user-images.githubusercontent.com/1003685/155511772-fe7ecc3b-49de-4727-bc9d-2cbb51549874.png)

Maybe also one for you @thjazi39 as a nice intermediate step?

**Comment by Felienne** [comment]
Ah never mind it was a simple fix, will be done with #1890

**Comment by thjazi39** [comment]
after verification, the bug is well solved in the upper levels
