### ISSUE TITLE
Problem with á, é and ó in level 1 ask command (needed for Spanish).

### ISSUE THREAD

**Issue by rickbeerendonk** [Felienne/hedy#20]
Level 1, ask command:
In Spanish the official spelling is "ask Cuál es tu color favorito?". But that cannot be executed at this moment.

Two options:
1. Allow á, é and ó as this is used in all Spanish questions (qué, cuál, quién, cómo, cuán, cuánto, cuándo, dónde & adónde = what, which, who, how, how, how much, when, where & where)
2. Adjust the Spanish translation (for the time being) to not use the diacritical marks.

@mivalencia

**Comment by dragondave** [comment]
I've got a potential solution to this: https://github.com/Felienne/hedy/pull/23

**Comment by Felienne** [comment]
Hmmm, the grammar works but there is an issue in the UI, reopening.

**Comment by Felienne** [comment]
Closed! Now also working in the front-end by https://github.com/Felienne/hedy/commit/2d4993e6b8b83de44d5504e76de286bf34ff74a9
