### ISSUE TITLE
[UI idea] Enable teachers to enforce keyword language in class

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#2009]
**Idea incl level**
A description of your idea, for example: "I would like to be able to save and freeze programs so they cannot be edited"

**Additional context**
Add any other context about the idea here.

**Comment by Felienne** [comment]
Good question, I am not really sure what is smart here also. What d you think @OnnoEbbens or @MarleenGilsing? Would you want to be able to control if kids may use Dutch or English keywords?

**Comment by OnnoEbbens** [comment]
I don't necessarily want to control the keyword language for the kids but it could be nice to have this as a class setting. Then you can make sure everyone in the class has the same settings. However if this is hard to implement I wouldn't bother, it was not very hard for the students to set the keyword language themselves and it works fine now.

**Comment by TiBiBa** [comment]
Just had some thinking about this issue. I will implement an additional settings on the class customization to hide the switcher. The switcher will be shown by default but a teacher will be able to hide it if desirable. I do however have some concerns about the complexity of the customizations. When we keep adding options, we also have to keep adding explanations on how everything works. I would like to keep the UI as simple as possible so new teachers are able to use all functionality without becoming confused or needing our help. So we would have to think about that.

Conclusion: Will implement a hide option on the customizations, but we have to think about a better long-term solution.

**Comment by MarleenGilsing** [comment]
@TiBiBa Maybe we can clean up the teacher page a bit by making a button 'extra settings' or 'advanced settings'. We could put all the extra options in there to keep the main page cleaner. We could also put the 'Rename class' and 'show class statistics' and 'add students' in there, as they currently have a quite prominent place in the teacher interface for buttons that aren't used that much.
