### ISSUE TITLE
[UI addition] Agree to third party info on signup

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2023]
Since we are finalising our agreement with Lyceo, we need to add a tickmark to account signup where people agree that they might be contacted by third parties we work with. We need to save this consent in the database we so can share only the information of people that agree with Lyceo.

**Comment by TiBiBa** [comment]
Should this be a required or optional tickmark?

**Comment by Felienne** [comment]
> Should this be a required or optional tickmark?

Optional!
