### ISSUE TITLE
[CHORE] Switch to Babel for translations

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#2030]
Currently we are dependent on YAML files for our translations. This is a great starting point, but it is getting a bit out-of-hand. Whereas yamls are still useful for complete page translations such as the homepage or learn-more page. It would be more efficient to use a dedicated translation library such as Babel for all our other translations.

Babel will automatically extract the correct translation from the corresponding file, based on our set language. Currently we have some homemade dictionary matching to overwrite the default English values with the current language. This works, but on a large scale is slow and in-efficient.

**This is a very very big chore and needs some clear planning before proceeding**

**Comment by Felienne** [comment]
Just to clarify @TiBiBa, will this affect content or just the code? Concretely: will the content remain in the yaml-files, because we are just setting up Weblate to work with the yamls more or less like they are now.

**Comment by TiBiBa** [comment]
> Just to clarify @TiBiBa, will this affect content or just the code? Concretely: will the content remain in the yaml-files, because we are just setting up Weblate to work with the yamls more or less like they are now.

This will affect the content as well as the translations will be stored in a new structure. I think the structure for adventures, pages and level-defaults works fine with the current YAML structure.

The biggest bottle-neck at this point is that we constantly re-create and pass around variables that contain certain parts of the translation (Auth, ui, ClienErrorMessages). I haven't measured it yet, but this seems like a lot of unnecessary server-load. Switching to Babel can fix this for us.

Maybe we can switch to Babel for all our "small" translations in `/texts`? They seem to be the biggest back-end issue.

**Comment by Felienne** [comment]
> Maybe we can switch to Babel for all our "small" translations in `/texts`? They seem to be the biggest back-end issue.

This sounds like a great first step!!

Potentially you can work together with @Mark-Giesen on this? He also wanted to move some content to gettext() which is think is similar to Babel? Starting with the texts sounds like a great plan, but it will also affect the Weblate config so you do sync with Mark.

**Comment by TiBiBa** [comment]
> > Maybe we can switch to Babel for all our "small" translations in `/texts`? They seem to be the biggest back-end issue.
> 
> This sounds like a great first step!!
> 
> Potentially you can work together with @Mark-Giesen on this? He also wanted to move some content to gettext() which is think is similar to Babel? Starting with the texts sounds like a great plan, but it will also affect the Weblate config so you do sync with Mark.

Yes Babel does use gettext()! Will get in contact with @Mark-Giesen. For now I will already make a branch to try some things out!
