### ISSUE TITLE
tailwind/generate-development-css doesn't work

### ISSUE THREAD

**Issue by rix0rrr** [Felienne/hedy#2039]
**Describe the bug**

The `build-tools/heroku/tailwind/generate-development-css` script generates an empty css file, instead of a CSS file with all the Tailwind bells and whistles.

It looks like it's stripping all classes, because they're unused, because it's not configured with any files to look at for classes to retain.

This means you have to use `generate-css` to generate the CSS, but that will only retain classes that are actually currently being used.

The upshot of all this is that if you want to experiment with new Tailwind classes, you must:

* First write HTML
* Then regenerate Tailwind CSS
* Then refresh your browser (hard-refresh so it doesn't cache!) to see the results of the new class

It would be better if the checked-in `generated.css` always contains the full Tailwind distribution with all classes. Yes, it'll be large, but at least you can develop to your heart's content.

To make that work, we need to fix `generate-development-css` and `tailwind.full.js` though...

**Comment by TiBiBa** [comment]
I noticed this as well! However, I always use the method as described above: type your code, generate Tailwind and refresh the browser (in incognito mode). Might not be the most efficient way, but most of the times I use classes that are already there. However, I do agree that this should be fixed: will take a look!
