### ISSUE TITLE
Add missing German translations

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#205]
![image](https://user-images.githubusercontent.com/1003685/110076252-79599080-7d84-11eb-9b2c-de01df11726a.png)

I think step this might also be missing from our translation instructions?

**Comment by fpereiro** [comment]
We're also missing translations for lines 32-42 of coursedata/texts/de.yaml to improve user errors

**Comment by fpereiro** [comment]
Summary of missing translations:j
- Main page: https://github.com/Felienne/hedy/blob/master/main/start-en.md
- Press section and contact section: https://github.com/Felienne/hedy/blob/master/main/contact-en.md and https://github.com/Felienne/hedy/blob/master/main/press-en.md
- Hedy docs: https://github.com/Felienne/hedy/tree/master/coursedata/course/hedy/docs-en
- Lines 34-44 of  https://github.com/Felienne/hedy/tree/master/coursedata/texts/de.yaml

**Comment by dpprdan** [comment]
Current status:
- [x] Main folder 
	- [x] Start section https://github.com/Felienne/hedy/blob/master/main/start-en.md
	- [x] Press section https://github.com/Felienne/hedy/blob/master/main/press-en.md
	- [x] Contact section: https://github.com/Felienne/hedy/blob/master/main/contact-en.md
	- [x] Teachers section: https://github.com/Felienne/hedy/blob/master/main/for-teachers-en.md
	- [x] Learn more section: https://github.com/Felienne/hedy/blob/master/main/learn-more-en.md
- [x] Lines 34-44 of https://github.com/Felienne/hedy/tree/master/coursedata/texts/de.yaml
- [ ] Code examples for levels 8-17: https://github.com/Felienne/hedy/tree/master/coursedata/level-defaults/en.yaml
- [ ] Adventures: https://github.com/Felienne/hedy/blob/master/coursedata/adventures/en.yaml

🤔 Has this been moved?
- [ ] Hedy docs: https://github.com/Felienne/hedy/tree/master/coursedata/course/hedy/docs-en

**Comment by Felienne** [comment]
It is no longer feasible to manage translations with issues, moving this to a dedicated mailing list
