### ISSUE TITLE
[BUG] error when using . in quoted strings in level 11 and up

### ISSUE THREAD

**Issue by thjazi39** [Felienne/hedy#2056]
When we try to assign several variables in a row, like in the following code, we get several errors
```MAX_VALUE is 26
SIZE_ARRAY is 50
input_data is 'strInput'
i_input_data is 0
input_code is '+[----->+++<]>+[--->+<]>----.'
i_input_code is 0
tableau is 0
i_ptr is 0
```

In levels 4->17, on the github version, we get :
![image](https://user-images.githubusercontent.com/48509466/155109169-e6c32fe8-e6c2-42ae-890f-b730007ceb2e.png)

In levels 2-3 this first triggers another error, because of the dot that is not allowed, but when the dot is removed, the above error is 
the dot, we get the above error again

and on the hedycode.com version (level 11), we get a 3rd error, which is obviously due to the presence of +/- in a string

![image](https://user-images.githubusercontent.com/48509466/155109272-39e9eb8e-c45b-4949-acf5-fc8bcdf68422.png)

If this bug is actually made of several bugs, I could decompose it in several issues

**Comment by Felienne** [comment]
Hi @thjazi39,

I can't reproduce the first issue on alpha:

![image](https://user-images.githubusercontent.com/1003685/155149869-1169b523-7376-41e1-a0f3-c3b17f940758.png)

I think you may be using an old version of Lark, can you check that (see #1314 for instructions)

**Comment by Felienne** [comment]
Although I also want to point out that the things you are trying are very unlikely to even occur in kids's code. It would be more beneficial to the project if you stick closer to example codes, then we will find more likely bugs.

It would also be nicer if you separate out different problems in different issues (although I know it can be hard to find root causes)

**Comment by thjazi39** [comment]
Indeed, my version of Lark was not up to date, I redid some tests, and there is no more problem with the points

however, I think that it is rather on the symbols '+' and '-' that there is an error of interpretation

```
a is '-.'
```
=> We can't run your program. a is not a Hedy level 11 command. Did you mean in?


```
a is '.'
```
=> Good job !


```
a is '-'
```
=>  We can't run your program. a is not a Hedy level 11 command. Did you mean in?

**Comment by Felienne** [comment]
Yes quoted string in level 11 should surely work, I will look into that! I tis likely kids will do something like `text = 'well done.'`

**Comment by boryanagoncharenko** [comment]
I ran all code examples in this thread and it seems that using . in a quoted string at any level is currently not a problem. The only issue that is left is using arithmetic operators in quoted strings, which already has its dedicated issue: #2067
@thjazi39 can you please confirm that, so that I can close the current issue?

**Comment by thjazi39** [comment]
Indeed, I stayed the examples, and I do not know how I managed to have an error, probably mistakes when I made my tests
