### ISSUE TITLE
[BUG] English error shown on password conditions

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2057]
I guess we auto-generate this because it does not seem to come form the texts yamls I think?

![image](https://user-images.githubusercontent.com/1003685/155117676-d8b2ddf4-6695-46b5-8914-65444882c2b6.png)

**Comment by TiBiBa** [comment]
We don't have any influence on this text as we set a HTML attribute `minlength=6`. The browser decided the error message that is returned (as it's a built-in function). We can also catch this with jquery and manually return our own message but I thought as it automatically returns the browser language it should be fine.

**Comment by Felienne** [comment]
Ah interesting, so I guess there nothing to be done to localize this in an easy way. Let's hope kids localize their browsers :) 

At the very least then we should remove this from the yaml:

```
    password_six: "Password must contain at least six characters."
```

Because it was a bit confusing to the translators (and to me haha, took me a while to find this!) that this did not come from a yaml.

**Comment by TiBiBa** [comment]
> Ah interesting, so I guess there nothing to be done to localize this in an easy way. Let's hope kids localize their browsers :) 
> 
> 
> 
> At the very least then we should remove this from the yaml:
> 
> 
> 
> ```
> 
>     password_six: "Password must contain at least six characters."
> 
> ```
> 
> 
> 
> Because it was a bit confusing to the translators (and to me haha, took me a while to find this!) that this did not come from a yaml.

This string is still used in the back-end. As we verify the sent body in the back-end as well. For example if a user makes a direct POST to the server or their browser does not support minlength (or they remove the attribute on the front-end) the form can still be submitted. The password in these cases can be too short, so we do have to perform the back-end validation as well.

These situations are not likely. But we still want to return a useful error in the case of this happening.

**Comment by TiBiBa** [comment]
Can we close this issue or do we want to step away from the HTML built-in input validations? It gives us less control over the specific error message but very easily reduce server-load as users are less likely to submit invalid fields.

**Comment by Felienne** [comment]
Yeah we can close this. Maybe if we do have "better yamls" we can leave a comment in that that message will not be shown in the front-end if html can validate the input?
