### ISSUE TITLE
[BUG] In "my programs" reset is not localized

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2058]
In "my programs", Reset is not localized (f.e. in French)

![image](https://user-images.githubusercontent.com/1003685/155119273-5139ee46-e2d6-448b-bdb8-e02505a6ff2c.png)

We have a word for this in the yaml file, so I guess we can grab that?

![image](https://user-images.githubusercontent.com/1003685/155119340-fb3da753-b493-422f-97a5-606d1337ef31.png)

**Comment by Felienne** [comment]
Search does work by the way!

![image](https://user-images.githubusercontent.com/1003685/155119828-45ba50ed-242c-417c-8029-d45960450f2b.png)

**Comment by TiBiBa** [comment]
My bad, will fix it right away!
