### ISSUE TITLE
Mandarin Chinese version

### ISSUE THREAD

**Issue by fpereiro** [Felienne/hedy#207]
- Create branch & add existing translations.
- List missing translations.

**Comment by Felienne** [comment]
Closed by #347!

@Grace666-code The only thing we are now missing is the adventures, but that is missing for a bunch of other languages too. If you want to translate these too, you can do that with our new translation interface, that might be a bit easier?

http://hedy-alpha.herokuapp.com/translate/en/zh

Again thanks a bunch! Once you are at Snellius I will give you some nice Hedy goodies!
