### ISSUE TITLE
[BUG] Copy button overlays Arabic code because it is on the right hand side

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2082]
Copy button overlays Arabic code because it is on the right hand side:

![image](https://user-images.githubusercontent.com/1003685/155477669-24ce053d-59d9-405c-8862-80d85f176e74.png)

Same issue that we had with the language switcher (#2063) so maybe it can be solved in the same way?

**Comment by TiBiBa** [comment]
Will also take a look if we can use a left-handed arrow in this case!
