### ISSUE TITLE
[BUG] the add and remove commands don't get syntax highlighting

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#2084]
(Sorry if this issue already exists)

In level 3 the add to and remove from commands are introduced but they don't turn red. 

taarten is aardbei, chocolade
add appel to taarten
remove chocolade from taarten
print taarten at random

**Comment by Felienne** [comment]
> (Sorry if this issue already exists)

It does, but that one is very imprecise! So this is a perfect start for @thjazi39 to fix!

**Comment by MarleenGilsing** [comment]
Speaking of syntax highlighting... 
In level 6 ask gets no syntax highlighting in this example even though it should.  
antwoord = ask 'Hoeveel is 10 plus 10?'

The = sign also gets no syntax highlighting, but that might be on purpose.

**Comment by Felienne** [comment]
> Speaking of syntax highlighting... In level 6 ask gets no syntax highlighting in this example even though it should. antwoord = ask 'Hoeveel is 10 plus 10?'
> 
> The = sign also gets no syntax highlighting, but that might be on purpose.

That will be fixed very soon, when we merge #1890!

**Comment by thjazi39** [comment]
fix by #2134
