### ISSUE TITLE
[UI idea] Link for one adventure

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2096]
It would be nice if we could make direct link to one adventure, to be used for workshops and for campaigns like de week van het geld.

A link, like hedycode.com/adventure/story would then just link to the Hedy UI, but only with the story tab shown (and level defaults, of course) Somewhere (in the top bar?) 

We might want an extra button to show all adventures (or not, kids could do that by going to Hedy in the top bar?)

@TiBiBa We did have this feature very early when we deployed adventures so maybe there might be some relic code you can use!

**Comment by TiBiBa** [comment]
Love this idea! Do we want to show the adventure for a specific level or do we want tot show the adventure for all levels? Will have to think about how we share this URL, but should be possible!

**Comment by Felienne** [comment]
This is the very old PR that I think had something similar: https://github.com/Felienne/hedy/pull/299

**Comment by Felienne** [comment]
> Love this idea! Do we want to show the adventure for a specific level or do we want tot show the adventure for all levels? Will have to think about how we share this URL, but should be possible!

In my mind, it would show all levels for 1 adventure. So the "go to next" button goes to level 2 with just that adventure shown.

**Comment by Felienne** [comment]
If the adventure has no further steps, the button is now shown.

**Comment by TiBiBa** [comment]
All right, I think this will be quite a big project but should definitely be possible. Will work on it!

**Comment by TiBiBa** [comment]
Will work on this today and try to make a nice implementation!
