### ISSUE TITLE
[BUG] "no such level" is a bit generic 

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2108]
We show "no such level exists" in all cases where the level is not reachable, for various reasons, but this is not always strictly true. 

Two cases come to mind:

**1. Logged in user in a class** 
If I am a logged in user in a class whose teacher hid a level, I get the message that the level does not exist. This is confusing, esp when teachers close levels kids have already seen. Can we change that with a new template saying something like: 

"you are in a class in which this level has been closed"?

**2. Level not translated yet**
If I set the language to Arabic and then navigate to hedy/8/ I also get this message but the real reason is that this level does not exist *in this language*.  Can we change the error with that note? "No such level in your selected language"?

And we want to redirect to En always in that case after a few seconds? Or give the error and a link to the English version with: "Use this to look at the English version instead?" I can make a nice Hedy drawing with different languages :)

**Comment by TiBiBa** [comment]
> We show "no such level exists" in all cases where the level is not reachable, for various reasons, but this is not always strictly true.
> 
> Two cases come to mind:
> 
> **1. Logged in user in a class** If I am a logged in user in a class whose teacher hid a level, I get the message that the level does not exist. This is confusing, esp when teachers close levels kids have already seen. Can we change that with a new template saying something like:
> 
> "you are in a class in which this level has been closed"?
> 
> **2. Level not translated yet** If I set the language to Arabic and then navigate to hedy/8/ I also get this message but the real reason is that this level does not exist _in this language_. Can we change the error with that note? "No such level in your selected language"?
> 
> And we want to redirect to En always in that case after a few seconds? Or give the error and a link to the English version with: "Use this to look at the English version instead?" I can make a nice Hedy drawing with different languages :)

Will fix both situations with a dedicated error message! Was also looking into re-writing the error page structure, so this is a good starting point.
