### ISSUE TITLE
[CHORE] Re-write structure of retrieving loaded programs

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#2117]
Currently when viewing a program we use the same structure as when loading a level. However, we use a somewhat unique way to differentiate between levels and program id's. Namely: `if step and isinstance(step, str) and len(step) > 2:`. It works, but I don't like this structure. It would be nice if we have some dedicated key to make it clear we are looking at a loaded program instead of a level.

**Comment by Felienne** [comment]
Yeah that is a quite ugly hack and I would applaud it is we would get rid of it!
