### ISSUE TITLE
[CONTENT] missing quotation marks in story level 5

### ISSUE THREAD

**Issue by thjazi39** [Felienne/hedy#2129]
Level 5 story

Line 1 and line 4 are missing quotation marks, turning `is ask` into `is` + str, which leads to an incorrect execution of the code.

Furthermore, the syntax highlighting interprets this as `is ask` without quotes, which can mislead children

![image](https://user-images.githubusercontent.com/48509466/156186864-47f2c9db-2181-425f-8ce6-02c2a01b429e.png)

**Comment by Felienne** [comment]
Hi @thjazi39!

These are two separate issues, one for the content (is a relic from when this was not needed, and for @MarleenGilsing) and one about syntax highlighting for you :) (although that will be very hard to get right...!)
