### ISSUE TITLE
[CHORE] Clean-up readme.md

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#2141]
**Description**
Readme.md is a bit out-of-date with the current state of our project. It would be nice to update this with a new screenshot of the Hedy website and we might also want to take a look at the contributing.md file to make sure it is still consistent with our current state. There are also some grammar mistakes "her en der", would be nice to fix these as well.

**Comment by Felienne** [comment]
Haha yeah this is before we even had syntax highlighting at all!! That is like before June 2021!
