### ISSUE TITLE
[BUG] at random is not recognized in french

### ISSUE THREAD

**Issue by thjazi39** [Felienne/hedy#2170]
It seems that the keyword `at random` translated as `au hasard` is not recognized in level 3.

As a result, the code provided in the story 'restaurant' does not work.

![image](https://user-images.githubusercontent.com/48509466/156873279-c27c5a63-4fd4-4ede-a944-464375b5fa16.png)

**Comment by Felienne** [comment]
Hi @thjazi39!

I found the issue, there is a discrepancy in translation! In the coursedata, we have "au"

<img width="201" alt="image" src="https://user-images.githubusercontent.com/1003685/156877338-56239939-9087-4b88-aec0-013a58235daa.png">

But in the grammar, we have "sur":

<img width="265" alt="image" src="https://user-images.githubusercontent.com/1003685/156877357-1d742d65-f695-4f00-b182-6e9c661b954a.png">

Now we translate the examples with option 1 and parse with option 2 which of course does not work! Which one should we choose?

**Comment by thjazi39** [comment]
I think "au" is better than "sur" in "at random" ("au hasard")

I have seen that you can replace random with a number, as in the following code 
```
L is a, b, c
print L at 2
```
but I don't think it is better translated

It seems to me that there is no other use of at in the grammar.

**Comment by Felienne** [comment]
> I think "au" is better than "sur" in "at random" ("au hasard")

Ok! Shall I change at to "au" then in the grammar? You can do it too of course!

> I have seen that you can replace random with a number, as in the following code
> 
> ```
> L is a, b, c
> print L at 2
> ```
> 
> but I don't think it is better translated
> 
> It seems to me that there is no other use of at in the grammar.

Yeah that is sort of an undocumented feature haha (see LEVELS.MD) we are stil in doubt whether we should explain that and if so where, so indeed for now we only use _AT in combination with random.

**Comment by thjazi39** [comment]
It's done !

I also tried to modify them in the grammars-total files, but these files don't seem to be followed

**Comment by Felienne** [comment]
> It's done !
> 
> I also tried to modify them in the grammars-total files, but these files don't seem to be followed

No those are generated! You should use the files in /grammars
