### ISSUE TITLE
[BUG] Check fix #2173

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2174]
When you are back, you will want to see if my hotfix is sensible :)

**Comment by Felienne** [comment]
Ah I already found one issue, we can now longer edit shared programs, but I guess that is a lot less bad that not being able to share so I will leave that as a check for later.

**Comment by TiBiBa** [comment]
> Ah I already found one issue, we can now longer edit shared programs, but I guess that is a lot less bad that not being able to share so I will leave that as a check for later.

Weird! Will take a look today to see if we can solve this easily.

**Comment by TiBiBa** [comment]
> Ah I already found one issue, we can now longer edit shared programs, but I guess that is a lot less bad that not being able to share so I will leave that as a check for later.

I'm not able to re-produce this error? I tried to save a program, share it and then open it again and save it again. This all seems to work fine.

**Comment by Felienne** [comment]
Yeah I know how to reproduce it but it is indeed tricky! Will explain after
I am back from lecturing.

**Comment by TiBiBa** [comment]
> Yeah I know how to reproduce it but it is indeed tricky! Will explain after I am back from lecturing.
> […](#)

All right! I just did some thinking on the issue and it might be best to just re-write the current structure of saving. When using the save button we call the `saveit` function whereas when using the save and share button we call the `share_program` function. I think it would make more sense to use the same function but with an additional boolean called `shared`. Will take a look and I think the issue will solve itself when the code is cleaned-up.

**Comment by Felienne** [comment]
> > Yeah I know how to reproduce it but it is indeed tricky! Will explain after I am back from lecturing.
> > […](#)
> 
> All right! I just did some thinking on the issue and it might be best to just re-write the current structure of saving. When using the save button we call the `saveit` function whereas when using the save and share button we call the `share_program` function. I think it would make more sense to use the same function but with an additional boolean called `shared`. Will take a look and I think the issue will solve itself when the code is cleaned-up.

Yeah I agree! The issue that I ran into was that there were two routes that both use this view, one showing just the program without all the rest and one for the edit mode showing the regular view. In the second one, for reasons I forgot, we only allow teachers of kids to view? So I could not edit a program cause the program I was looking at was made by a kid in a class. I think we want those two routes to use the same auth code? If this is not easy to understand, we can look at it together later in the week!

**Comment by Felienne** [comment]
> > > Yeah I know how to reproduce it but it is indeed tricky! Will explain after I am back from lecturing.
> > > […](#)
> > 
> > 
> > All right! I just did some thinking on the issue and it might be best to just re-write the current structure of saving. When using the save button we call the `saveit` function whereas when using the save and share button we call the `share_program` function. I think it would make more sense to use the same function but with an additional boolean called `shared`. Will take a look and I think the issue will solve itself when the code is cleaned-up.
> 
> Yeah I agree! The issue that I ran into was that there were two routes that both use this view, one showing just the program without all the rest and one for the edit mode showing the regular view. In the second one, for reasons I forgot, we only allow teachers of kids to view? So I could not edit a program cause the program I was looking at was made by a kid in a class. I think we want those two routes to use the same auth code? If this is not easy to understand, we can look at it together later in the week!

And yeah, cleaning up the sharing/saving is a great idea too, but this issue concerned the viewing side of things not the saving side.

**Comment by TiBiBa** [comment]
I just created a PR that cleaned-up and simplified the saving and sharing code. Can you verify that the bug is fixed? I'm currently struggling with some e2e tests, but it should be almost finished. Will put it at "ready to review" when ready.

**Comment by Felienne** [comment]
Yeah I think this is a different issue, but I will look at the PR when it's ready!

**Comment by TiBiBa** [comment]
I'm still a bit confused by this bug. So if I understand correctly the following work flow is expected:

- Everyone can view a shared program
   - And everyone should be able to edit this program and save it for themselves
- Teachers can view all student programs (also the non-shared) onces

But, currently for some reason the shared programs of a student in a class can not be viewed by non-teachers?

**Comment by Felienne** [comment]
Yes that is the expected workflow and I had the impression (did not test very extensively!) that as a teacher I was not able to edit programs by non-students, but I was able to see them, which is confusing. Being able to see and being able to edit should be the same.

**Comment by TiBiBa** [comment]
> Yes that is the expected workflow and I had the impression (did not test very extensively!) that as a teacher I was not able to edit programs by non-students, but I was able to see them, which is confusing. Being able to see and being able to edit should be the same.

All right! I think I understand the issue, will take a look later today to create a fix.
