### ISSUE TITLE
[CONTENT] check NL adventures for translation mistakes

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#2190]
for example: 
![image](https://user-images.githubusercontent.com/80678586/157614105-878ed494-e192-42ee-ad22-962691b94859.png)
level 3

and level 1

**Comment by MarleenGilsing** [comment]
I should also check the level defaults to make sure they look the same each level. with example codes on the right. (level 2 is off ofr example)

**Comment by thjazi39** [comment]
I already have some python scripts that I used to check the use of quotes in Hedy codes,
I can easily adapt it to solve this problem if it can help!
