### ISSUE TITLE
Generate cheat sheets

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2198]
In #2193 we add really nice cheat sheets but they are made manually, wouldn't it be nice if those can be generated from the examples in the yamls for all languages?

**Comment by TiBiBa** [comment]
I think we can create a similar styling dynamically using Tailwind. Where do we want to show / implement these cheat sheets? Are they supposed to be sent as separate documentation to teachers or can we create a dedicated "cheatsheet page" on the website. For the first option I would have to do some research on converting pages to pdf automatically with Python (this should definitely be possible).

**Comment by TiBiBa** [comment]
We are not the only one:

https://stackoverflow.com/questions/62783277/how-can-i-create-a-pdf-file-from-jinja-template-in-flask-question-tagged-pytho

**Comment by Felienne** [comment]
Yeah makes sense that other people want this too! I don't need a PDF perse, we could also just generate a web page that can the printed it that is easier?

**Comment by TiBiBa** [comment]
> Yeah makes sense that other people want this too! I don't need a PDF perse, we could also just generate a web page that can the printed it that is easier?

All right! Will take a look to generate some cheatsheets dynamically (without the menubar etc.). We will have to figure out a good way to return these to users when needed as we already have the cheatsheet button on the program bar. So it might be a bit overload to always show this option.
