### ISSUE TITLE
[BUG] Level 13 example code can't run properly

### ISSUE THREAD

**Issue by fRedelaar** [Felienne/hedy#2199]
**Describe the bug**
In level 13, none of the **example** adventures work. Printing some other Hedy code in the editor still works fine though. 

**Example Hedy code that will not work**
naam = ask 'hoe heet jij?'
leeftijd = ask 'hoe oud ben jij?'
if naam is 'Hedy' and leeftijd is 2
    print 'Jij bent de echte Hedy!'

![image](https://user-images.githubusercontent.com/33595265/157851264-29a20141-f9d3-4c60-933d-a8894aaf9b3f.png)

**What machine and browser I am using**
- Windows 10
- Chrome and Firefox browsers

**Comment by thjazi39** [comment]
Strange, I can't find the error:
![image](https://user-images.githubusercontent.com/48509466/157877692-944795d6-6ea7-4840-871a-c3d20a172405.png)
It's good with the following link: https://hedycode.com/hedy/13#

**Comment by fRedelaar** [comment]
Weird stuff. I can't replicate the bug anymore either..

Issue can be closed then :)
