### ISSUE TITLE
[BUG] Syntax highlighting broken on public profile

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#2214]
**Describe the bug**
The syntax highlighting does not seem to work on the public profiles while the ace editors are correctly rendered. Might have something to-do with the `level` attribute not correctly being set in this case.

**Comment by Felienne** [comment]
Hi @TiBiBa! Fine if you don't fill out the template for simple bugs, but can you then use a blank issue or remove all template text? This is a bit confusing.

**Comment by TiBiBa** [comment]
> 

My bad! Made these last night and forgot to fill them with text. Will fix them!

**Comment by Felienne** [comment]
This does not seem broken for me? (on alpha):

<img width="899" alt="image" src="https://user-images.githubusercontent.com/1003685/158384995-50f80702-75b3-4b7f-a9e7-2125c4ebab11.png">

**Comment by TiBiBa** [comment]
> This does not seem broken for me? (on alpha):
> 
> 
> 
> <img width="899" alt="image" src="https://user-images.githubusercontent.com/1003685/158384995-50f80702-75b3-4b7f-a9e7-2125c4ebab11.png">
> 
> 

No the user-specific public profile. With the url /user/felienne for example.

**Comment by Felienne** [comment]
Ow, I see, here:

<img width="927" alt="image" src="https://user-images.githubusercontent.com/1003685/158385648-5b8999cc-890a-4ee5-a298-e931e7451639.png">
