### ISSUE TITLE
[BUG] Quoted strings cannot contain escaped quotes

### ISSUE THREAD

**Issue by boryanagoncharenko** [Felienne/hedy#2293]
**Describe the bug**
The grammar of level 4 contains the following definition. It clearly expresses the intention to support escaped quotes in quoted strings.
```
quoted_text: (/'((?:[^\\']|\\.)*)'/ -> text
```
However, while preprocessing user input, we double all backslashes:
```
if level >= 3:
    result = result.replace("\\", "\\\\")
```
Effectively, this means that we will never use the escaped quote "feature" of the quoted_text definition. Moreover, we created tests which specifically test this behavior:
```
  def test_print_with_slashes(self):
    code = "print 'Welcome to \\'"
    expected = textwrap.dedent("""\
    print(f'Welcome to \\\\')""")
    output = "Welcome to \\"
    self.multi_level_tester(
      code=code,
      max_level=17,
      expected=expected,
      translate=False  # \\ is not preserved in tests properly at the moment
    )
```

**Paste the Hedy level**
Level 4 and up

**Expected behavior**
It is unclear what the expected behavior of `print 'Welcome to \'` should be. We have the following options:
- keep the current behavior and refactor the grammar. In other words, print a backslash and adapt the grammar so that it does not support escaped quotes.
- produce an error because the quote is escaped and, therefore, there is no closing quote. This change probably requires content changes too.

**Comment by Felienne** [comment]
Hi @boryanagoncharenko! Good catch as always!

I remember that I did this for a reason but I forgot the reason hahaha 😢 I do want to keep the behaviour that we have, aka if you use one \, it should be printed normally, so 

`print 'Welcome to \'` should print **Welcome to \**

At one point, we do want to also teach kids that \ has meaning and can be used to print `'` but of possible, I would say we only give that meaning to \ when it precedes a quote and not in other cases.

(note people are working on the above at the moment: #1834)

**Comment by Felienne** [comment]
> I think the GitHub editor may have made your example a bit unclear. Could you please confirm that you want to keep the current behaviour which means that `print 'Welcome to \'` should result in the following text being printed `Welcome to \`?
> 
> If so, I will close this issue and follow the discussion in #1834

Yes! We don't yet want to explain to kids that \ has special meaning cause that is complex. And kids like to use this to make shapes :)
