### ISSUE TITLE
Translation of recurrent string

### ISSUE THREAD

**Issue by qku** [Felienne/hedy#2307]
Hello,
while translating the adventures into German on weblate, I noticed that the string "# place your code here" appears very often (at least 50 times). That makes sense, since it is often the code shown in the editor at the start. I should be independent of context and could be translated always in the same way.

I tried to use the Glossary function of weblate to make the translation process easier, but it is still very tedious that way. Could there be a better option to translate this recurring string only once?

**Comment by TiBiBa** [comment]
Hi @qku! Awesome that you are helping to make the Hedy adventures available in German. I'm not sure if there is a better way to do this in Weblate. @Mark-Giesen do you have an idea? 

Another solution might be to replace all these strings through git. You can check out this repo, make a new branch and then in your code editor simply use "replace all" on the German adventures YAML. If you make a pull request of these changes we can merge them to main and Weblate will automatically pick this up as well. Might not be the most straight forward solution, but beats manually editing 50 strings. Let me know if you need any help!

**Comment by Mark-Giesen** [comment]
Hi @qku, I saw the work you were doing on Weblate: great job!
There is indeed an option in Weblate to have Weblate translate all equal strings when someone changes one of them. I was a little afraid to turn this on. Some of the "equal" ones might need a slightly different translation in the other context? This example of course is not one of these. If you let me know the translation you'd like it to be, I'll translate all occorences for you after we merged your translations. So for now, you can skip these specific strings.

**Comment by Mark-Giesen** [comment]
A little further investigation shows the option is not (yet) available for us. This is because we use the same id (start_code) for all these strings and this id is used to find the strings to update. So all start code will be replaced if I activate this option. 
We'll take this under consideration when moving to a new method for string translation.

**Comment by qku** [comment]
I just stumbled upon the "Search and replace" feature of weblate. You can find it under "Tools". I am also including a screenshot down below. It does exactly what we were looking for and includes a handy confirmation window where you get the chance to go over all replacements before they are implemented.

<img width="710" alt="Screenshot 2022-03-27 at 17 26 57" src="https://user-images.githubusercontent.com/16756499/160288778-7393e93a-4ff0-4236-9413-1fbe35498119.png">

**Comment by Mark-Giesen** [comment]
Ah, great find. Haven't tried it, so this does an search and replace on the strings, not the ID's of the text.
