### ISSUE TITLE
[WEBLATE] Document that codes between {} should not be translated

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2325]
> Extra question!
> 
> I see there is some keywords in the texts (see pic) should I translate these? Or is these keywords important to keep in english?
> 
> ![image](https://user-images.githubusercontent.com/24886567/160234204-907d3ee5-5416-441c-8832-1b349a4ab3fc.png)
> 
> 

Good question! These should remain **untranslated** as these are used as placeholders for which values are parsed when these strings are used. You will find these in multiple places, escpecially for the level-defaults and adventures and you can recognize them by the curly brackets.

_Originally posted by @TiBiBa in https://github.com/Felienne/hedy/issues/2324#issuecomment-1079659942_

**Comment by Mark-Giesen** [comment]
They are visible by being greyed, translation is still possible though. Translaters wil get an error if they do.

**Comment by TiBiBa** [comment]
I think this is as best as a solution as we create at this point, propose to close this issue.

**Comment by Mark-Giesen** [comment]
Agreed

Outlook voor Android<https://aka.ms/AAb9ysg> downloaden
________________________________

**Comment by Felienne** [comment]
ok!
