### ISSUE TITLE
Error when trying to start a quiz [BUG]

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#2330]
When I try to start a quiz I get an error. This happens at any level. First I go to the "einde" tab and select "Naar de quiz" then I press "Ga naar vraag 1 van de quiz" and I get this error. 

![image](https://user-images.githubusercontent.com/10562903/160292597-bdff5d0a-8666-4fc1-a100-4a01875097b3.png)

**Comment by TiBiBa** [comment]
Will take a look!

**Comment by TiBiBa** [comment]
Hi @OnnoEbbens! Just fixed this in a PR, will hopefully be merged soon!
