### ISSUE TITLE
[BUG] 'Bad input' error when using multiple `if` statements and a single `else` in level 5

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#2339]
When I use more than one `if` statement followed by an `else` I get a `bad input` error in level 5. For example:
```
naam is ask 'hoe heet jij?'
if naam is Hedy print 'leuk'
if naam is Python print 'ook leuk'
else print 'minder leuk!'
```

**Comment by Felienne** [comment]
Ah interessant! Zeg voor nu maar even tegen lln dat ze of de else er achter zetten of steeds ook een else gebruiken

**Comment by erinrshi** [comment]
hi i'd like to pick up this issue!

**Comment by Felienne** [comment]
I think @boryanagoncharenko might be planning work on this one?

**Comment by Felienne** [comment]
> @Felienne alright, also do you know if there's any open backend tasks that I can work on?

What about this one: https://github.com/Felienne/hedy/issues/1919

**Comment by boryanagoncharenko** [comment]
Thanks for pointing out this issue. This is tightly coupled to #2471 

I addressed the 'bad error' problem by making sure quotes are properly escaped and now the program compiles correctly. However, I am afraid the transpiled code is not what you'd expect. In fact I believe this program illustrates an ambiguity in the Hedy language definition.

Most probably the program is meant to be transpiled in the following way:
```
naam = input(f'hoe heet jij?')
if naam == 'Hedy':
  print ('leuk'):
if naam == 'Python':
  print(f'ook leuk')
else:
  print(f'minder leuk!')
```

However, according to the decisions taken in #1721, `if naam is Hedy print 'leuk'` can be interpreted as `if name == "Hedy print 'leuk'"`, if it is followed by a command on a new line. In the program at hand, the command is the second if statement, which is correct. So, the transpiled code becomes:
```
naam = input(f'hoe heet jij?')
if naam == 'Hedy print \'leuk\'':
  if naam == 'Python':
    print(f'ook leuk')
else:
  print(f'minder leuk!')
```
While the above is valid according to the definitions, it will yield very surprising results.

@Felienne Maybe we should revisit the valid syntax definitions in #1721 ? Or do you see another way to approach this?

**Comment by Felienne** [comment]
> @Felienne Maybe we should revisit the valid syntax definitions in #1721 ? Or do you see another way to approach this?

Hi @boryanagoncharenko! I am in favor of transpiling this as you proposed, into 2 separate ifs and not 2 nested ones but it is not clear to me at this point what impact that would have on other programs (incl the decisions made in #1721) but I am open to changing my mind on those!

Do you have bandwidth to dive into making a draft pr or sketch of what this could look like?

**Comment by boryanagoncharenko** [comment]
> Do you have bandwidth to dive into making a draft pr or sketch of what this could look like?

Yes, of course. I will experiment with possible solutions (including changing the rules in #1721 or even not allowing multiple if statements until level 8) and present them here for discussion.

**Comment by boryanagoncharenko** [comment]
After trying multiple approaches which turned to be hard to implement, I thought we could disallow nested if statements until level 8 (see https://github.com/Felienne/hedy/pull/2514). It can be done minimal effort and does not require syntactic changes, meaning that we can keep all of the #1721 rules.

The downside is that it will not allow for more complex programs in levels 5-7. @Felienne what do you think?
Please note that currently nesting if-statements in levels 5-7 will yield a parse error. If we decide this approach is acceptable, I will extend the grammar to include this case and return an error.

**Comment by Felienne** [comment]
Fixed by https://github.com/Felienne/hedy/pull/2514
