### ISSUE TITLE
[SYNTAX HIGHLIGHTING] comment in level 1-3

### ISSUE THREAD

**Issue by thjazi39** [Felienne/hedy#2359]
In the following case there is an inconsistency:
![image](https://user-images.githubusercontent.com/48509466/160643852-8495db58-98bc-441e-9731-9ef741a1de5e.png)

Either the "#" are not escaped, even at levels 1-3, and in this case, the syntax coloring must be modified to take it into account
or the "#" must not be escaped so that children can use them in prints

**Comment by Felienne** [comment]
Ow this is an interesting one @thjazi39.....! I have to think about what the best solution is here

**Comment by Felienne** [comment]
Hi @thjazi39! 

I don't know which PR it was but it seems you took this into account already in highlighting:

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/1003685/180617448-3e937fb5-14d9-4aef-9fac-42cec53577dc.png">
