### ISSUE TITLE
[BUG] level 2 ask error message says that quotation marks are required

### ISSUE THREAD

**Issue by HeladoDeBrownie** [Felienne/hedy#2367]
on [level 2](https://hedycode.com/hedy/2), trying to run a program consisting of `ask a` pops up an error message that states that ask requires quotation marks. however, `x is ask a` works just fine without quotation marks, and if i add the quotation marks (`x is ask 'a'`) then they're interpreted literally. i would expect either the words " and quotation marks" to be left out of the error message, or quotation marks to be required

**Comment by Felienne** [comment]
Ah what a great catch! We are on it
