### ISSUE TITLE
[CONTENT] Hard-coded text in French level 4

### ISSUE THREAD

**Issue by thjazi39** [Felienne/hedy#2392]
the first words should be `print` and `ask` but `impreso` is not the translation of ask!
Moreover, this is not level 5, but 4!

![image](https://user-images.githubusercontent.com/48509466/161053913-34086758-61f3-4d2c-a113-a771e27af8f6.png)

**Comment by Felienne** [comment]
Pretty sure this is a content issue in the yaml file

**Comment by Liz433** [comment]
Hi! I would like to try and tackle this issue, where can I find the yaml file?
