### ISSUE TITLE
[CLEAN UP] Bundle all web related translations in one Weblate component

### ISSUE THREAD

**Issue by Mark-Giesen** [Felienne/hedy#2399]
As young as the use of Weblate is, allready a clean up would be nice. The different webpages have different folders for translatable content. This seemed smart for us, but it's nog very logical for translators. 
Can the website related component be merged into one, at least on the Weblate side of things. If necessary a merge on this repo side could be considered.

**Comment by Mark-Giesen** [comment]
This is not possible unless we make two projects in Weblate, I don't think this is worth it.

**Comment by Felienne** [comment]
@Mark-Giesen You managed to make this work after all!
