### ISSUE TITLE
Ops suggestion: switch to on-demand capacity

### ISSUE THREAD

**Issue by rix0rrr** [Felienne/hedy#241]
Looking at the Dynamo config, I have a couple of recommendations.

## Switch to on-demand capacity

Fairly sure this will save you 99% of your total bill. Right now, tables are all at minimum capacity of 5 IOPS and they're hardly even using that. Check out typical capacity graphs:

<img width="257" alt="image" src="https://user-images.githubusercontent.com/524162/112307129-d91acb80-8ca0-11eb-87fe-7fbdfb8a6af2.png">

All the white area underneath the red line is $$$ down the drain.

Switching to on-demand capacity will also get rid of the 30+ autoscaling CloudWatch alarms, which is also going to save you $0.10 per alarm per month.

**Comment by rix0rrr** [comment]
## Switch to on-demand capacity

Fairly sure this will save you 99% of your total bill. Right now, tables are all at minimum capacity of 5 IOPS and they're hardly even using that. Check out typical capacity graphs:

<img width="257" alt="image" src="https://user-images.githubusercontent.com/524162/112307129-d91acb80-8ca0-11eb-87fe-7fbdfb8a6af2.png">

All the white area underneath the red line is $$$ down the drain.

Switching to on-demand capacity will also get rid of the 30+ autoscaling CloudWatch alarms, which is also going to save you $0.10 per alarm per month.

**Comment by rix0rrr** [comment]
Did this already since it's such low-hanging fruit

**Comment by fpereiro** [comment]
Thank you @rix0rrr !!
