### ISSUE TITLE
[BUG] Level 14: Calculator not running 

### ISSUE THREAD

**Issue by fRedelaar** [Felienne/hedy#2420]
**Describe the bug**
At level 14 the example code for the calculator game will give an error message. It's probably due to the indentation in the YAML file. The line "spel = 'af'```" is the cause of the bug.  

**Paste the Hedy code & level**
```
print 'Raad mijn getal'
getallen = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
getal = getallen at random
spel = 'aan'
for i in range 1 to 10
    if spel == 'aan'
        gok = ask 'Welk getal denk je?'
        if gok > getal
            print 'Lager!'
        if gok < getal
            print 'Hoger!'
        if gok == getal
            print 'Hoera!'
            spel = 'af'```
```

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/33595265/161499102-bc6ec685-7955-4ae5-943f-8295105755b3.png)

**Comment by TiBiBa** [comment]
Weird! We should have some code validation on the adventures to make sure this is not possible, will take a look to make sure that this validation does indeed work.
