### ISSUE TITLE
[SYNTAX HIGHLIGHTER] No more space after keywords needed

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2424]
Since #2413 a space is no longer mandatory between keywords are arguments:

![image](https://user-images.githubusercontent.com/1003685/161514723-5f600bb3-aba7-4576-be70-fda75eea1a30.png)

This needs to be updated in the highlighter

**Comment by thjazi39** [comment]
Does it only concern the space after or also the one before?
```
x is 1, 2, 3
print xat random
```
?

**Comment by Felienne** [comment]
Only after

**Comment by thjazi39** [comment]
And is this just for the print command or all of them?
Likewise, is it just for level 1 or for all levels?

**Comment by Felienne** [comment]
For all commands and all levels (You can read the PR maybe to see the changes in detail: #2413?)

**Comment by jpelay** [comment]
> For all commands and all levels (You can read the PR maybe to see the changes in detail: #2413?)

Hi! no, no for all commands! Currently just for: print, ask, echo, sleep, turn and forward. These are the more function-like commands of Hedy, do you want to me to open an issue regarding relaxation of spaces requirements around other keywords?Y You commented on `is` maybe we can also do that for every keyword and not just this handful?

**Comment by Felienne** [comment]
> Hi! no, no for all commands! Currently just for: print, ask, echo, sleep, turn and forward. These are the more function-like commands of Hedy, do you want to me to open an issue regarding relaxation of spaces requirements around other keywords?

Ah thanks for the clarification!! I think it makes a lot of sense to do this for the function-like keywords, yes!

>  You commented on `is` maybe we can also do that for every keyword and not just this handful?

Not sure if it adds value, we can totally think about it but let's not put too much work in it right now before we know it really helps.

**Comment by thjazi39** [comment]
Ok, so this only concerns the commands mentioned above.

And concerning the levels, it's good for all of them? for example, when `ask` is replaced by `input` we keep the non-necessity of the space after the keyword?
or is it when the `ask` in level 1 is replaced by the `is ask` in level 2 (or later in level 4, with the quotes)?

**Comment by jpelay** [comment]
> Ok, so this only concerns the commands mentioned above.
> 
> And concerning the levels, it's good for all of them? for example, when `ask` is replaced by `input` we keep the non-necessity of the space after the keyword? or is it when the `ask` in level 1 is replaced by the `is ask` in level 2 (or later in level 4, with the quotes)?

Yes, this goes for all levels. And input is followed by a parenthesis, so no, no need of spaces after it.
