### ISSUE TITLE
[BUG] Dynamic syntax highlighting doesn't work on program view page

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#2439]
**Describe the bug**
Currently the dynamic syntax highlighting seems broken on the program view. This might be something related to the `window.State` value set for the keyword language that is used on the front-end to decide on a highlighter. This is actually part of a larger issue:

- How do we highlight syntax for a program that is not in your language?

We have several options, but non are ideal. As currently the language switcher is also shown, enabling the user to translate the viewed program. We might want to remove this as well? We already have a `readonly` boolean parsed, so we can easily say "only show if ..." The following options are feasible for the program view page:

- Show English syntax highlighting (doesn't highlight a program with non-English keywords)
- Show the user keyword language syntax highlighting (actually doesn't make any sense)
- Show the syntax highlighter for the program language
    - **Note: the program language is not always the same as the keyword language used**
    - We have to remove the language selector in this situation as it doesn't make any sense

Really interested in your views on this issue as it is larger than only the syntax highlighting. We currently show all adventures when searching on `/explore`, do we want to limit this to the user language? @Felienne @boryanagoncharenko 

**Add a screenshot (optional)**
![Schermafbeelding 2022-04-05 om 13 24 13](https://user-images.githubusercontent.com/38155424/161744316-7d084da3-7ec3-4bdf-9427-2d7ae394f616.png)

**Expected behavior**
The syntax should be correctly highlighted, we do however have to discuss in which way.

**Comment by Felienne** [comment]
Ah interesting issue @TiBiBa!

> Currently the dynamic syntax highlighting seems broken on the program view. This might be something related to the window.State value set for the keyword language that is used on the front-end to decide on a highlighter. 

Will you look into this part of the issue?

I think as a first fix, I would say let's highlight in En so at least it is not broken. 

As a second fix, I think it is very reasonable to limit the filtering to only programs in the same keyword language as the user has set, do we have that info in the DB currently @boryanagoncharenko (keyword language per program) Of not, we can take the keyword language of the creator of the program although that might not be perfect since users might mix or switch.

**Comment by TiBiBa** [comment]
> Ah interesting issue @TiBiBa!
> 
> > Currently the dynamic syntax highlighting seems broken on the program view. This might be something related to the window.State value set for the keyword language that is used on the front-end to decide on a highlighter.
> 
> Will you look into this part of the issue -> I think as a first fix, I would say let's highlight in En so at least it is not broken.
> 
> As a second fix, I think it is very reasonable to limit the filtering to only programs in the same keyword language as the user has set, do we have that info in the DB currently @boryanagoncharenko (keyword language per program) Of not, we can take the keyword language of the creator of the program although that might not be perfect since users might mix or switch.

I should be more clear: It does already work in English. The translation doesn't work when switching the code to dutch using the keyword switcher. I propose to remove the keyword switcher and use the syntax highlighter of the program language. Then, independent if the creator made the program with English or profile language keywords: the highlighting is always correct.

**Comment by TiBiBa** [comment]
No wait, this problem is actually a bit bigger than only the program view page. The issue also occurs on the `/explore` page as we initialize the syntax highlighting on the keyword language of the current user; not the creator. See the screenshot below for clarification. We might be able to fix this by setting the highlighting language on runtime for each ace editor specific instead of once using the `window.State` value, but that needs to figuring out first.

![Schermafbeelding 2022-04-05 om 15 50 30](https://user-images.githubusercontent.com/38155424/161769298-063fb706-f316-47cd-ac02-192c23640e74.png)
