### ISSUE TITLE
Unclear error when forgetting `print` in a `repeat` statement in level 7

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#2458]
When you forget to use `print` in the `repeat` statement in level 7 the error is unclear. As this happens quite often I think it is good to have a clear error message.

An example would be:

`repeat 3 times 'Hedy is leuk!'`

**Comment by jpelay** [comment]
Hi, this is very interesting and makes a lot of sense! I think we can make a new error message for this quite easily. Thank you for the suggestion!

**Comment by jpelay** [comment]
Thinking about it, maybe we want to also fix these programs? We can add a print before the text. What do you think @Felienne ?

**Comment by OnnoEbbens** [comment]
I am not Felienne but I like the students to fix it themselves. I think the small success when you understand an error and fix it yourself is a big motivation when learning to program.

**Comment by Felienne** [comment]
> I am not Felienne

🤣

**Comment by boryanagoncharenko** [comment]
I was browsing the transpiled programs with repeat commands and indeed often users forget the 'print' keyword. I also noticed they sometimes forget the word 'times', e.g. `repeat 3 print 'Hi!'`. Perhaps it would be easy to add this scenario while addressing the current issue? If not, I can create a separate issue ofc.

**Comment by jpelay** [comment]
> I was browsing the transpiled programs with repeat commands and indeed often users forget the 'print' keyword. I also noticed they sometimes forget the word 'times', e.g. `repeat 3 print 'Hi!'`. Perhaps it would be easy to add this scenario while addressing the current issue? If not, I can create a separate issue ofc.

Hi! Sorry I took this and didn't finish it! I think it can be addressed in the same issue of course. I just need to add that option as an error rule in the grammar, which is the solution I'm pursuing for this one. Also, where can you see the transpiled programs?

**Comment by Felienne** [comment]
> Hi! Sorry I took this and didn't finish it! 

No problem! That excuses me for also replying very late haha!

> I think it can be addressed in the same issue of course. I just need to add that option as an error rule in the grammar, which is the solution I'm pursuing for this one.

Cool!

> Also, where can you see the transpiled programs?

We have no easy way of seeing the transpiled programs (maybe we should...) I usually put a breakpoint here and look at the Python field of result:

https://github.com/Felienne/hedy/blob/857542a4781aad83031b6be37d4ca00685033490/hedy.py#L1990
