### ISSUE TITLE
[Language idea] Adding Turtle colors

### ISSUE THREAD

**Issue by fRedelaar** [Felienne/hedy#2460]
**Language idea incl level**
Today I saw some children coding in Hedy. They especially seemed to love drawing using Turtle! I think adding colors would be a very cool and exciting feature for them. I am not sure which level would be best to introduce the color keyword. 

In Hedy, something like: 
`color red`
could work for example. This would make the line red.

**Sketch of idea in Hedy**
![image](https://user-images.githubusercontent.com/33595265/162010362-a16ca768-1d03-4c0f-b4a2-1d576ed5cae2.png)

**Screenshot of the working Python Turtle code**
![image](https://user-images.githubusercontent.com/33595265/162007794-079185eb-da3c-481b-9cba-df10f5acff93.png)

We could use [turtle.pencolor](https://docs.python.org/3/library/turtle.html#turtle.pencolor)("red") for example. The standard available colors in Turtle are: red, blue, yellow, brown, magenta, cyan, orange, purple, pink, darkblue, darkgreen, and many more. There are many! For now maybe just 3-4 colors will be enough though.

**Comment by fRedelaar** [comment]
I've made a beginning in the [turtle_color](https://github.com/Felienne/hedy/tree/turtle_color) branch.

**Comment by TiBiBa** [comment]
I really like this idea! It does introduce an extra "complexity" to our level. Maybe we can add this as an ongoing adventure? Of course we still have to add this to the syntax and highlighting, but this way we don't have to add it to any specific level and it can be seen as an "extra" option on drawing.

**Comment by fRedelaar** [comment]
Progress on branch: 11 colors possible!

![image](https://user-images.githubusercontent.com/33595265/162160627-8acf658d-0d47-4e03-af28-6ca51bf683bb.png)

**Comment by TiBiBa** [comment]
> Progress on branch: 11 colors possible!
> 
> ![image](https://user-images.githubusercontent.com/33595265/162160627-8acf658d-0d47-4e03-af28-6ca51bf683bb.png)

I do have a question on this, are we able to localize the colors? I can imagine non-english speakers don't know the English colors.

**Comment by fRedelaar** [comment]
@TiBiBa Thanks for the feedback! Dutch (and English) colors work! 🎉 Unfortunately I can't speak many other languages haha. 

![image](https://user-images.githubusercontent.com/33595265/162163730-1828d81e-3d43-42b3-8012-89792ecad2ea.png)

**Comment by fRedelaar** [comment]
Asked a multilinguist friend for some translations in French and Spanish to be used later.
[Colors_FR_ES.txt](https://github.com/Felienne/hedy/files/8441742/Colors_FR_ES.txt)

**Comment by TiBiBa** [comment]
> @TiBiBa Thanks for the feedback! Dutch (and English) colors work! 🎉 Unfortunately I can't speak many other languages haha.
> 
> ![image](https://user-images.githubusercontent.com/33595265/162163730-1828d81e-3d43-42b3-8012-89792ecad2ea.png)

Wow really awesome! Will take a look at your branch later to check it out myself, we do have to think about on which level we want to introduce this coloring. Maybe level 2 or 3?

**Comment by fRedelaar** [comment]
Hmm.. level 2 introduces angles (`hoek is 20`). In level 3 no new `turtle` command is being taught. So maybe introduce `color` in level 3?

**Comment by TiBiBa** [comment]
> Hmm.. level 2 introduces angles (`hoek is 20`). In level 3 no new `turtle` command is being taught. So maybe introduce `color` in level 3?

Sounds good to me! We do have to think about some other stuff before we can merge this:

> Update commands
> Maybe create a new adventure?
> Write dedicated exceptions "this is not a color, you can only choose ..."
