### ISSUE TITLE
[CLEAN-UP] Remove forgotten logs on front-end

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#2467]
**Description**
It seems we forgot some logs on the front-end code somewhere as currently our Javascript console is pretty crowded:
![Schermafbeelding 2022-04-07 om 13 03 57](https://user-images.githubusercontent.com/38155424/162185232-78164bc3-2b56-4c48-90ce-feb3b3e051bd.png)

**Comment by TiBiBa** [comment]
Might have something to do with syntax highlighting debugging? @thjazi39

**Comment by thjazi39** [comment]
Yes, it's an oversight on my part, sorry, I'll fix that right away!
