### ISSUE TITLE
Level 5 removes input field on code change

### ISSUE THREAD

**Issue by onsetsu** [Felienne/hedy#247]
Running the example code already given:

![image](https://user-images.githubusercontent.com/1829825/112519376-9b01d280-8d9a-11eb-8b8b-92c412acab17.png)

then, not entering an input, but instead changing the code results in the following:

![image](https://user-images.githubusercontent.com/1829825/112519441-abb24880-8d9a-11eb-81e1-689acd9829f0.png)

Hitting *run code* leads to the above alert dialog, but the input field is gone, so I'm locked out of the system until a page reload.

**Comment by Felienne** [comment]
I have seen this issue occur with students also but I was never able to pinpoint the exact issue, because sometimes oit does work well. @fpereiro can you look into it?

**Comment by fpereiro** [comment]
@onsetsu great catch, thank you for reporting this! I just submitted a fix, we'll merge it shortly.

**Comment by Felienne** [comment]
Great, this seems to fix the issue!!
