### ISSUE TITLE
Fill ALL_KEYWORD_LANGUAGES automatically

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2485]
Since #2396 we populate ALL_LANGUAGES automatically (which is great!) It would be even nicer if we'd also do that for ALL_KEYWORD_LANGUAGES. Everything that has a grammar file (and maybe also a ts syntax-highlighting file) gets added.

Seems an issue for @Mark-Giesen, but no rush on this of course!

**Comment by Mark-Giesen** [comment]
Maybe it's no longer necessary? If a language is added by Weblate but not yet translated, it defaults en EN. So every language actually has a keyword yaml file, but usually with EN keywords in them. So ALL_KEYWORD_LANGUAGES could perhaps be replaced with ALL_LANGUAGES.
Last week I discovered people can actually add a language per component, we do have to take a look at this assumption, but it might change the perfective on this issue.

**Comment by Felienne** [comment]
> Maybe it's no longer necessary? If a language is added by Weblate but not yet translated, it defaults en EN. So every language actually has a keyword yaml file, but usually with EN keywords in them. So ALL_KEYWORD_LANGUAGES could perhaps be replaced with ALL_LANGUAGES. Last week I discovered people can actually add a language per component, we do have to take a look at this assumption, but it might change the perfective on this issue.

No, there is a subtle difference between having a yaml file (indeed, en if not translated yet) and having a grammar and syntax highlighting file (which only exist when we manually run a script to generate them)

**Comment by Mark-Giesen** [comment]
> No, there is a subtle difference between having a yaml file (indeed, en if not translated yet) and having a grammar and syntax highlighting file (which only exist when we manually run a script to generate them)

Ah, maybe automate that generations as well then? But for now, creating ALL_KEYWORD_LANGUAGES should be easy. I'll have a look.
