### ISSUE TITLE
[BUG] Improve turtle color feedback

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2486]
This is quite minor, so no rush @boryanagoncharenko! 

With the new turtle (#2465), we get a list of colors with []:

<img width="638" alt="image" src="https://user-images.githubusercontent.com/1003685/162578008-2c642883-94ba-465c-9103-587f1c7fa1c9.png">

This is correct but not very pretty, can we make that into something like: "one of these: red, blue...." We must have a mechanism for that already since we can also print "left or right" but I was too lazy to find out where :)

**Comment by Felienne** [comment]
Ow never mind, fixed it myself in https://github.com/Felienne/hedy/pull/2465/commits/bc3cc6dd7143d1c1a244358924bff2df4c486936

**Comment by boryanagoncharenko** [comment]
It seems that this is now resolved, indeed, and already in main. Closing the issue.
