### ISSUE TITLE
Text "Probeer dit" cannot be translated.

### ISSUE THREAD

**Issue by mivalencia** [Felienne/hedy#25]
At the moment the text "Probeer dit" is hardcoded and cannot be translated: 
https://github.com/Felienne/hedy/blob/245edc93f9c19ff74f9a441633a87be1123cdf94/templates/index.html#L18-L19

**Comment by rickbeerendonk** [comment]
Commit 12f9400 fixed #25 (fixed this).

**Comment by Felienne** [comment]
Thanks for pointing this one out, I missed in while translating (I typically look at the Dutch version, oops)
