### ISSUE TITLE
[BUG] Flexibility in the recognition of blanks

### ISSUE THREAD

**Issue by thjazi39** [Felienne/hedy#2502]
Blank characters are not highlighted here ! : (level 4)
![image](https://user-images.githubusercontent.com/48509466/162771224-0f71887a-5dcd-4d77-a5de-cc3243d405dd.png)

Indeed, since they are blanks stuck to a word (either in front or behind) they are considered as classic underscore characters and are not highlighted in pink
In order to solve this case, we should make the rules more flexible by highlighting all the underscore, except those inside a word (in front and behind)
Anyway, I think there are few children who name their variables: `bla_ ` or `_bla` !

On the other hand, when the child types `_bla` the underscore will be highlighted in pink at first, then it will return to the classic coloring as soon as the child types the rest, I don't know if this will be a problem.

Another problem highlighted by this example, where the goal is to insert the quotes, is that while waiting for the quotes to be put by the child, what is inside the quotes is colored (here it is from that is recognized)
If this is a problem, I can open another way to solve this

**Comment by Felienne** [comment]
HI @thjazi39!

This is, I think, fine as it is! `_glued` to a word does not give an empty warning and also should not be highlighted differently.
