### ISSUE TITLE
[CONTENT] Level 4 incorrectly states double quotes are supported in print statements

### ISSUE THREAD

**Issue by boryanagoncharenko** [Felienne/hedy#2522]
**Describe the issue**
At level 4, Hedy supports both single and double quotes, e.g. `print 'Hi'` and `print "Hi"` are valid. However, the end quiz is not updated and currently states that double quotes are not valid.

**Add a screenshot (optional)**
<img width="1255" alt="Screenshot 2022-04-13 at 10 59 25" src="https://user-images.githubusercontent.com/3010723/163131162-f82a2cdf-34ec-4432-839b-0810c6b3f38c.png">

**Expected text**
The end quiz should take double quotes as a correct response.

Maybe we should consider changing the content of level 4 so that double quotes are mentioned as a correct option too? Currently in Hedy, just like in Python, you can print single quotes as long as you surround the text they are in with double quotes and vice versa. Maybe this could be explored further in an adventure?

**Comment by MarleenGilsing** [comment]
I have updated the quizzes in #2472 so once that PR is figured out, this shouldn't be a problem anymore. 

Unless we specifically want to teach the students to use the double quotes. Then I should add it to the level defaults. But I don't think that's desirable/necessary, @Felienne?

**Comment by Felienne** [comment]
> I have updated the quizzes in #2472 so once that PR is figured out, this shouldn't be a problem anymore.

Great!

> Unless we specifically want to teach the students to use the double quotes. Then I should add it to the level defaults. But I don't think that's desirable/necessary, @Felienne?

No I think for now it is fine that we just explain the single quotes (they are easier to type) because otherwise it will be confusing.
