### ISSUE TITLE
Create highlighting (typescript) and Lark files dynamicly per Keyword language

### ISSUE THREAD

**Issue by Mark-Giesen** [Felienne/hedy#2542]
In static\js\syntaxModesRules we have to add a new include and switch branch if a new keyword language is added. A new lark file has to be created aswell. Can we do this in a script during build making this (not often) recurring task an automatic one.

**Comment by thjazi39** [comment]
This issue has been resolved by PR #2527 and PR #2672.
Now the `generate-rules-highlighting.py` file fetches translations directly from all `/content/keywords/<LANG>.yaml` files and generates 2 json files which are read by the `syntaxModesRules.ts` file

So, adding a new language file in keywords directory will generate, after execution of the `build-tools/heroku/generate-typescript` script, the support of the new language.
