### ISSUE TITLE
[CONTENT] Improve quiz yaml

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2571]
I know how they came to be but I am not in love with the way we do quizzes right now. Question have as an answer either code or feedback_option (f.e. in Dutch):

This: 

```
                -   code: "{echo}"
                     feedback: "Met {echo} herhaal je een antwoord..."
```

or

```
                -   option_text: "Haydie"
                     feedback: "Deze is het niet !"
```

This is done because we render code differently from text but it is not so pretty (the keys are very differently names but do the same) and leads to weblate problems when quizzes for different langs have different fields (such as in https://github.com/Felienne/hedy/pull/2472) and I suspect that will be inevitably going forward because in some languages you might want to have special questions related to the language (such as: "what is the meaning of this keyword" which you might not need in En)

I would prefer it if we'd make all answers similar, in a field `answer_option` and add a boolean for whether or not an option is code, as such:

```
                -  answer_option: "{echo}"
                    feedback: "Met {echo} herhaal je een antwoord..."
                    code: true*
```

or

```
                -   answer_option: "Haydie"
                     feedback: "Deze is het niet !"
                     code: false
```

* or whatever a boolean is in yaml, maybe it was yes or no? I am too lazy to look that up rn 

Tagging @Mark-Giesen also because it might impact weblate?

**Comment by Mark-Giesen** [comment]
Would it be possible to have just one tag (f.e. answer_option) and use the MD inline code (` like this `) to indicate code. We do this in adventures, so this might be congruent?

**Comment by TiBiBa** [comment]
> Would it be possible to have just one tag (f.e. answer_option) and use the MD inline code (`like this`) to indicate code. We do this in adventures, so this might be congruent?

This might be a solution but then we move some styling dependencies to the translators. If it's inevitable, such as with inline code snippets on the adventures, I don't think we have a choice. But in this situation I prefer the solution with a code boolean. Of course this value should never be translated so we do have to figure out a way for weblate to always "skip" the code boolean. Another solution is that we write our own quiz interface to fix this, but that's quite complex and weblate works fine for almost all of our translations.
