### ISSUE TITLE
[CONTENT] Replace translated keywords with {keyword}

### ISSUE THREAD

**Issue by Mark-Giesen** [Felienne/hedy#2577]
Languages with translated keywords are sometimes missing the {keyword} parts in translations. Adding these can be done quickly with replace in the Yaml file. But, in languages with different alphabets this might not be the preferred way, because children might not (yet) be able to read the English alphabet. Setting the default keyword language to these languages in the UI, might solve this problem and make the replace a smart thing to do for all languages?

**Comment by Felienne** [comment]
> But, in languages with different alphabets this might not be the preferred way, because children might not (yet) be able to read the English alphabet.

That is no problem, for languages in non-English alphabets, the default setting is the localized dependent one (can be changed in profile), so once the keywords are translated, this change can be made!
