### ISSUE TITLE
[WEBLATE] Language stats are not correct

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2588]
We used to have somewhat correct stats but they are now shown a bit too optimistically: 

![image](https://user-images.githubusercontent.com/1003685/164704162-017034b9-4835-4d4d-991d-44a48846b971.png)

I think due to a Weblate change?

Not high priority but it would be nice if it is shown correctly.

**Comment by Mark-Giesen** [comment]
If in Weblate, you can find a ... menu on the right hand side, choose 'Get help' there. This question is there under the name "Change default pull request message" for Weblate to answer.

**Comment by Mark-Giesen** [comment]
This doesn't seem to happen anymore, Weblate support wanted an live example, which we can't provide at this moment. Close this for now, if it reappears I'll let Weblate know.
