### ISSUE TITLE
[UI idea] Show which langs have keywords

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2618]
We don't really show now in an easy way (for users but also for me as a person that very often gives demos) what languages have keywords, can we make that clear? Maybe in the lang switcher, instead of the whole list, we have two lists, one with and one without keywords? Or something else like a symbol in the list, or maybe an place outside of the list?

**Comment by TiBiBa** [comment]
I just came up with this easy fix, giving the non-supported keyword languages another color:
![Schermafbeelding 2022-04-26 om 17 29 42](https://user-images.githubusercontent.com/38155424/165337123-994a702c-d743-40a8-add0-c632e2a3ca40.png)

I'm not sure what would be a better approach as two separate lists will make the UI more crowded and might be unclear.
