### ISSUE TITLE
Add Spanish translations for levels 4-1 and 8

### ISSUE THREAD

**Issue by fpereiro** [Felienne/hedy#262]
- Code examples for levels 8-13: https://github.com/Felienne/hedy/tree/master/coursedata/level-defaults/en.yaml

**Comment by Felienne** [comment]
@fpereiro I think we can close this?

**Comment by fpereiro** [comment]
> @fpereiro I think we can close this (if yes, please do close it)

There are still a few Spanish translations missing. Should I still close it?

**Comment by Felienne** [comment]
If we miss a few, let's rename the issue to make it more clear what we are
missing.

**Comment by fpereiro** [comment]
@Felienne just reviewed the missing translations & renamed the issue

**Comment by fpereiro** [comment]
Remaining adventures will be translated in #641
