### ISSUE TITLE
[UI] Why do we have two different comma views?

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2622]
I just noticed (while debugging Chinese commas) that our example snippets show a different comma than Ace itself, look:

![image](https://user-images.githubusercontent.com/1003685/165749727-fd5fe3f3-a9d2-4700-822f-9f052fdd6452.png)

It is 
![image](https://user-images.githubusercontent.com/1003685/165749792-93de9062-2911-4930-9838-20990af145c0.png)
 versus
![image](https://user-images.githubusercontent.com/1003685/165749826-30c60819-87f8-4e8a-ad7b-072f05cc35bd.png)

This is purely visual, it seems to be the same ASCII characters (when copy-pasting from above, you get the lower one)

Is that an Ace setting? Can we make it consistent?

**Comment by TiBiBa** [comment]
Weird! Will take a look. I don't think we use any different type of styling, but will try to figure it out.

**Comment by Felienne** [comment]
> Found it! Which one do you prefer? We can easily set one of the fonts as fixed.

I prefer the top one, I think that is most familiar to kids (at least Dutch ones)
