### ISSUE TITLE
[BUG] The ask command doesn't seem to work in level 18

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#2642]
This is confusing. It might be on purpose, because print has changed, so it seems likely ask should change as well? 
It might be better to shut level 18 down for now and launch it when there is a plan/content for it.

**Comment by Felienne** [comment]
> This is confusing. It might be on purpose, because print has changed, so it seems likely ask should change as well? It might be better to shut level 18 down for now and launch it when there is a plan/content for it.

Yes, in level 18, `ask` turns into `input`. But yeah, we should add that to the intro text!
