### ISSUE TITLE
[BUG] Explore boxes not always nicely aligned

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#2661]
**Describe the bug**
With a long username the explore program boxes are not always aligned correctly. This makes me really sad as it looks terrible and should be fixed. See the screenshot below for clarification:

![Schermafbeelding 2022-05-02 om 14 41 49](https://user-images.githubusercontent.com/38155424/166235371-e78c6eb7-71d9-4e87-9ec9-9958bbcf4b4b.png)

**Expected behavior**
Long usernames should be cut short when they don't fit.

**Comment by Felienne** [comment]
> This makes me really sad

😃  Love how much you care about the little things!!
