### ISSUE TITLE
Error message exchanges level numbers

### ISSUE THREAD

**Issue by LauraTSD** [Felienne/hedy#269]
![image](https://user-images.githubusercontent.com/23657961/113315959-2553b480-930e-11eb-916f-20e2cb40d0b1.png)

The error messages is: You wrote code for level 9 on level 8 while it was the other way around. The code was written on level 9 and is correct code for level 8

**Comment by bjorn3** [comment]
Fixed now

![image](https://user-images.githubusercontent.com/17426603/136049671-0af491fd-3a6d-4a94-9133-542c8787e817.png)
