### ISSUE TITLE
[Language idea] add special rule "needs colon"

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2712]
In #2701 we remove a comment that had a nice idea which needs to live in an issue and not in a comment:

```
//TODO: this could be an attribute on the rule that we add in the merger
```

The idea was to have some sort of attribute on a rule in a special grammar form (like we have `+=` and `-=` and `|`) that indicates that the rules should now end in `:`. No rush at all on this, just a way to make the grammars nicer that we can think about (maybe fun for @jpelay)

**Comment by jpelay** [comment]
Hi, sure!!
