### ISSUE TITLE
[UI idea] better class statistics

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2718]
Currently, the classes in the admin UI are sorted by the last login of the teacher, but since we have return customers now, that makes the bit a bit weird (and I have to search for the most recent class). We have info about runs in classes, can we sort the classes by last run in class instead? And maybe add a few more stats to the overview page too (number of runs, programs, programs saved etc)

**Comment by TiBiBa** [comment]
I think this will be computationally very expensive to execute. On the classes table we only keep track of the students in our class, finding the last run would result in iterating over all students in all classes and keeping track of the last run. One solution might be to add a timestamp to our class entry in the db and update it each time a student of the class logs in or saves a program. But this would result in a lot of extra db traffic.

**Comment by Felienne** [comment]
> On the classes table we only keep track of the students in our class, finding the last run would result in iterating over all students in all classes and keeping track of the last run.

But don't we have that info somewhere already? Because I can select a class and see all runs in the stats page (tagging @boryanagoncharenko )

**Comment by TiBiBa** [comment]
We do have a `program-stats` table keeping track of the runs per user per week. I think this one is used for the stats page, but that doesn't contain a last used value somewhere. We can maybe sort the classes by most runs in the last week.

**Comment by Felienne** [comment]
> We can maybe sort the classes by most runs in the last week.

If we have that data, that would be a good way forward!

**Comment by TiBiBa** [comment]
> > We can maybe sort the classes by most runs in the last week.
> 
> 
> 
> If we have that data, that would be a good way forward!

Will implement this!
