### ISSUE TITLE
[BUG] Frequently made mistake is broken in En and Nl

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2750]
**Describe the bug**
Button does not show the text, at least in Nl and En, maybe other languages too?

**Comment by TiBiBa** [comment]
Works fine for me on Alpha. I remember solving this somewhere last week, might not be deployed to beta yet?
![Schermafbeelding 2022-05-16 om 14 45 03](https://user-images.githubusercontent.com/38155424/168595376-63ba63bd-3999-4c74-b5d6-d36d69f88cbc.png)

**Comment by Felienne** [comment]
Ow you might be right, this might be a deployment issue! Will check after my lecture.
