### ISSUE TITLE
[UI idea] Transpose customization field?

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2755]
**Idea**

I was just using the teacher's interface and I find it a bit weird that the adventures are in the vertical dimension since on the website they are horizontal. What about transposing the table?
![image](https://user-images.githubusercontent.com/1003685/168757525-fe928d14-ce23-4361-a90d-d0993f56012d.png)

We could also make the adventure names look a bit more like tabs so it is clearer what we mean?

(Maybe @MarleenGilsing has an opinion on this too?)

**Comment by TiBiBa** [comment]
We do have to re-structure this page when transposing as the adventure title won't fit in one line horizontally. But will take a look if we can make it more similar to the existing adventure tabs view.

**Comment by TiBiBa** [comment]
I'm struggling a bit with how we can improve this UI without making it more complex (adding scrolling etc.). @MarleenGilsing do you have any suggestions?

**Comment by MarleenGilsing** [comment]
Only thing I can think of is maybe cutting the amount of levels in half.  So you could make level 1-10 and you'll have to click for 11-18. This way you could leave the adventures that are only in the higher levels out of the lower levels table and vice versa.

**Comment by Felienne** [comment]
I think that is a good idea Marleen! Would that be possible you think @TiBiBa?

**Comment by TiBiBa** [comment]
I think it would! However, we have to decide on some implementation issues: If levels 11-18 are not shown how to we communicate with the user if they are selected or not? The teacher might expect them to automatically be selected when not shown. Will look into this, but not sure yet how we can make this user-friendly.

**Comment by Felienne** [comment]
> If levels 11-18 are not shown how to we communicate with the user if they are selected or not?

Maybe we want to fold them, close them by default, and allowing a teacher to open them with a button click, like in the stats?

**Comment by Felienne** [comment]
Let's leave this for now! Will test with some teachers before we make more decisions here
