### ISSUE TITLE
[CHORE] Reduce test running time

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2757]
**Describe the issue**
Tests take a long time, partly because snippets are copied over to non-translated languages and thus tested multiple times. 

**Suggested improvement**
While testing the adventure and level default snippets, we could create a set of snippets per level. Only if the snippet we open to test is *not* in the set, we test it. That could save a lot of time for langs that are only translated partly.

**Comment by TiBiBa** [comment]
This is a fun issue! We can especially improve some speed on the adventure snippet testing as well as caching the keywords (something we don't do at this point). Will take a look!

**Comment by Felienne** [comment]
Thanks! This is fun but also superhelpful, since 10 mins to wait on all tests is a bit much!

**Comment by Felienne** [comment]
We could even extract and then pickle all snippets so we don't have to read all the files on test, that would also save a lot. We can then add a boolean to re-extract, or detect when the adventures commands files have changed?

**Comment by TiBiBa** [comment]
I just created a hash table for which we check if the current snippet is already in there, if so: skip for testing. Very curious how much time this will save, will let you know!

**Comment by Felienne** [comment]
Yeah I am curious too! I have thought about this idea for a while already but I never found the time to build it. Happy you are on it!!

**Comment by TiBiBa** [comment]
We managed to the reduce the runtime from around 8 minutes to 7 minutes, but most time-consuming seems to be the `test_level` functionality (4,5 minute of the time). I'm not really familiar with that part of our code base, but it seems we test each example on all previous levels? We should be able to make the real improvement at this part of the code!

**Comment by Felienne** [comment]
Ah pity that it did not help all too much. In the level tester we might be able to optimize a bit too but it remains needed to tests snippets on multiple levels
