### ISSUE TITLE
[BUG] Debug button doesn't align nicely when "edit code" button is shown

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#2775]
**Describe the bug**
On the view program page, when the edit code button is shown the debug button has no margin. Small fix, but would be nice to improve!

**Add a screenshot (optional)**
![Schermafbeelding 2022-05-19 om 10 43 47](https://user-images.githubusercontent.com/38155424/169252175-918f8d7f-252f-44fc-a906-4eccf6fa4898.png)

**Expected behavior**
Make sure there is a small margin between all buttons.

**Comment by fRedelaar** [comment]
Wow, good find @TiBiBa  thank you! I will look into it. 

I've also just noticed that the debugger does not work on this page.. So that is a bug on its own. I will create a new issue.
