### ISSUE TITLE
[BUG] Run buttons remains 'stop button' when copying snippet

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#2778]

**Comment by arjank** [comment]
I would need some info on how to reproduce this issue.

**Comment by TiBiBa** [comment]
My bad, forgot to add a description. The issue was more of a "note to self, don't forget and fix" but I forgot this one. I will shortly describe the bug below:

When running a program the run button is replaced by a stop button until the program is finished (either by finishing running or the user stopping the program). However, when copying a snippet from the adventures into the code editor the current program is terminated and the output is emptied. If the previous program is not finished yet we get a undesirable situation: No program is running, but the stop button is still shown, see the screenshot below:
![Schermafbeelding 2022-06-21 om 21 51 40](https://user-images.githubusercontent.com/38155424/174885980-e6444fb5-4df0-47cb-b7d8-dc8050cf739f.png)
Let me know if you need any help picking up this issue!
