### ISSUE TITLE
[Weblate] Check for valid markdown

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2780]
This is an interesting PR too for you @Mark-Giesen! 

Can we somehow force `##` to have a space after them? Or at least mark them in grey so they don't get changed?

_Originally posted by @Felienne in https://github.com/Felienne/hedy/issues/2771#issuecomment-1130221022_

**Comment by Mark-Giesen** [comment]
Prevention is not really a thing in Weblate, the translators are "the boss".  Greying them is possible though. I'll have a look.

**Comment by Mark-Giesen** [comment]
The're greyed now and therefore violations can be found in Weblate by finding clicking "Failing checks: placeholders" on the language you're translating. This might be enough to close this issue.
