### ISSUE TITLE
[BUG] Arabic numerals cannot be used as list index

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2781]
**Describe the bug**
Arabic numerals cannot be used as list index in level 16:

```
fruit = ['appel', 'banaan', 'kers']
print fruit[١]
```

**Comment by Felienne** [comment]
Be my guest, thanks for making my todo list a lot smaller @ThomasKluiters!

**Comment by ThomasKluiters** [comment]
For the life of me I had been trying to figure out why my fix suddenly didn't do anything anymore, but it appears that the latest main branch already is able to support this behaviour :)

**Comment by Felienne** [comment]
Hmmmm I wonder which PR fixed that but ok, happy it works!
