### ISSUE TITLE
Small issue with symbol + quote

### ISSUE THREAD

**Issue by fpereiro** [Felienne/hedy#279]
A small quirk that happens after merging #275:
`print hello world!`' yields `print hello world! '` (note the space between the exclamation mark and the quote). This happens on levels 1 & 2 and only with the combination symbol + quote. Quote + symbol works fine, as well as normal character + quote. It happens both with single and double quotes.

**Comment by Felienne** [comment]
This is not a vey easy fix and seems a very rare issue so I am not going to pursue it for now.
