### ISSUE TITLE
[BUG] One number can't be printed in level 6

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2794]
**Describe the bug**
We can print 5+5 but not a single 5!

**Paste the Hedy code & level**
`print 5`

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/1003685/169505011-2b5f0ed2-ae89-4103-b405-570d104b600d.png)

**Comment by ThomasKluiters** [comment]
I can have a look at this one!

**Comment by Felienne** [comment]
> I can have a look at this one!

Great, thanks!! Let me know if you need help!
