### ISSUE TITLE
[CLEAN-UP] Make quiz completely dependent on tailwind classes for styling

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#2797]
**Describe the issue**
We currently have some manual written CSS for the quiz styling. This is not necessary as we can achieve the same styling with Tailwind classes. Might also be a good first issue to get familiar with our code base and Tailwind in general!

**Comment by bhlox** [comment]
I would like to work on this issue. But, I am currently having issues with running it locally.

I've followed the instructions with installing it via windows PowerShell. When it comes to running website version locally command, I'm currently encountering issues.

![image](https://user-images.githubusercontent.com/86870447/169963028-bdbbc39c-ac43-47c1-b1ae-f3214d14add4.png)

**Comment by TiBiBa** [comment]
> I would like to work on this issue. But, I am currently having issues with running it locally.
> 
> I've followed the instructions with installing it via windows PowerShell. When it comes to running website version locally command, I'm currently encountering issues.
> 
> ![image](https://user-images.githubusercontent.com/86870447/169963028-bdbbc39c-ac43-47c1-b1ae-f3214d14add4.png)

Awesome, thanks for picking up this issue!  These logs are as expected when the server is running and it seems to be working fine. Did you try navigating to `http://0.0.0.0:8080` in your web browser? You should be able to visit your locally running server there.

**Comment by bhlox** [comment]
Yes I did try to navigate to the URL. But all I get is this page.

![image](https://user-images.githubusercontent.com/86870447/169965657-f431e84b-be6c-42f1-b8f7-250053febc1f.png)

**Comment by TiBiBa** [comment]
> Yes I did try to navigate to the URL. But all I get is this page.
> 
> ![image](https://user-images.githubusercontent.com/86870447/169965657-f431e84b-be6c-42f1-b8f7-250053febc1f.png)

Weird! What IDE are you using? And do you console logs change when trying to reach the page?

**Comment by bhlox** [comment]
Hold on, I manage to solve it. You could put it on the documentation (for newbs like me) That if URL "http://0.0.0.0:8080/" doesn't work, they can do this "http://localhost:8080".

Reference to where i find other issues: https://stackoverflow.com/questions/43547420/python-server-http-0-0-0-08080

anywho, is the issue to be worked on is the quiz.html?

**Comment by TiBiBa** [comment]
> Hold on, I manage to solve it. You could put it on the documentation (for newbs like me) That if URL "http://0.0.0.0:8080/" doesn't work, they can do this "http://localhost:8080".
> 
> Reference to where i find other issues: https://stackoverflow.com/questions/43547420/python-server-http-0-0-0-08080
> 
> anywho, is the issue to be worked on is the quiz.html?

Awesome, nice that you got it working! The issue is related to all quiz related templates. These are all stored in the `/templates/quiz` folder. The issue is that all these templates are partly dependent on the `/css/quiz-css.css` file for styling. Which would like to remove this dependency and make these templates dependent on our Tailwind CSS library, just like all other templates. All specific styling that can't be covered by Tailwind should be stored in `css/additional.css` or `built-tools/heroku/tailwind/styles.css`. 

Let me know if you need any help! The `CONTRIBUTING.md` file has a short explanation on how to work with Tailwind.

**Comment by bhlox** [comment]
Cool. is there a more convenient way of contacting you or messaging you? (e.g. discord, facebook)

**Comment by TiBiBa** [comment]
> Cool. is there a more convenient way of contacting you or messaging you? (e.g. discord, facebook)

We just created a Discord channel to get in touch with contributors. Feel free to message me there or ask any question in the related channels. You can join through this link: https://discord.gg/8yY7dEme9r.

**Comment by Felienne** [comment]
> Hold on, I manage to solve it. You could put it on the documentation (for newbs like me) That if URL "http://0.0.0.0:8080/" doesn't work, they can do this "http://localhost:8080".

That is a good point, @TiBiBa, can you do that or make an issue so we don't forget?
