### ISSUE TITLE
[CONTENT] Period should be a comma in welcome text?

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2804]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/1003685/169982919-90a91d85-c314-41d5-bbaf-1419d4e39c00.png">

(hedy here is the name on the account)

**Comment by TiBiBa** [comment]
> <img width="952" alt="image" src="https://user-images.githubusercontent.com/1003685/169982919-90a91d85-c314-41d5-bbaf-1419d4e39c00.png">
> 
> 
> 
> (hedy here is the name on the account)

I think this issue only occurs locally when the babel is not up-to-date. If I remember correctly the string should be different here, but will take a look!

**Comment by TiBiBa** [comment]
This should automatically be solved once Weblate is up-to-date.
