### ISSUE TITLE
[UI idea] Allow filtering on UI language in /explore

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2813]
**Idea incl level**
Since https://github.com/Felienne/hedy/pull/2808 all programs are shown in the local keywords, awesome! But I think it would be great if we can also filter on the UI language of the creator, cause a program with a lot of Spanish text is still not so very useful to me. Do we have that information? If so, can we add it as a filtering option?

**Comment by TiBiBa** [comment]
We do! We store the user profile on the program when saving (and have always done this) so we should be able to filter on the program language. Will take a look at this!
