### ISSUE TITLE
[BUG] String is invalid variable when on Hindi translations

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#2830]
**Describe the bug**
Also when working on #2828 I found another unique bug where a specific Hindi string is not allowed as a variable, causing the program to crash. The following program is invalid:

```
जानवर है 🦔, 🐿, 🦉, 🦇
प्रिंट वह अब एक जानवर की आवाज सुनता है पर अनियमित
```

However, replacing `जानवर` with `test` seems to fix the issue. As I don't speak Hindi I have no clue what the current name of the variable is, but for some reason it breaks the program.

**Edit**
Google translate just thought me it can roughly be translated to "beast".

**Comment by Felienne** [comment]
I think this might be a content issue? The hi file says (I made the var bold):
```
                    **जानवर** {is} 🦔, 🐿, 🦉, 🦇
                    {print} वह अब एक **जानवर** की आवाज सुनता है {at} {random}
```

So the list variable जानवर does not directly precede the list as required. It is a bit like they say like: `animals select one at random` and not `animals at random` This fixes the issue but maybe then we do not have a proper sentence?

```
                    **जानवर** {is} 🦔, 🐿, 🦉, 🦇
                    {print} वह अब एक की आवाज सुनता है **जानवर** {at} {random}
```

@Rezwin Maybe you know how to make this a sentence where जानवर precedes at random?

**Comment by Rezwin** [comment]
> I think this might be a content issue? The hi file says (I made the var bold):
> 
> ```
>                     **जानवर** {is} 🦔, 🐿, 🦉, 🦇
>                     {print} वह अब एक **जानवर** की आवाज सुनता है {at} {random}
> ```
> 
> So the list variable जानवर does not directly precede the list as required. It is a bit like they say like: `animals select one at random` and not `animals at random`
> 
> I suspect the code below fixes the issue, but maybe then we do not have a proper sentence?
> 
> ```
>                     **जानवर** {is} 🦔, 🐿, 🦉, 🦇
>                     {print} वह अब एक की आवाज सुनता है **जानवर** {at} {random}
> ```
> 
> @Rezwin Maybe you know how to make this a sentence where जानवर precedes at random?

I can certainly have a look.
Thanks.
