### ISSUE TITLE
[Feature] Multiple parson's problems for a level in UI

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2831]
We already support Parson's in a level in the yaml, but we will have to make content and also make it clear in the UI that there are more puzzles to do (and maybe also change the DB storing of tries?) 

Maybe something like in the quiz where there is a question 1, 2 etc.

> As well as changing the structure so we can support multiple parsons adventures per level. 

_Originally posted by @TiBiBa in https://github.com/Felienne/hedy/issues/2761#issuecomment-1131606090_

**Comment by TiBiBa** [comment]
Will work on this after merging #2879 as otherwise it might introduce some ugly merge conflicts later on.

**Comment by TiBiBa** [comment]
Will start working on this in the already existing PR #2874!
