### ISSUE TITLE
[UI] Expand timeout for turtle programs

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2834]
In #1682 we extended the time limit to 20 seconds for the turtle but I am getting reports that might not be long enough for complex drawings (which we will get even more when we finish the dst generation) 

Shall we up the limit for turtle programs by a lot? Since we have the stop button since #2591, kids can't really "program themselves into a corner" because they can always stop execution, so maybe the timeout now is overkill?

**Comment by Felienne** [comment]
> I agree that the timeout should be removed. But we have too look into some front-end memory limit to prevent the earlier stated issue.

Great thanks!!

**Comment by Felienne** [comment]
Hi @TiBiBa!

I changed the title here, can we just remove the timeout for turtle programs? Or maybe even better set it to really long (10 mins?) I understand it is a bit risky but I think it should be ok!

**Comment by TiBiBa** [comment]
Will look into this, this should be very easy to fix.
