### ISSUE TITLE
[UI idea] Less buttons for teachers

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#2837]
I was thinking about the abundance of buttons on the for teachers page and class pages, and I came up with this. 

We could remove the 'visible columns' table. And we could change 'invite students' to 'student settings'. Then student settings can contain: 
- Add students
- Invite students
- Invite link
- Remove student
- Change students password

We could also change the 'rename class' button into a pencil next to the class name and delete class could be a little trashcan. 

Lastly, In customize class we could make the openingdates a dropdown thingy, so it's hidden by default. This could be done for 'other settings' and 'select own adventure' as well, but they aren't in the way that much.

**Comment by TiBiBa** [comment]
Will take a look at this today! Will also close #2244 as it is basically the same issue (but without this nice explanation).

**Comment by MarleenGilsing** [comment]
Oh haha, lekker bezig! ;)
