### ISSUE TITLE
[UI idea] Make a printable list of students userinfo 

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#2843]
It's always great when a website allows me to print out a list of my students' account names and passwords. So at the first lesson I can just print the list, cut it into pieces and hand over the login info to the students (and keep the list for myself somewhere when they inevitably forget their userinfo).

**Comment by TiBiBa** [comment]
> It's always great when a website allows me to print out a list of my students' account names and passwords. So at the first lesson I can just print the list, cut it into pieces and hand over the login info to the students (and keep the list for myself somewhere when they inevitably forget their userinfo).

Unfortunately we are unable to print the passwords as they are stored secured by being hashed and we are unable retrieve the original password. So for example the password `test123` will be stored something like this `e0r8wj234wr`. We are unable to reverse this process for security reasons. The only option would be to print the list at the point of multiple account creation (when the passwords are not hashed yet).

We already help the teacher by enabling them to change the password of their students. Not ideal, but I think from a security perspective the best we can do.

**Comment by MarleenGilsing** [comment]
The only option would be to print the list at the point of multiple accounts creation (when the passwords are not hashed yet).

I think this would be nice too. This will help the students login the first time.

**Comment by TiBiBa** [comment]
> The only option would be to print the list at the point of multiple accounts creation (when the passwords are not hashed yet).
> 
> I think this would be nice too. This will help the students login the first time.

Will take a look to implement this!
