### ISSUE TITLE
[BUG] Microsoft Visual C++ 14.0 or higher not available at URL in CONTRIBUTING.md

### ISSUE THREAD

**Issue by jorisslob** [Felienne/hedy#2854]
**Description**
There is a link in the CONTRIBUTING.md in the section "Run Hedy code on your machine". The link says "download here" and points to the following URL:
http://landinghub.visualstudio.com/visual-cpp-build-tools
If you go to that URL, you reach a 404 page.

**Hedy code & level**
It is about the following line in the CONTRIBUTING.md (line 33)
- install Microsoft Visual C++ 14.0 or higher, which you can [download here](http://landinghub.visualstudio.com/visual-cpp-build-tools)

**Screenshot**
![image](https://user-images.githubusercontent.com/1334788/172144074-6fb10525-68b5-479b-b12a-59d56b1897db.png)

**Expected behavior**
I expect to go to a website where I can download the Microsoft Visual C++ libraries.
I think this might be a good link:
https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist

**Machine and Browser**
- Windows 10

**Comment by TiBiBa** [comment]
Hi @jorisslob! Thanks for pointing this out, will take a look!
