### ISSUE TITLE
[UI idea] Make sure teachers don't lose their costumizations by clicking back to class

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#2866]
On the costumize class page you can click 'go back to class' after filling in the costumizations and all your settings will be lost. 
Ideally the settings would be saved automatically when you go back or otherwise there needs to be a 'are you sure?' message to make sure teachers don't lose their settings.

**Comment by TiBiBa** [comment]
Will take a look into this! I think we can trigger the Browser built-in "You have unsaved changes" method.
