### ISSUE TITLE
[CONTENT] Options for the color command in the turtle

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#2872]
I love the new color feature, @fRedelaar! 
If possible, could you maybe add some more color-related features to the turtle?

For example I would love for these codes to work as well: 

Level 3:
choices is blue, yellow, green
color choices at random

Level 5:
name is ask 'What is your name?'
if name is 'Hedy' color green 
else color red

Maybe it would also make more sense in these situations if the command is `color is red` instead of `color red`.

**Comment by Felienne** [comment]
Fixed by #3051 (thanks @arjank!)
