### ISSUE TITLE
Rename master to main

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#288]
Master has negative connotations for some people so I'd prefer if we use main in the future, but that does involve quite some changes, could you look into that @fpereiro (low prio!)

**Comment by sigmavirus24** [comment]
For what it's worth: https://github.com/github/renaming

**Comment by fpereiro** [comment]
Hi @Felienne . Will do!

Thanks @sigmavirus24 for the resource!

**Comment by fpereiro** [comment]
Hi @Felienne ! I believe I don't have the permissions for renaming the main branch - the option is not available in the branches section of the repo, nor I can access the repo settings.

In the meantime, all mentions to `master` have been renamed in this PR: https://github.com/Felienne/hedy/pull/397

**Comment by fpereiro** [comment]
Done by @Felienne a few days ago.
