### ISSUE TITLE
[BUG] Run grammar generation before tests

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2882]
In https://github.com/Felienne/hedy/pull/2877/commits/d9b928df806a11aa1930abd3e0a0b3902cf02c73 I manually generated the grammars because without that, the tests failed. Can we change our tests script to also always generate the grammars, or we will have this issue each time when someone updates the keywords and also adds content (to optimize, we could also store the hashes of the keyword files and only generate the grammar when there is a change?)

**Comment by TiBiBa** [comment]
Will do! Generating the grammars shouldn't take too long, so we can simply add this before calling the tests. But as we also generate them on-deploy we maybe can optimize this to prevent generating them twice.
