### ISSUE TITLE
[CONTENT] example not used in cheat sheet?

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2904]
#2903 made me realize that we don't really use `example` in the commands yaml's anymore (not in the dropdown cheat sheets), shall we just remove it, or do we plan to use that for the paper cheat sheets?

**Comment by TiBiBa** [comment]
Will take a look on what would be a suitable design choice for the cheatsheets.

**Comment by Felienne** [comment]
Closed by #2903
