### ISSUE TITLE
[BUG] Non-English error text (Arabic) includes the keyword highlighted in English 

### ISSUE THREAD

**Issue by alaaeddin-swidan** [Felienne/hedy#2907]
**Describe the bug**
Working in a non English language (Arabic) and encountering a "Missing Inner Command" error, the error text is in Arabic, but it includes the highlighted keyword in English although the code is written completely in Arabic. 
   

**Paste the Hedy code & level**
For example, executing this code in Level 8 
كرر ٥ مرة
قول "علاء الدين"
generates the following error text: 
يبدو أنك نسيت استخدام أمر برمجي مع الجملة repeat التي استعملتها في السطر رقم 1.

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/7933089/174032636-05660d78-b13a-47df-b708-1197c90ee990.png)

**Expected behavior**
Expected is to have the keyword in the same language used in the command window, in my case Arabic. Alternatively the error text will be: 
يبدو أنك نسيت استخدام أمر برمجي مع الجملة كرر التي استعملتها في السطر رقم 1.

**Comment by TiBiBa** [comment]
I think this is a larger issue where the error messages are not being parsed with the user keyword language. Will look into this!
