### ISSUE TITLE
[CONTENT] Estonian Parsons were overridden

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2921]
In merging the new Parsons structure (#2874) I reverted the Estonian translation (sorry @ElviaSober!) I was a bit too overwhelmed to figure out what the transformation was, but I wanted to merge so other translators did not get into the same problem.

I saved the conflicted file here, so maybe either @ElviaSober or @TiBiBa can try to salvage the texts?

https://www.dropbox.com/s/ydtbxktsi1hrut7/et.yaml?dl=0

**Comment by TiBiBa** [comment]
Will manually merge these back into our new structure, no problem!

**Comment by TiBiBa** [comment]
I will wait with this one until #2938 and #2939 are fixed. This will make it easier to copy the translations as the structure is changing once again.

**Comment by TiBiBa** [comment]
#2939 is merged, will look into this today!
