### ISSUE TITLE
[BUG] Parson's lines always look indented

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2938]
When dragging a line down, it seems they become "indented" or at least we have a lot of space upfront? I think that can be confusing in higher levels?

<img width="507" alt="image" src="https://user-images.githubusercontent.com/1003685/174956205-0e2ccfbf-ab41-407d-87a4-a63d04621e97.png">

**Comment by TiBiBa** [comment]
Will look into this later today!
