### ISSUE TITLE
[BUG] Sometimes quizzes ask kids to match textual output but then the output is also highlighted

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2941]
Output in quizzes should not be highlighted, f.e. in level 8:

<img width="723" alt="image" src="https://user-images.githubusercontent.com/1003685/175010254-3572fc14-01b3-4227-b0bd-6b97e209510b.png">

Can we make a block that is output but not code? If that is hard, I am also ok with changing the content here although it might be hard to communicate to translators what words not to use.

**Comment by TiBiBa** [comment]
This is quite hard as we store the questions block as a code block, on the front-end we look for three quotes and if so, parse to an ace editor. This is actually quite complex so it might be nice to change this anyway. For example by adding an additional boolean: `code: True`. This could simplify our front-end quite a lot.

**Comment by TiBiBa** [comment]
Did some thinking on this and it might be best to adjust the YAML so we don't have to manually verify what type of data we are handling on the front-end. Will make an example and propose this on this issue when done.
