### ISSUE TITLE
[BUG] remove 'convert_numerals: undefined' from variables list

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#2948]
![image](https://user-images.githubusercontent.com/80678586/175284482-bfcba381-4c23-4c27-9a13-c4511cd1993e.png)

We should  remove 'convert_numerals: undefined' from the variables list

**Comment by TiBiBa** [comment]
I think we can add a check to hide variables that have an `undefined` value. Will look into this!
