### ISSUE TITLE
[UI idea - High scores] Show name of country instead of "Your country"

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#2962]
I love https://github.com/Felienne/hedy/pull/2931!

But wouldn't it be nicer if we'd say: "The Netherlands" instead of "Your country"? We have the info for the filter so I guess it is not all too much hassle?

**Comment by TiBiBa** [comment]
We have this info! However we don't have the localized country names, which is already an issue on the signup page. So we can return the country name, but only the English one. Will look into some library to check if we can support localized countries as well.

**Comment by Felienne** [comment]
You would think somewhere on the internet we can find list of localized country names? If not, we could add it to weblate but I use that would be complete to explain "translate this string with your country's name in your language".
