### ISSUE TITLE
[BUG] Last class letter is always bold and capitalized

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#2990]
**Describe the bug**
Very weird bug and we have to look into this what might cause this. It is only a visual issue so not really urgent, but for some reason the last letter of the class name on the class overview page is always capitalized and bold. Also see the screenshot below for clarification.

**Add a screenshot (optional)**
![Schermafbeelding 2022-06-29 om 09 50 22](https://user-images.githubusercontent.com/38155424/176382830-3f932e7d-128e-4774-887c-066c90d2d73e.png)

**Comment by Felienne** [comment]
I can't seem to reproduce this bug on my mac (Chrome or Safari) locally, and I don't see it in alpha either:

![image](https://user-images.githubusercontent.com/1003685/176407145-1b5d8833-8b6b-4d87-b1e7-987fb65fa0f9.png)

Do you see it on alpha?

**Comment by TiBiBa** [comment]
I also have this bug on Alpha, might have something to-do with the last char being a number?
![Schermafbeelding 2022-06-29 om 11 55 24](https://user-images.githubusercontent.com/38155424/176408641-6f9ba7bf-c5dc-499b-867d-87a767f4ee6f.png)
