### ISSUE TITLE
[BUG] Sign up doesn't work

### ISSUE THREAD

**Issue by Mark-Giesen** [Felienne/hedy#3012]
Creating an account doesn't work right. It results in an error, but the account is created.

**Comment by TiBiBa** [comment]
This is a serious (and app breaking) issue. I don't have much time this weekend, but hope to get it fixed tonight.

**Comment by TiBiBa** [comment]
It seems to crash on the email sending functionality. Still a bit unclear to me what the exact cause is but it seems to be a Babel translated issue:
```
  body_html = body_html.format(link='<a href="' + link + '">{link}</a>').format(link=gettext('link'))
KeyError: "_('hedy_logo_alt')"
```

**Comment by TiBiBa** [comment]
Found a fix! Would be great if we can merge and deploy this quickly.
