### ISSUE TITLE
[UI idea] Change "Do you wish to create one?" on landing page

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3042]
Do you want to create a public profile on landing page has no button/action:

<img width="990" alt="image" src="https://user-images.githubusercontent.com/1003685/178095850-fdb5b795-b93c-4fed-91a6-3694382c385b.png">

It feel to me like: "Do you wish to create one?" should be a link or button?

**Comment by TiBiBa** [comment]
This seems to be (another) translation issue as the displayed string should be different here. Will look into this!
