### ISSUE TITLE
Malicious link

### ISSUE THREAD

**Issue by Tazaria** [Felienne/hedy#3044]
Someone uploaded a program with a link to an apparently malicious website. Might be a good idea to block their account

![Screenshot 2022-07-11 134906](https://user-images.githubusercontent.com/47422769/178257812-8c95b55d-d81d-428f-8fb5-1413f5aaf604.png)

**Comment by Tazaria** [comment]
This is the only level in the database from level 18. The account name is anthony_petrusschool

**Comment by TiBiBa** [comment]
I will look into deleting this program. We don't have any protocol or system for deleting programs so we have to perform this manually in the database (which is quite cumbersome). @Felienne might be nice to discuss some type of "spam filter" or back-end admin system to enable us to more easily remove programs.

**Comment by TiBiBa** [comment]
Is this spam filter still something we want to pursue? I'm not sure what would be a good starting point for this, but can look into some documentation on this!

**Comment by Felienne** [comment]
Spam filter seems overkill, but what about a "report" button that sends me an email which then generated a link that I can click to remove the program from the db.

**Comment by TiBiBa** [comment]
> Spam filter seems overkill, but what about a "report" button that sends me an email which then generated a link that I can click to remove the program from the db.

Sounds good! Will look into this, I think it would be best to only implement this on the /explore page.

**Comment by Felienne** [comment]
> I think it would be best to only implement this on the /explore page.

Yes that makes sense for now!

**Comment by TiBiBa** [comment]
Once #3148 is merged this issue can be closed, we will be able to easily remove this program.

**Comment by TiBiBa** [comment]
Closed because the report functionality has been built-in and deployed.
