### ISSUE TITLE
[CONTENT] Level 15 and up, while loop doesn't allow multiple conditions (Lyceo issue)

### ISSUE THREAD

**Issue by Tazaria** [Felienne/hedy#3049]
**Describe the issue**
In level 15 the while loop is introduced, but it doesn't allow the user to use `and` and `or` in the condition. Because they learned these keywords in an earlier level this leads to confusion. No higher level, including level 18, allows it either. This issue came up in the Lyceo Hedy summer camp.

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/47422769/179194697-e621a59a-1696-41c5-b97d-066d12d5295c.png)

**Expected text**
Have the while loop conditions allow `and` and `or` to avoid confusion and keep the learning curve intact. In level 18 it should work anyway as that is supposed to be normal Python.

**Comment by jpelay** [comment]
Hi! Thank you for this catch, it was an easy fix overall :)
