### ISSUE TITLE
[UI idea] Show messages in profile icon

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3068]
When I have a message, it is not clear unless I navigate to messages in my profile. Would it be useful to add a little 1 to my profile icon so it is more clear:

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/1003685/179814164-3426f3f6-a125-4146-9628-d697df82608c.png">

(I vaguely remember we had something like that once?)

**Comment by TiBiBa** [comment]
Indeed! We did support this somewhere last year, but with an implementation that checked the messages on each request.

As we did some clean-up to reduce the amount of db calls we decided to remove this check. We can re-introduce this, but have to think carefully on how many times we want to check for new messages as this can rapidly increase our db calls.

**Comment by Felienne** [comment]
> Indeed! We did support this somewhere last year, but with an implementation that checked the messages on each request.
> 
> As we did some clean-up to reduce the amount of db calls we decided to remove this check. We can re-introduce this, but have to think carefully on how many times we want to check for new messages as this can rapidly increase our db calls.

Ah I see what th problem is! it will be expensive to check each time and on login might not be frequent enough... But maybe we can do it at the very least when a kid clicks their profile (we need to fetch it then anyway to be able to show the messages)

**Comment by Felienne** [comment]
Sounds like a good path forward. I am not sure how often kids log out and in, on a private computer that might not be too often but for the use case of schools we can assume kids log in at the beginning of lessons.
