### ISSUE TITLE
[UI idea] Class page does not refresh after "strafwerk" achievement

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3069]
Ok this is tiny but if you remove a student for the first time you get an achievement but then the page does not refresh and the student remains in view (but is deleted correctly)

**Comment by TiBiBa** [comment]
I can't seem to re-produce this bug and the function call also seems to set correct:

`showAchievements(response.achievement, true, "");`

Where the first argument is the actual achievement, the second a reload boolean and the third a redirect link.
Maybe you pressed the close button on the achievement? In that case the Promise is cancelled and the reload is not executed. I'm not sure what would be the best approach to fix the issue in that case. Maybe always reload on pressing the close button?

**Comment by Felienne** [comment]
> Maybe you pressed the close button on the achievement?

Haha yes, I am impatient :D 

I think reload on closing should be a good fix for busy people :)

**Comment by Felienne** [comment]
> Maybe you pressed the close button on the achievement?

Haha yes, I am impatient :D 

I think reload on closing should be a good fix for busy people :)

**Comment by TiBiBa** [comment]
All right, will add a simply reload() to ensure we are always up-to-date when a user closes the window. Might be nicest to only reload if this was expected beforehand. So will look into how we can keep up the promise thrown to make sure we don't deviate from the expected flow.
