### ISSUE TITLE
[Language] Prevent tests breaking on main with new else keyword

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3070]
Ok here is an interesting bit of process knowledge that we need to document somewhere. Recently, @Mark-Giesen merged a PR (#3035) for which all tests passed, so he did not do anything wrong! However... it broke main. How?

Because... this commit in #3035 translated `else` to Hebrew: https://github.com/Felienne/hedy/pull/3035/commits/1560b109a8d47e99df9c74509c50e23754dd9b06

At that point in time, all is well. But, once we run the deploy script, we regenerate the grammars and suddenly, we start to parse Hebrew examples and that causes an issue (more on the concrete issue later-on, in point 2)

To fix this:

1) We should change https://github.com/Felienne/hedy/blob/main/.github/workflows/unittests.yml so that the `on-deploy.sh` script is ran before the tests run (or at least that `python ../../content/yaml_to_lark_utils.py` runs) so the PR fails, instead of main.

2) So... why does this even break? Because the grammars need magic for else to work!

We need to escape all else keywords here:
https://github.com/Felienne/hedy/blob/12031e693fc0cfcaa7bcba12404dc5330a35d0c3/grammars/level5-Additions.lark#L34

And in a slightly different from here:
https://github.com/Felienne/hedy/blob/12031e693fc0cfcaa7bcba12404dc5330a35d0c3/grammars/level5-Additions.lark#L37

Ideally, we add these additions to the yaml_to_lark_utils script so it goes automatically! But maybe that is not worth in, since we do not add languages all too often and if it breaks on the PR, I can easily fix by hand (as I have been doing for now)

To give more context, a concrete example change of the fix is here: https://github.com/Felienne/hedy/pull/3054/commits/911c02476db30eff76ae66f7da3c7e13cc169efa

**Comment by jpelay** [comment]
Hi, I will start working on this one!
