### ISSUE TITLE
[BUG] Can't use negative numbers

### ISSUE THREAD

**Issue by jpelay** [Felienne/hedy#3072]
**Describe the bug**
We can't use negative numbers in computations: assign it to a variable, use it in conditionals or in expressions.

**Paste the Hedy code & level**
When using in a conditional it says that the dash is not allowed.
```
antwoord is 0
if antwoord is -10
  antwoord is ask 'A number not between -10 and 10'
print 'Goed gedaan!
```
![image](https://user-images.githubusercontent.com/45865185/179883781-bd45b98c-4a6f-4275-a46b-3151e292acb2.png)

When assigning it to a variable it throws Missing Command Exception:
![image](https://user-images.githubusercontent.com/45865185/179884480-19217b9c-44d1-4ef2-9d12-b38725677a44.png)

**Expected behavior**
I think kids should be able to work with negative numbers! We allow them to use floating points numbers, which I think is more complex to understand than negative numbers!

**Comment by Felienne** [comment]
Great catch! I agree we should allow it. It should not be all too hard to change the grammar, because we do already explicitly support it in the turtle:

![image](https://user-images.githubusercontent.com/1003685/179942763-6fbe3eb8-8f53-4ff4-bcbd-b6b9f3bdb76f.png)

**Comment by jpelay** [comment]
Another one I found while working on this: in expressions, if an expressions starts with a dash (-) it won't be parsed, if it comes after a string, it fails because the print thinks you're trying to substract the string from the number.

![image](https://user-images.githubusercontent.com/45865185/180681404-439abff1-128c-408e-91fd-8e937fe19a2a.png)
![image](https://user-images.githubusercontent.com/45865185/180681448-25bc2785-4733-4763-aebc-eed0f161c422.png)

**Comment by jpelay** [comment]
This happens because in level 6 the rules use INT and that rule just parses positive numbers.
