### ISSUE TITLE
Implement teacher backend

### ISSUE THREAD

**Issue by fpereiro** [Felienne/hedy#308]
- Implement a simple backend for teachers.
- Functionality:
   - Allow teachers to create classes and invite other users to them.
   - Allow users to accept an invitation to a class.
   - Once an user is in a class, allow the teacher to see the number of programs, adventure progress and last login of each member of the class.

**Comment by Felienne** [comment]
@fpereiro This is quite a large issue, maybe we can make each bullet into an issue and group them in a project? Trying to be more serious about project management :D

**Comment by fpereiro** [comment]
Hi @Felienne ! I think that, as scoped, we can fit all three inside one issue - I like the conceptual unity of items inside one issue, and don't mind having sub-items, as long as 1) they all are related; 2) take each less than a day's work; 3) and are done by the same person. Would that be OK?

**Comment by Felienne** [comment]
Going to split this up after all so we can have sketches and discussions with each bullet.
