### ISSUE TITLE
[UI idea] Add edit colum to adventures

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3084]
**Idea incl level**
While testing #3066... (guess I never really tested the usability of all the teacher stuff, just that it did not break!)

I also realized the name of the adventure is edit but that is a bit confusing (I clicked view like 5 times forgetting it was not edit) maybe we should add an explicit edit column?

![image](https://user-images.githubusercontent.com/1003685/180171222-b26b9932-dd03-4c7c-ac06-52589e074459.png)

**Comment by TiBiBa** [comment]
Never thought about this either, doesn't look very user-friendly this way indeed. I will fix this with the "edit pencil" and "remove dustbin" to be consistent with UI elements t we use in other places.
