### ISSUE TITLE
Any interest in a Dockerfile for local development?

### ISSUE THREAD

**Issue by lpmi-13** [Felienne/hedy#309]
Some people might be interested in contributing to the html/css/js side of things and not necessarily be confident navigating the virtual environments or python dependencies (they might not even have python installed, I suppose).

A Dockerfile would allow for local development as long as someone has docker installed and running. It's an additional dependency, but removes the need to even worry about the zany world of python versions/dependencies/installation/etc.

I'm ready to submit a PR to add a simple Dockerfile to enable this if it seems like a nice thing to have.

**Comment by Felienne** [comment]
Hi @lpmi-13!

What a lovely idea, if you could provide a Docker file that can indeed help people circumvent installing the Python stuff.

Thanks!

**Comment by fpereiro** [comment]
Hi @lpmi-13 ! That would definitely be useful for people who don't have Python installed but do have Docker. Great idea!

Ideally, the dockerfile should closely follow the official installation instructions (https://github.com/Felienne/hedy/blob/master/CONTRIBUTING.md#run-hedy-code-on-your-machine) so that the Dockerized environment is as close as possible to the standard one.

**Comment by lpmi-13** [comment]
Awesome! I'll take a look at that tonight and raise a PR for comments.

**Comment by lpmi-13** [comment]
PR here https://github.com/Felienne/hedy/pull/316

**Comment by hanjoosten** [comment]
Maybe as an extention to this initiative to move to Docker, it would be nice to have the VS-code integration as well. That way, every developer that uses VS-code (a vast majority of developers seem to use this) uses the same development environment out of the box. Maintaining dev environment gets a lot easier too. See https://code.visualstudio.com/docs/remote/create-dev-container for details.

**Comment by fpereiro** [comment]
Closed by #316
