### ISSUE TITLE
[UI] Language switcher does not fold out anymore

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3109]
Not sure why this happened (I think maybe with the rewriting of the front-end accessibility stuff?) but the language switcher has stopped working, it does not fold out anymore:

<img width="695" alt="image" src="https://user-images.githubusercontent.com/1003685/180972704-841d23d7-049b-4eba-8693-11b8960c9182.png">

There are no errors shown in the developer output in Chrome so I have no hints to why this happens.

**Comment by TiBiBa** [comment]
Weird! Will look into this today!
