### ISSUE TITLE
[BUG] Can't access lists using indices on level 5+

### ISSUE THREAD

**Issue by jpelay** [Felienne/hedy#3110]
**Describe the bug**
Starting from level 5, it is allowed to access a list using an int, but the code rule is not working due to a problem in the function that process the production rule.

**Paste the Hedy code & level**
For example, the following code
```
friend is Hedy, Lola, Frida
x is friend at 2
print x
```
 Gives the following error:
 
![image](https://user-images.githubusercontent.com/45865185/181035308-a39de64e-a4d5-418f-931d-8c0ec81b141d.png)

**Expected behavior**
The code should compile down to a list access

**Comment by jpelay** [comment]
Funnily enough, it works on levels 3 and 4. I think this is due to a rewrite of the `list_access_var` on level 5.

**Comment by arjank** [comment]
Also note that the following code is compiled to the exact same Python code in levels 4 and 5, and works correctly in both versions.

```
friend is Hedy, Lola, Frida
print friend at 2
```

And the line `x is friend at 2` fails in level 5 (and obviously not in level 4).
