### ISSUE TITLE
Strengthen coupling between regular mode and adventure mode

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#313]
To strengthen the coupling between regular mode and adventure mode, it would be great if we could analyze the adventure yaml, gather all the assignments per level, and show them underneath the buttons, where we now have the Uitleg.

Something like this:

![image](https://user-images.githubusercontent.com/1003685/115727804-4004d080-a384-11eb-8d1c-8c83a0b9d581.png)

**Comment by fpereiro** [comment]
I love this idea. I think we can add it into the ongoing Adventure Mode PR.

**Comment by Felienne** [comment]
Cool! Could we do it a bit like this, each associated adventure in a tab?

![IMG_3552](https://user-images.githubusercontent.com/1003685/115764993-7d7a5580-a3a6-11eb-937d-5dde9eb11b6f.jpg)

**Comment by Felienne** [comment]
@fpereiro Just letting you know @rix0rrr is planning to take this up this weekend (so you don't have to get started and can finish the last things in the regular adventure mode (if you are coding at all, no need in the weekend of course)

**Comment by Felienne** [comment]
This can be closed, is already integrated into #299
