### ISSUE TITLE
[BUG] Parsons tab does not have a direct link

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3131]
All tabs have one such as: https://hedycode.com/hedy#next but Parson's done not get one:

![image](https://user-images.githubusercontent.com/1003685/183430998-021bd952-8685-4de8-aac7-0e739d0f8607.png)

(if I click it is still stuck on #next):
 
![image](https://user-images.githubusercontent.com/1003685/183431036-8c46d906-7b85-4f48-bf37-5a87ea13f788.png)

**Comment by TiBiBa** [comment]
I just fixed this in #3132!
