### ISSUE TITLE
[UI idea] Enrich profile with special tags

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3149]
Would be cool if public profiles could have a few extra tags that we can assign in the admin interface:

* Teacher (already present in the database, no change needed)
* Certified teacher (new category that we will be making for people that have followed our Hedy course)
* Admin for the username that is admin (maybe it would be even better if we can have multiple admins?)
* And maybe "distinguished user" that we can give out to very special people for various reason?

These tags would then be shown in the user's profile

**Comment by TiBiBa** [comment]
Love this idea! Will look into this, shouldn't be too hard to store this on the user profile.

**Comment by TiBiBa** [comment]
Will look into this today. Propose to fix this following this convention:
- All teachers automatically receive the "teacher" tag
    - We can either check this on server start (with the risk of not always being up-to-date)
    - Or when loading the public profile page
    - The second option is expensive as we have to make multiple retrievals (on each call!):
        - Get the public profile page
        - Get the user profile
        - Verify if the `is_teacher` value is set
        - Update the public profile 
        
- All other tags can only be set manually by the admin
- This makes it even more relevant to fix #2994.
- Somewhere in the future it might be nice to add tags for specific milestones (x amount of achievements etc.)

**Comment by Felienne** [comment]
Sounds good!

Do you also have a plan for how to address #2994?
