### ISSUE TITLE
[UI idea] Put teachers manual in a separate menu item

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3153]
I think the teachers manual is not very discoverable as we have it now, and the UI with the buttons is very uncommon so the separate parts are also harder to use than could be necessary, and I also plan to make it a bit more extensive with videos.

So could we add it as a second extra menu item, and replace the green buttons with something else (anchors in the page?)

**Comment by Felienne** [comment]
Ow abd then we also want to add a link to (and explanation of) the cheatsheets!

**Comment by TiBiBa** [comment]
Do you mean within the menu bar? I can look into make it a sub option on the profile dropdown. When being a dedicated page we also have a lot more freedom for styling. Will look into this today!

**Comment by Felienne** [comment]
> Do you mean within the menu bar? I can look into make it a sub option on the profile dropdown. 

Yeah where I said menu I meant dropdown menu!

> When being a dedicated page we also have a lot more freedom for styling. Will look into this today!

Exactly!

**Comment by TiBiBa** [comment]
I just made a PoW in a new PR. Still not happy with the styling of the menubar. Will look into some tweaking so we always have a nice UI when having a "sub dropdown item".

**Comment by Felienne** [comment]
Does it need to be a sub-menuitem? We could also just have 2 new items appear for teachers?
