### ISSUE TITLE
[BUG] Program code not shown when opening from /programs page

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#3182]
**Describe the bug**
When switching the keyword language using the new dropdown menu the code editor remains empty; not showing the default adventure code.

**Add a screenshot (optional)**
![Schermafbeelding 2022-08-19 om 11 10 56](https://user-images.githubusercontent.com/38155424/185586311-249cf517-6237-4dcb-929b-9789311ff58f.png)

**Comment by TiBiBa** [comment]
This is actually quite bigger as non of the programs are shown when opening them from the programs page. Independent of being an admin or the author of the program: the editor always stays empty. This a priority bug as it can be very frustrating for users as they can't alter their saved programs.

**Comment by TiBiBa** [comment]
Weird thing is, I'm unable to re-produce this error locally! When following the same flow locally everything works fine, but on Alpha the follow console error is thrown:

![Schermafbeelding 2022-08-26 om 08 57 31](https://user-images.githubusercontent.com/38155424/186841838-3a5d853c-d54e-415a-ba92-950239ae0c10.png)

@Felienne do you have any clue what can cause this?

**Comment by TiBiBa** [comment]
The bug isn't there on Alpha, I assume this has already been solved (?).

**Comment by Felienne** [comment]
Seems fixed on alpha indeed, will deploy so we can see if that fixes it!

**Comment by Felienne** [comment]
Still there :( Does seem to be a Safari specific issue (or at least it is not in Chrome)

**Comment by Felienne** [comment]
> This is actually quite bigger as non of the programs are shown when opening them from the programs page. Independent of being an admin or the author of the program: the editor always stays empty. This a priority bug as it can be very frustrating for users as they can't alter their saved programs.

I have not been able to replicate this in Safari though, only the language switcher issue

**Comment by TiBiBa** [comment]
Weird! I don't know what the issue is here as I'm unable to re-produce this locally. Just checked it out with the newest version of main but nothing seems to be wrong there...

**Comment by Felienne** [comment]
> Weird! I don't know what the issue is here as I'm unable to re-produce this locally. Just checked it out with the newest version of main but nothing seems to be wrong there...

Superweird indeed!
