### ISSUE TITLE
[UI idea] Add username as filter option in /admin/users 

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3195]
Can we add username as a filter in admin/users?

We don't have it now (I am not sure why!) but I often look for users by name. Often (but not always) the email address is similar but it would be nice to explicitly allow usernames too.

<img width="803" alt="image" src="https://user-images.githubusercontent.com/1003685/185851918-2c97bec9-d724-4cec-866c-6eb1cf011aee.png">

**Comment by TiBiBa** [comment]
Sounds good! We do still have the lasting issue that not all users are correctly queried before we fix the long running issue of #2994.
