### ISSUE TITLE
[UI idea] Allow filtering of the programs page on submitted programs

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3196]
Currently in the programs page of a user you can filter for adventure and level, but for teachers it would be really useful if you could also filter on all programs that are submitted.

**Comment by TiBiBa** [comment]
Just so I understand correctly, we want to add the option to the user programs page? Would be a really nice feature if we enable a teacher to set an adventure as an assignment, enabling submission for which the teacher can get an overview of all their students. I know we always said "don't re-create Magister", but still would be nice.

**Comment by Felienne** [comment]
> Just so I understand correctly, we want to add the option to the user programs page?

Yes that seems to me to be the simplest option?

> Would be a really nice feature if we enable a teacher to set an adventure as an assignment, enabling submission for which the teacher can get an overview of all their students. I know we always said "don't re-create Magister", but still would be nice.

I do agree that would be really nice...! But maybe we can do the easy way first and do this in a separate issue/PR in the future?
