### ISSUE TITLE
[CONTENT] Two small textual issues in account page

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3202]
Two times new password:

![image](https://user-images.githubusercontent.com/1003685/186407731-c7b42756-015c-43ff-ae47-35e151073f54.png)

No string for request_teacher_account:

![image](https://user-images.githubusercontent.com/1003685/186408186-5ff2da2e-fa5a-4979-9f68-0ce3e83537f4.png)

**Comment by TiBiBa** [comment]
I think this is due to the merging conflicts chaos with the .po files. Will look into this tomorrow!
