### ISSUE TITLE
[UI idea] Change the icon next to the username to your avatar

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#3204]
@TiBiBa  I've got one last little issue to fix for you! :) 

![image](https://user-images.githubusercontent.com/80678586/186612523-b991e915-8752-46a4-be37-e69f46267777.png)
Can you change the icon next to the usernames into the avatar the users picked?

**Comment by TiBiBa** [comment]
Love this idea! I think this is quite hard as we would have the public profile info present for the user at any place, but will look into this!

**Comment by MarleenGilsing** [comment]
Oh, @Felienne said it would be super easy 😅

**Comment by Felienne** [comment]
> Oh, @Felienne said it would be super easy 😅

Shows what I know 🤣

**Comment by TiBiBa** [comment]
It should indeed be very easy! But we have to be cautious with the amount of database calls we make to prevent redundant server load. Therefore it will be quite a challenge to implement this efficiently, but should definitely be possible!
