### ISSUE TITLE
[CLEAN-UP] Validate that all translations in the .po files still exist

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#3206]
**Describe the issue**
We are missing some translations that went missing due to merging conflicts. We should manually add these again.

**Comment by TiBiBa** [comment]
This should be worked on in the ongoing PR #3205.

**Comment by TiBiBa** [comment]
I think we can close this? All seems to work as expected!

**Comment by Felienne** [comment]
Yes I think we have all of them (en anders horen we het wel haha)
