### ISSUE TITLE
Automatische vertalingen door de browser = suf

### ISSUE THREAD

**Issue by simonepronk** [Felienne/hedy#3208]
Nederlands, Level 3, Quiz. 

Jemig wat suf, mijn browser Edge vertaald automatisch woorden naar het Nederlands, waardoor termen in de lessen zoals add, remove, ad randome vertaald worden. In de quiz worden deze woorden niet vertaald (omdat het daar plaatjes zijn, denk ik) en dan valt dat ineens op. Dit is misschien wel een aandachtspunt voor de leraar om op te letten, maar dus geen bug.

**Comment by simonepronk** [comment]
ook in vraag 3

**Comment by TiBiBa** [comment]
Bedankt voor het melden van dit issue! Het is deels een bug, we kunnen dit namelijk voorkomen. Ik ga er even mee puzzelen, maar als het goed is kunnen we Edge vertellen "blijf van mijn text af, de vertaling klopt al".

**Comment by TiBiBa** [comment]
Note to self, this should fix it:
`<meta name="google" content="notranslate" />`

**Comment by Felienne** [comment]
Ha @simonepronk!

Dit zou nu niet meer moeten gebeuren, althans bij ons is het nu in orde. Kan jij eens kijken of dta bij jou ook is via onze testomgeving:

hedy-alpha.herokuapp.com
