### ISSUE TITLE
[BUG] Going from Parsons to quiz should not show popup

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3239]
**Describe the bug**
When finishing the parsons problems of a level and you want to continue to the end quiz, users are asked if they want to continue without saving. However, there is no save option for the parsons problems? You can click yes but it would be nicer if there was no popup

**Add a screenshot (optional)**
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/1003685/187406026-789d6590-36d6-4e79-8500-8d6ac8dc2ba1.png">

**Comment by TiBiBa** [comment]
Will take a look!
