### ISSUE TITLE
[BUG Scrollbar partly blocks blur button

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3249]
In Edge on Windows, the horizontal scroll bar overlaps the blur button when the line is long:

![image](https://user-images.githubusercontent.com/1003685/187663972-3dba3f78-2275-4ddd-a081-f5286a4471e2.png)

**Comment by TiBiBa** [comment]
Whoops! Easiest solution would be to simply style the blur icon a few pixels higher. Dynamically changing the location of the icon based on the visibility of the scroll bar might be a bit cumbersome.
