### ISSUE TITLE
[BUG] When a program is submitted, the blur button does not show

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3250]
![image](https://user-images.githubusercontent.com/1003685/187665388-abecf52b-76aa-474d-907e-2b8642a5291b.png)

**Comment by TiBiBa** [comment]
The blur button is only shown when on developer's mode. This was a design choice at that time, but we have to be careful to make the code editor not too crowded.

**Comment by Felienne** [comment]
Yes totally fair remark! But I guess for submitted programs the UI is not all too full at the moment
