### ISSUE TITLE
[UI idea] Programmers text screen should remain same size, regardless of print

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3281]
Now the programmer's view has a large text screen when there is no print statement:

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/1003685/190422988-b6f3b58a-c307-4d73-8a8d-f5acdd0b84d3.png">

With one print:
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/1003685/190423834-45a5def5-403f-4755-8665-5dfe77267e3d.png">

I'd prefer the last view always, or (if possible) a size depending on the number of printed lines.

**Comment by arjank** [comment]
I can't reproduce this in Firefox nor in Chromium. The programmer view output window is small when there is no print output.

**Comment by Felienne** [comment]
Yeah you are right, I can't reproduce it either:

<img width="1145" alt="image" src="https://user-images.githubusercontent.com/1003685/198246378-ac1abb1b-63df-47cc-a9b8-04fc51913c52.png">

Guess it is fixed or it was a weird one off?
