### ISSUE TITLE
[BUG] Change Password starts out with "new password" filled

### ISSUE THREAD

**Issue by Mark-Giesen** [Felienne/hedy#3283]
Navigating to Change Password under my account shows (see attachment in Dutch) the new password filled, that should not be the case I assume.

**Expected behavior**
All three boxes should be empth.

**What machine and browser you were using (optional)**
Testes on Brave browser

![passwordchange](https://user-images.githubusercontent.com/28646458/190579353-863a53ce-8467-4317-9e5a-323a864fb34a.jpg)

**Comment by Felienne** [comment]
Ah good catch @Mark-Giesen! I am not sure but I think disabling autocomplete (as we did here for second email address: https://github.com/Felienne/hedy/commit/774fd23c0c6e96bf6a501ae8404e864a9b86da30, note that that second field no longer exists...) might do the trick. Maybe you can take a peak @jpelay?

**Comment by jpelay** [comment]
> Ah good catch @Mark-Giesen! I am not sure but I think disabling autocomplete (as we did here for second email address: [774fd23](https://github.com/Felienne/hedy/commit/774fd23c0c6e96bf6a501ae8404e864a9b86da30), note that that second field no longer exists...) might do the trick. Maybe you can take a peak @jpelay?

Yes of course!!
