### ISSUE TITLE
[BUG] Run Empty code shouldn't count?

### ISSUE THREAD

**Issue by Mark-Giesen** [Felienne/hedy#3290]
**Describe the bug**
Delete all code from the window and press Run. This results in a succesfull execution. You'll get some encouragement (Bravo!) which is OK, but your succesfull counter also increments. Pressing the run button 50 times, will result in a batch! I think this isn't the intended behaviour?

**Expected behavior**
Running "no code" should result in nothing

**Comment by TiBiBa** [comment]
Agree! We should catch this on the `/parse` route or maybe even better: prevent the POST from being made all together on the front-end.
