### ISSUE TITLE
[UI idea] Give option to let quiz score unlock next level in classes

### ISSUE THREAD

**Issue by jpelay** [Felienne/hedy#3298]
**Idea incl level**
This idea was made by user TamaraNotenboom in Hedy's discord:

> Suggestion: it would be really nice if teachers could personalize classes so that the students have to do the end quiz before being able to continue to the next level! Now students tend to go to the next level immediately after the introduction.

It would affect all levels.

**Comment by Felienne** [comment]
Thanks for making the issue @jpelay I rephrased it slightly so it is more clear we are talking about unlocking a level here. We have though about this a lot but I think with the quiz score is a good first step, but let's also think about how it can be made more generic later on.

Challenges/things to consider are:

* What cutoff score do we use? One for everyone (80%?) or does the teacher choose this too?
* How to show to kids why they lack the  "go to level X" button. Add a "take the quiz" button in the same place? Or a button with a modal that shows what is needed to unlock the next level?
* How does that button change if we want to unlock using more criteria?

**Comment by Felienne** [comment]
I'd love for this to be implemented but it will be A BIG PROJECT and will probably need to be split into multiple issues at one point.

**Comment by TiBiBa** [comment]
Will look into this right now!
