### ISSUE TITLE
Error message for new line

### ISSUE THREAD

**Issue by ogoletti** [Felienne/hedy#33]
Error messages should be hidden or at least simplified. (maybe this should be a broader issue, linked to #12 ?)
Empty lines are not valid syntax and throws : 
```
The server couldn't translate this Hedy program to Python.
Unexpected end-of-input. Expected one of: * LETTER * __ANON_1 * __ANON_1 * __ANON_1 * DIGIT * __ANON_1 * __ANON_1 * __ANON_1
```

**Comment by Felienne** [comment]
Empty lines addressed by https://github.com/Felienne/hedy/commit/8d7f424e353629d7b6822793fd2d1b80e718f349

Better error messages is still needed indeed, making a new issue for that.
