### ISSUE TITLE
Unable to type in puzzles solutions[BUG]

### ISSUE THREAD

**Issue by zrcarter** [Felienne/hedy#3306]
**Describe the bug**

**Paste the Hedy code & level**
It is super helpful if we can copy-paste the Hedy code to test, so please paste the code here, and don't forget to tell us what level you were in.

**Add a screenshot (optional)**
Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.

**Expected behavior**

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
- What browser you were using (Chrome, Edge, Safari)

**Comment by zrcarter** [comment]
Unable to use puzzles, cannot type in codes.


When typing I expect the code that is written to show up in the code editior.

Using chromebooks of various brands and Dell laptop (Chrome)

**Comment by TiBiBa** [comment]
I'm not sure I understand the issue correctly. For the drag/drop puzzles you can only create a program by dragging the lines from the adventure explanation into the code editor. The goal is to get them in the correct order.

**Comment by zrcarter** [comment]
LOL, the students showed me that today.  Thanks for you immediate response.
