### ISSUE TITLE
[CONTENT] Add new Hedy paper

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3324]
**Describe the issue**
This paper is new 👏, it needs to be added to the /research folder: https://www.sciencedirect.com/science/article/pii/S2590118422000557

Superboring task but I know I will not get around to it so I am dumping it here

**Comment by martinbeentjes** [comment]
That sounds like an awesome task for a Hedy newbie, awesome start for the weekend 👌🏼
