### ISSUE TITLE
[Language idea] Add 'pressed' for binding keyboard events

### ISSUE THREAD

**Issue by ToniSkulj** [Felienne/hedy#3337]
❗ #3335 has to be completed first, this makes pragmatic testing a lot easier.

It would be nice if the user is able to test if a certain keyboard key has been pressed with the following Hedy syntax:
```python
if pressed is 'a' print 'cool!' else print 'meh'
```
This code has been taken from level 5 (introduction) and adapted, since if statements are necessary the functionality can only be added at level 5 and later. The following Python code would need to be generated (in total):
```python
import pygame as pg
pg.init() 
disp = pg.display.set_mode((711, 300))

while True: 
    for e in pg.event.get():
        if e.type == pg.KEYDOWN:
            if e.key == pg.K_a:
                print('cool!')
            else:
                print('meh')

    pg.display.update()
```
Notice that the generated Python code uses Pygame. 

❗ This is a simplified example, in practice this may result in problems (such as setting the pygame display size)
🏁 the above should give the desired result.

**Comment by maximilionis** [comment]
for now Rik and I have found 2 bugs:
- The turtle is not working anymore. It returns an error stating the following: "name 'int_saver' is assigned to before global declaration"
- The ask keyword now bugs out hedy by not receiving any keyboard input after you run the code.

**Comment by ToniSkulj** [comment]
See #3483
