### ISSUE TITLE
[BUG] Ace has a weird vertical line?

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3340]
**Describe the bug**
If you type this:

`print hello world on a very very very very very very very very very very very very very long line`

and scroll left there is a line across Ace:

<img width="661" alt="image" src="https://user-images.githubusercontent.com/1003685/192770405-a6a2944b-5f6d-4f39-bbc4-93a466bbd9a0.png">

This was a bit confusing to some of my students as they thought they were not allowed to make longer lines (which they are) 

Can we remove this line?

**Comment by Felienne** [comment]
I have seen this issue in both Chrome on macOS and Edge on Windows

**Comment by TiBiBa** [comment]
This should be easy to solve as this can be configured with a built-in Ace function: https://ace.c9.io/api/editor.html#Editor.setShowPrintMargin

Can take a look later today!
