### ISSUE TITLE
[Language idea] Add support for calculations in turtle commands

### ISSUE THREAD

**Issue by boryanagoncharenko** [Felienne/hedy#3345]
**Language idea incl level**
Now that the turtle commands are available for all levels, we should allow them to take more complex parameters such as expressions.

**Additional context**
The following program should work:
```
for counter in range 10 to 100
    turn 100 - counter
    forward counter
```

**Comment by jpelay** [comment]
I like this idea! Shouldn't be too hard, can I take this one, Boryana, or will you work on it?

**Comment by boryanagoncharenko** [comment]
> I like this idea! Shouldn't be too hard, can I take this one, Boryana, or will you work on it?

Apologies for the delay. I have not started working on this, so please feel free to pick it up.
