### ISSUE TITLE
[CONTENT] Sort research papers by year

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3365]
**Describe the issue**
The papers in `/learn-more` appear in a "random" order (the one the file system returns)

<img width="903" alt="image" src="https://user-images.githubusercontent.com/1003685/193330651-b3536ae1-4fb9-454f-8d3e-7782dfb5e1e7.png">

Could we fix this with a sort in `hedy_content.py`:

https://github.com/Felienne/hedy/blob/c4ad47e9b48fc6d8a05f9607ede680b609300f27/hedy_content.py#L64

I guess that also means putting the years before the title so we can sort on that.

**Comment by huyszn** [comment]
Hello @Felienne,

Could I work on this issue for Hacktoberfest?

**Comment by Felienne** [comment]
For sure! Thanks and welcome to Hedy!
