### ISSUE TITLE
[BUG] code after ask not always executed

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#3372]
The last days I often get unexpected errors in level 5 (and probably in level 4 as well) that are hard to reproduce. I think it has something to do with the `ask` command. Code after the `ask` command is not always executed.

When I run this code in level 5:
```
antw is ask' wat kies jij'
if antw is schaar print ' gelijk spel!'
antw2 is '1, 2, 3, 4, 5, 6, 7, 8, 9, 10'
print 'test'
print antw2 at random
```
I get this error:

```

Er ging iets fout bij het uitvoeren van het programma.

name 'antw2' is not defined
```

So it seems as if line 3 is not executed. Although the error is a Python and not a Hedy error. When I change the order of the code to this:
```
antw is ask' wat kies jij'
if antw is schaar print ' gelijk spel!'
print 'test'
antw2 is '1, 2, 3, 4, 5, 6, 7, 8, 9, 10'
print antw2 at random
```
'test' is not printed so line 3 is skipped again.

I encountered this issue in many different ways in the last weeks. Once it seemed to depend on how fast you answer the question if the next code line is executed. In another case it seemed to matter what the answer to the question was. So it is a big mystery to me what is happening here.

**Comment by Felienne** [comment]
Weird!! I will take a look!

**Comment by Felienne** [comment]
ok, the issue here is that in level 5 you may not use `if` without `else`.  This is one of the concessions we have to do to make it "natural language like"

It would be great if @jpelay or @boryanagoncharenko could look into throwing a nice error message for this!

**Comment by eremmel** [comment]
The parser gets confused and accepts the code without the else, but generates internally this code:
```
antw = input(f' wat kies jij')
if antw == 'schaar print \' gelijk spel!\'':
  antw2 = ['\'1', '2', '3', '4', '5', '6', '7', '8', '9', '10\'']
print(f'test')
print(f'{random.choice(antw2)}')

```
So line 3 becomes part of the if statement.
