### ISSUE TITLE
Error message location in the web interface

### ISSUE THREAD

**Issue by ogoletti** [Felienne/hedy#34]
This is more of a UX problem. 
On my screen, the error message appears below the code box, and thus sometimes not visible if there are to many 'Try this' boxes above. So that I didn't figure something was wrong directly without visual feedback. 
To reproduce, type garbage in lesson2 in english then hit 'run code'

**Comment by Felienne** [comment]
Fixed by https://github.com/Felienne/hedy/commit/16d80f55cd7302c73e80c36cb74010fc846414ee
