### ISSUE TITLE
[CONTENT] Remove red text in adventure mode

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3400]
**Describe the issue**
Remove red sentence in adventure more (for example: https://hedy.org/adventure/parrot)

**Add a screenshot (optional)**
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/1003685/195296691-95e060a7-5f64-48ee-a753-f064fc63f104.png">

**Expected text**
Just remove this text, it kids need to go elsewhere, a teacher will tell them.

I am copy-pasting the text here for easy grepping: `You're currently in adventure 'Parrot', click on 'Hedy' to view all adventures.`

**Comment by Lakshayainani** [comment]
@Felienne, may I try resolving this ?

**Comment by Felienne** [comment]
> @Felienne, may I try resolving this ?

Ah sorry @Lakshayainani, in the mean time it has been fixed! Let us know if you want to pick up something else!
