### ISSUE TITLE
[UI idea] error color is unreadable with correct keyword

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3402]
We were tweaking the error color a while back (https://github.com/Felienne/hedy/pull/3031) and this looks nice for a wrong (and thus not highlighted) keyword:

<img width="702" alt="image" src="https://user-images.githubusercontent.com/1003685/195314829-56e42d62-cfb5-4422-a080-27c94c814ab6.png">

But is the error is not in the keyword, the color overlaps with the keyword color:

<img width="708" alt="image" src="https://user-images.githubusercontent.com/1003685/195314646-9aa63d6e-539d-406d-ad55-2e2b4828a3f9.png">

So I guess we need to change the color to be a bit more red? Or orange or whatever looks nice and doesn't clash.

**Comment by TiBiBa** [comment]
I remember tweaking this (a lot) in #3031. Not sure how I missed this in the first run, but indeed needs some improvement. I remember it being a bit darker red as well. So before working on this might be nice to have a definitive idea how we want to display the incorrect error line.

**Comment by Felienne** [comment]
> I remember tweaking this (a lot) in #3031. Not sure how I missed this in the first run, but indeed needs some improvement. I remember it being a bit darker red as well. So before working on this might be nice to have a definitive idea how we want to display the incorrect error line.

I was reading https://github.com/Felienne/hedy/pull/3031 and the yellow you suggested there was very readable, but did not align with the error popup. Maybe we could do the lighter red of the popup?

<img width="682" alt="image" src="https://user-images.githubusercontent.com/1003685/195318629-f2718631-4c51-4ba7-a369-57c9b76ba387.png">

**Comment by TiBiBa** [comment]
The color changing itself is really easy as it is defined in a class in `styles.css` (lines 321-324):
```
.editor-error {
  @apply bg-red-500 absolute;
  z-index: 10; /* Show higher than the active line (which has z-index 2) */
}
```

**Comment by Felienne** [comment]
Ah cool I can probably fix that myself :D

**Comment by Mark-Giesen** [comment]
> What do you think @OnnoEbbens or @Mark-Giesen or @MarleenGilsing? It is important the error line and the error box have the same color?

No, if you want to have something matching, we could color only the linenumber the same red and use something well readable in the line itself.
