### ISSUE TITLE
Add 'UsesPygame' Transformer 

### ISSUE THREAD

**Issue by daandj** [Felienne/hedy#3413]
Add a class analogous to the 'UsesTurtle' class which inherits from Transformer and returns true if pygame specific commands are in the tree. (At this moment only the 'pressed' command.)

Also add a UsesTurtle variable in the HTTP-response that is sent to the browser. So the front-end knows whether to enable pygame.

**Comment by ToniSkulj** [comment]
Closed by commit #[Add has_pygame transformer](https://github.com/Felienne/hedy/commit/6108e4bc165476567a27542f7a708d11625424d4) in branch #[Add has_pygame transformer](https://github.com/Felienne/hedy/commit/6108e4bc165476567a27542f7a708d11625424d4)
