### ISSUE TITLE
[UI, QUIZ] add route for previewing quiz question

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#3422]
**Idea incl level**
Testing the quiz is quite a hassle, cause to preview you have to click through all the questions. Can we make a route (like `/quiz/1`) to navigate to a specific question?

Note that we have this route: 
![image](https://user-images.githubusercontent.com/1003685/196181954-edc1707c-7adc-477d-a586-e81f8d68dbb9.png)

But that is fetching, not rendering, rendering happens with a bit of js magic that I find hard to untangle, here: https://github.com/Felienne/hedy/blob/6c42e7e46476a338f1d488e9e41282ec411b0088/static/js/quiz.ts

Hopefully a front-ender can help me :)

**Comment by TiBiBa** [comment]
I think the easiest approach would be to add a dedicated routing, something like`/preview-question/8/6/`. On this route we can render the `quiz.html` file with the correct file. However, as `quiz.html` is used as an include in our `layout.html` file we would miss some necessary imports. But this shouldn't be too hard to fix.

Alternatively we can use the already existing route `/get-question` by adding an optional parameter like `?preview=true` to know if we should return plain YAML or a rendered html file. This makes it a bit easier so we don't have any duplicate / redundant code. I can take a look!

**Comment by TiBiBa** [comment]
Getting there...

![Schermafbeelding 2022-10-17 om 20 39 56](https://user-images.githubusercontent.com/38155424/196256638-90245ba1-196b-4a16-9abd-6bbbcb33268e.png)
