### ISSUE TITLE
[CONTENT] A Dutch variable name in English example code

### ISSUE THREAD

**Issue by jeremydavis519** [Felienne/hedy#3434]
**Describe the issue**
In Level 2, the English-language Turtle adventure gives the student this code to start with:
```
print Turtle race!
hoek is 90
turn hoek
forward 25
```

"Hoek" is, of course, not an English word, which is sure to confuse monolingual students.

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/14192265/196499579-eb8db772-d3d9-42d9-b93c-13c4c7830971.png)

**Expected text**
Something like the following:
```
print Turtle race!
angle is 90
turn angle
forward 25
```

**Comment by Felienne** [comment]
Ah good catch @jeremydavis519!!
