### ISSUE TITLE
[Language idea] Nested `if` statements at level 5

### ISSUE THREAD

**Issue by jeremydavis519** [Felienne/hedy#3439]
**Language idea incl level**
I would like to be able to do simple nesting of `if` statements in level 5. More specifically, something of this format:
```
if choice is rock if computer_choice is paper print 'you lose!'
```

I don't think it needs to be explicitly taught at this level, but I'd like the parser to allow it.

**Additional context**
When I saw the level-5 example code for the _Rock, paper, scissors_ adventure, I decided to see if I could detect win and loss conditions in addition to ties. Of course, the most natural way to do this would be with boolean operators, but those are, understandably, not available at this level. But I reasoned that nested `if` statements should do the same thing and decided to see if they would work. I can imagine a student who understands the concept sufficiently well trying this out.

When I tried it, I got a pretty misleading error message:
![image](https://user-images.githubusercontent.com/14192265/196520623-dcdb3109-e198-45ba-89a0-7f03246362d2.png)
> #### We can't run your program.
> 
> If you want to check if a variable is equal to multiple words, the words should be surrounded by quotation marks!

What makes it worse is that the syntax highlighter seems to have correctly figured out what I was trying to do. But the parser thinks I'm trying to test against a multi-word string. If the syntax highlighter agreed (by not highlighting the second `if` and `is` on the line), it would be easier to figure out that nesting `if` statements like this isn't allowed.

I think a better solution, if nested `if` statements are deemed too complex, would be to make the parser aware of this possibility and give an error message that says that having multiple `if` statements on one line isn't allowed (yet).

If nested `if` statements are to be allowed, an important bit of complexity is what to do with `else` in a case like this:
```
if choice is rock if computer_choice is paper print 'you lose!' else print 'something else'
```

Since level 5 doesn't have any way to delineate blocks of code, that would be unavoidably ambiguous. I'd suggest just disallowing `else` in such a case, with a clear error message to say why.

**Comment by Felienne** [comment]
Thanks for this issue @jeremydavis519 and for the others you have opened! We are aiming to make Hedy better every day.

Are you also in Discord? That might make it easier for us to chat about issues like this one. I agree with you that it would be nice to have the parser recognise this but it will be very hard, and furthermore, while this might be a reasonable idea for us experts, kids do not really try the nexted ifs on one line (I checked the logs and it is very rare.

The error we have about the multi-word string is most likely the right feedback for similar situations, we could do a substring search there for if but I don't think its worth it. If you want to pick that up specifically, go for it but in this form the issue will not be picked up by us.
