### ISSUE TITLE
[BUG] Drawing commands not in red in higer levels

### ISSUE THREAD

**Issue by qnojansen** [Felienne/hedy#3464]
**Describe the bug**
Turtle drawing commands are now available in more levels. However, the commands are not shown in red in the higer levels.

**Paste the Hedy code & level**
Level 15
hoeken = ask 'Hoeveel hoeken krijgt dit figuur?'
hoek = 360 / hoeken
repeat hoeken times
  forward hoek
  turn hoek

**Add a screenshot (optional)**
See attachment

**Expected behavior**
Commands forward and turn should be shown in red.

![image](https://user-images.githubusercontent.com/116218471/196796168-6c4dc9df-9a27-4e77-a810-264ff546c63a.png)

**Comment by arjank** [comment]
This issue has already been fixed in  #3419 . But that has not yet been deployed to production.
