### ISSUE TITLE
[CONTENT] `header.jpg` is 1.2 MB

### ISSUE THREAD

**Issue by nycdotnet** [Felienne/hedy#3487]
**Describe the issue**
On the main `hedy.org` web site, the header image is 1.2 MB (`static/images/header.jpg`).  This represents a significant portion of the page weight.  This image could be trimmed to a significantly smaller size.

**Expected**
I could PR a web-prepared version in and link to that instead.  Up to you!  Thanks.

**Comment by Felienne** [comment]
What a great catch @nycdotnet! We would very much welcome a PR with a smaller version!

**Comment by nycdotnet** [comment]
OK.  I will do so and may dig into a few other little things.

**Comment by nycdotnet** [comment]
This was fixed by #3491
