### ISSUE TITLE
[BUG] Unclear error message "forgot to use a command" - invalid variable name, Level 2

### ISSUE THREAD

**Issue by LeslieMurphy** [Felienne/hedy#3488]
**Describe the bug**
If the student tries to use an invalid variable name they get "It looks like you forgot to use a command on line xx."

GOOD

```
mynumber is ask  Pick a number?
print You told me mynumber

my_number is ask  Pick another number?
print You also told me my_number
```

BAD

```
my-number is ask  Pick a number?
print You told me my-number
```

BAD

```
my_piggybank$ is ask  How much money is in your piggy bank?
print You told me my_piggybank$
```

**Add a screenshot (optional)**

![image](https://user-images.githubusercontent.com/4464416/197888531-fcf049ff-edfc-40ae-8ac4-5618cbc5fb4d.png)

**Expected behavior**
This is probably a hard thing to fix - no clue where I would start looking in the codebase!  If the parse tree can't resolve a _{variable name} IS xxx_ statement it would need to try a recovery to see if the LH side would be valid if we strip out invalid characters not allowed in the variable name.  If this is feasible then the the error message could be:

"my-number is not allowed as a variable name.  You could try mynumber instead"

I think the parser uses this from level1.lark to determine whether it is a variable token:
`NAME: LETTER_OR_UNDERSCORE LETTER_OR_NUMERAL*
`
Wondering if there other places in hedy where there is code that  can recover from a parse tree issue so as to generate better error messages?

**What machine and browser you were using (optional)**
Windows 10
Edge

**Comment by Felienne** [comment]
Hi @LeslieMurphy! Thanks for the detailed issue but we follow Python var conventions so a trailing $ indeed does not work. We are a platform for kids without programming experience and they don't come up with names like that (I checked the logs even) so yeah, we could improve this error message with a lot of grammar gymnastics (also resulting in slower performance) but it is not worth it for our audience.

**Comment by LeslieMurphy** [comment]
Thanks for reviewing this. It’s great you have logs that capture the real world mistakes that the kids are making!
