### ISSUE TITLE
Problems with `print` syntax in level 2 and/or level 3

### ISSUE THREAD

**Issue by arjenpdevries** [Felienne/hedy#37]
We found a few glitches:
* a space at the end of a line that starts with `print` causes an error
* two variables on a print command works, but not if you put a non-variable (string) in between.

**Comment by arjenpdevries** [comment]
Example of first issue:
![image](https://user-images.githubusercontent.com/642221/77183672-fede2500-6ace-11ea-94cc-3030b2a9b8ea.png)

Second issue I cannot reproduce right now...

_This person likes boats better than cars._

**Comment by arjenpdevries** [comment]
Wait a minute - I can reproduce it, but at level 3, not level 2.
![image](https://user-images.githubusercontent.com/642221/77184105-993e6880-6acf-11ea-941e-20fe5b640cb4.png)

**Comment by arjenpdevries** [comment]
_Naughty impatient kids must have advanced further than I noticed!_

**Comment by arjenpdevries** [comment]
Another `print` that breaks, in level 3:
```
print 'something, something else'
```

**Comment by Felienne** [comment]
All these issues are now resolved by recent grammar changes!
