### ISSUE TITLE
Reserved words: unclear situation (level 2)

### ISSUE THREAD

**Issue by arjenpdevries** [Felienne/hedy#38]
Boys love cars. But car in Dutch is `auto`.
Using `auto` in your program causes errors.

**Comment by arjenpdevries** [comment]
Natuurlijk! Maar dit was een jongen :-)

Misschien zat er toch een ander issue in - ik kan het niet reproduceren nu.

Het was rond 12.45, en het eerste programma had auto en het tweede programma auto vervangen door car - de 1e werkte niet en de 2e wel. Meer info heb ik helaas niet, sorry!

(Oh and should have been in English, apologies!)

**Comment by Felienne** [comment]
Ah tijd helpt, dan ga ik m even opzoeken in de logs. Het kan zijn het dat per ongeluk gefikst is door andere wijzigingen, maar het punt over keywords als variabelen blijft staan als issue (moet ik nog even over nadenken hoe we dat kunnen oplossen)

**Comment by arjenpdevries** [comment]
Toch nog een probleem!

![image](https://user-images.githubusercontent.com/642221/77453252-50e8b880-6df7-11ea-8411-a4c3234c107f.png)

**Comment by Felienne** [comment]
Nou het auto probleem heeft me lang bezig gehouden :)! Dat bleek niks met keywords van toen te hebben maar met Unix line breaks!

![image](https://user-images.githubusercontent.com/1003685/78358485-92295700-75b3-11ea-8891-bad08b6248d2.png)

Dus dat wordt nu een nieuw issue, maar door jouw opmerkingen ondersteunen we nu wel keywords as variabelenaam :)

**Comment by Felienne** [comment]
Fixed by https://github.com/Felienne/hedy/commit/682ac0a738e1fecd4e71eea202ee1541d932fbaf

**Comment by arjenpdevries** [comment]
Wow nice collapse :-) great find too
