### ISSUE TITLE
Runtime specified not supported by Heroku

### ISSUE THREAD

**Issue by lpmi-13** [Felienne/hedy#383]
https://devcenter.heroku.com/articles/python-support#supported-runtimes

the runtime currently listed in `runtime.txt` (3.9.2) isn't supported by Heroku, meaning the application is currently running on 3.9.5 (the default). So we should either remove the file, or specify 3.9.5 (recommended option, so it doesn't surprise us when Heroku upgrades).

**Comment by fpereiro** [comment]
@lpmi-13 will take a look!

**Comment by fpereiro** [comment]
@lpmi-13 fixed by https://github.com/Felienne/hedy/commit/b23533ee91c23f3e189d8b39c4092e0aeff331b2 . Thanks for pointing it out!
