### ISSUE TITLE
Explain that printing also works with variables

### ISSUE THREAD

**Issue by omedtjeee** [Felienne/hedy#392]
It would be nice to make the students more clear that you can print variables with the
instruction "print". At the moment it is not clear for the student until level 8.
The first example of printing a variable is currently in level 8.

**Comment by Felienne** [comment]
Hi @MarleenGilsing!

I think this is still true, can we show this to kids earlier in a description or adventure?

**Comment by MarleenGilsing** [comment]
@Felienne Would this be solved with the new level 2 and 3? I don't really understand the problem?

**Comment by Felienne** [comment]
I think the issue was that we never showed code like this:

```
name is Marleen
print name
```

It was always in combination with text, like:

```
name is Marleen
print hallo name
```

But maybe we already show this now (and also maybe it is not all that important? have see ween kids confused by this?)

**Comment by Felienne** [comment]
Browsed the content a bit and I think it is fine as it is, we do show this here and there.
