### ISSUE TITLE
Central place to deal with security headers

### ISSUE THREAD

**Issue by lpmi-13** [Felienne/hedy#415]
Starting this issue just for visibility. I'm about halfway through with a PR to demo an implementation using https://github.com/GoogleCloudPlatform/flask-talisman (and possibly also https://github.com/maxcountryman/flask-seasurf, but can open a separate PR for that if preferred).

The main thing that needs tweaking from the default is the Content Security Policy, and it's a bit fiddly.

I'm also poking around to understand a bit better how we're using cookies in the application.

Anyway, still actively working on this, just taking a bit longer than originally expected.

**Comment by Felienne** [comment]
Thanks for the update @lpmi-13

**Comment by fpereiro** [comment]
Hi @lpmi-13 . It is much appreciated. Thank you for the update! No hurries at all.

FYI, in `auth.py` we set cookies only on two places (on signup and login), in case you want to see how we use the auth cookies.

**Comment by fpereiro** [comment]
@lpmi-13 this has been closed by #488. Let me know if it's not and I'll re-open!
