### ISSUE TITLE
Can only use one elif

### ISSUE THREAD

**Issue by LauraTSD** [Felienne/hedy#431]
Noticed when testing and showing Hedy that only one elif can be used at a time. Occured level 9 and on.
Test that failed:
![image](https://user-images.githubusercontent.com/23657961/119038821-df34dc00-b9b3-11eb-9aa9-75c15c483cb6.png)
Error message:
![image](https://user-images.githubusercontent.com/23657961/119038771-cc220c00-b9b3-11eb-8695-d8bd438270e3.png)

**Comment by LauraTSD** [comment]
This issue has been fixed by: Fix for the elifs #432 Still needs to be reviewed, can close issue when review is done

**Comment by Felienne** [comment]
closed by #432
