### ISSUE TITLE
Level 13 first example line 1 error

### ISSUE THREAD

**Issue by Princekrampah** [Felienne/hedy#435]
if 5+3 == 8:
    print('5+3 ni sawa sawa na 8')
else:
  print('Hii hayitachapishwa kwasababu 5+3 ni 8!')

This seems to be correct to me but, i get an error when ever i run this line of code. Can't seem to understand the course of the error.

**Comment by Felienne** [comment]
Hi @Princekrampah,

The issue is in the calculations within the condition (*5+3* == 8) We don't support that yet at this level. We also don't have == yet. This will work:

```
answer is 5+3
if answer is 8:
    print('5+3 ni sawa sawa na 8')
else:
    print('Hii hayitachapishwa kwasababu 5+3 ni 8!')
```

**Comment by Princekrampah** [comment]
Hey Felienne,

Thanks, guess am used to Python syntax😅. Should I make these changes and
commit again?

**Comment by Felienne** [comment]
Is this program in your translation? Then yes it is best if you change it!

**Comment by Princekrampah** [comment]
I'll do that by tomorrow.

**Comment by Felienne** [comment]
Great thanks!!
