### ISSUE TITLE
level 10 error

### ISSUE THREAD

**Issue by Princekrampah** [Felienne/hedy#437]
colour is blue
colourtwo is yellow
if colour is blue:
    if colourtwo is yellow:
        print 'Together we make green!'

The above hedy code results in an error. Any solution to this error?

All indentations are as they should be

**Comment by Felienne** [comment]
Hi @Princekrampah!

For me this works:

![image](https://user-images.githubusercontent.com/1003685/119234647-50e56500-bb2f-11eb-82cb-321ef1cc2f37.png)

Also if you are submitting code in an issue, you can use the <> button in GitHub to make it look like code, incl the indentation. That can be handy so I can copy-paste the code into Hedy.

Felienne

**Comment by Princekrampah** [comment]
Oh okay, I'll include the code properly next time. Guess it's an issue on
my end. Thanks
