### ISSUE TITLE
is does not work for string equality? (level 4)

### ISSUE THREAD

**Issue by arjenpdevries** [Felienne/hedy#45]
At level 4 using this program:
```
g is kop,munt
m is g at random
n is ask Kop of munt?
print 'Jij koos ' n
if n is m print 'Ja het is ' m else print 'nee ik had ' m
```
`n is m` never evaluates to true, whether I type the correct value or not.

**Comment by arjenpdevries** [comment]
If I enter `m` as value, then it does evaluate to true...

**Comment by Felienne** [comment]
Ah interesting find! Forgot to do the variable replace magic in the 'is' command. Will try to fix this soon (it should not be hard)

**Comment by arjenpdevries** [comment]
Fantastic service again!
