### ISSUE TITLE
Parse request without session cookie leads to a server error

### ISSUE THREAD

**Issue by rix0rrr** [Felienne/hedy#464]
A request to `/parse` without a `session` cookie leads to an error reply on Alpha right now:

```
$ curl 'https://hedy-alpha.herokuapp.com/parse' \
      -H 'Content-Type: application/json' \
      --data-raw '{"level":"1","code":"print hallo wereld\u0021","lang":"nl"}' \
      --compressed
```

Leads to the following response:

```
<h1>500 Internal Server Error</h1>
```

Additional of a cookie header behaves as intended:

```
$ curl 'https://hedy-alpha.herokuapp.com/parse' \
            -H 'Content-Type: application/json' \
            -H 'Cookie: session=.eJwlzEEKgCAQBdC7_LVBmEp6GRlzBGFKUGoT3b2g_ePd2FpmhOMUUeDeW4_CFwvCrDB4jNqOWDMC3OptmotzpMlos6zJ-GS5kObkyBd8vu5VqMf_xITnBe3nHmY.YLtnUA.CIQ4ghMSVtY1PFm7Ura6m51SorQ' \
            --data-raw '{"level":"1","code":"print hallo wereld\u0021","lang":"nl"}' \
            --compressed

{"Code":"# coding=utf8\nimport random\nprint('hallo wereld!')","prev_feedback_level":0,"prev_similar_code":"-"}
```

On some browsers (notably Felienne's browsers: Mobile Safari on iOS, Chrome on Mac) apparently the cookie is not set, or something? And then when people go to run a program, they get an error instead, and there is no way to recover from this.

Two things to figure out here:

* Why does a missing `session` cookie lead to an error?
* Why is the cookie missing in the first place?

**Comment by rix0rrr** [comment]
The same does not happen on `localhost` for some reason.

**Comment by fpereiro** [comment]
I believe the error was when not using https and going to http://hedy-alpha.herokuapp.com. Right now, we're redirecting from alpha to test, and test needs sessions to be enabled. In all Heroku environments, moreover, we have a `secure` property on all cookies. So if there's no HTTPS, the cookies won't be set. This doesn't happen in localhost because we don't set the `secure` property on cookies.

I just added redirection from http to https for both alpha and test, so even if the browser doesn't automatically go from http to https, this change will make it so.

This shouldn't have affected beta/production, unless redirection was happening there to test (which it shouldn't).

**Comment by rix0rrr** [comment]
That explains why cookies we set aren't sent along with the `parse` command!

But that still doesn't explain why:

```
$ curl 'https://hedy-alpha.herokuapp.com/parse' -H 'Content-Type: application/json'  --data-raw '{"level":"1","code":"print hallo wereld\u0021","lang":"nl"}'
```

fails and:

```
$ curl 'https://hedy-beta.herokuapp.com/parse' -H 'Content-Type: application/json'  --data-raw '{"level":"1","code":"print hallo wereld\u0021","lang":"nl"}'
```

succeeds.

The browser isn't involved in either, we just purposely choose to NOT send a cookie and we get an error.

Still makes me a little uncomfortable...

**Comment by fpereiro** [comment]
The code in `test`, which implements the Gradual Feedback Model, requires that we have a session cookie set if you submit something to parse. If you do a normal flow with the browser, this should always happen. But you're right, it makes sense that we should return a proper error and not a 500 if a session is missing. I just added that change in `test`.

**Comment by fpereiro** [comment]
Hi @rix0rrr ! This should be definitely fixed with the latest changes we added today to `test`.

**Comment by fpereiro** [comment]
HI @rix0rrr ! A bit of OCD here, but could we mark this as closed?

**Comment by rix0rrr** [comment]
Sounds good!

**Comment by fpereiro** [comment]
Thank you @rix0rrr !
