### ISSUE TITLE
Possible issue: loaded programs not being loaded correctly and instead loading the same program

### ISSUE THREAD

**Issue by fpereiro** [Felienne/hedy#472]

**Comment by fpereiro** [comment]
Closed by #474

**Comment by MarleenGilsing** [comment]
I seem to have the same problem in my own account now (username marleengilsing). If I go to my programms and click 'Spookhuis level 7' another level 7 program I made pops up, and not the Spookhuis. It seems like Hedy always opens the program you've saved most recently in the corresponding level (it happens to all levels, not just level 7).

**Comment by MarleenGilsing** [comment]
When I try to open the programs via the admin account, I don't even get programs I made myself but Hedy opens with the standard example codes used in that level.
