### ISSUE TITLE
Inconsistent use of strings

### ISSUE THREAD

**Issue by arjenpdevries** [Felienne/hedy#48]
```
n is ask 'Hoe vaak?'
```

Does not compile.
But

```
print Hoe vaak?
```

also does not compile.

I'd prefer for the first to work, but know little of programming didacticts ;-) so up to you!
Consistency would be nice.

**Comment by Felienne** [comment]
Here was my thinking, but I am also of course willing to learn from your experience!

- print is a real Python command that we want to build up in steps to the real thing
- ask is a toy command, that will be replaced with a true function call---input()---once kids now how to write those things

Hence I did not want to make the syntax of ask too rich. 

But I see it leads to issues such as not being able to use variables in ask.

Still thinking about it, feedback welcome!

**Comment by arjenpdevries** [comment]
Can you work around the problem by telling students everything after `ask` is given to an equivalent `print` command? Then you can implement it using `print` on everything `s/(^.*ask)//` and process the result as you had planned.

In my observation, the kids were happy to learn the difference between using quotes and not, but then confused that it did not work the same way in `ask` as in `print`.

**Comment by Felienne** [comment]
Upon further consideration and examining of user data, this was a mistake, `ask` needs to take a string too. Will be fixed in a new version of the grammars.

**Comment by arjenpdevries** [comment]
Data-driven language design, pretty cool!
