### ISSUE TITLE
Misleading error message with missing quotation mark

### ISSUE THREAD

**Issue by fpereiro** [Felienne/hedy#526]
As reported by @MarleenGilsing :

A lot of times, the error message states "you forgot a quotation mark" but they didn't. They did however use `print` wrong, but it wasn't always a quotation problem.

**Comment by MarleenGilsing** [comment]
Example code: 

print 'Ik ben Hedy de voetbalvoorspeller.'
print 'Ik weet voor alle clubs op welke plek ze gaan eindigen'
'in de competitie!'

**Comment by MarleenGilsing** [comment]
![image](https://user-images.githubusercontent.com/80678586/122748531-93b06f00-d28c-11eb-8c78-13200919647c.png)

**Comment by MarleenGilsing** [comment]
Its also nice if the error message shows in which line the mistake was made.

**Comment by Felienne** [comment]
Hmmm now that I am thinking about this one and also #857 which I just closed I am thinking maybe we should have a special error message for lines in which we do not recognize any keyword (aka, we fetch the first word but that does not look like any keyword like when it is string distance more than x characters) and let the kid know. 

Will experiment with this a bit!!

**Comment by Felienne** [comment]
Superseded by #1489
