### ISSUE TITLE
Point out missing translations in UI texts

### ISSUE THREAD

**Issue by fpereiro** [Felienne/hedy#531]
Currently we have a script that checks for missing entries for UI texts on each supported language. However, we have many of those texts that are not translated. It would be good to have a way to see which ones, at a glance, to work on the remaining translations.

My initial idea was to check for this on the build tools and point them out. However, @Felienne suggested this might be incorporated into the translation tool, perhaps by either showing only the untranslated segments (or providing a button to show only those).

**Comment by Felienne** [comment]
Hi @boryanagoncharenko!

Maybe this could also be an issue for you to pick up? I am imagining a tick mark in the translation UI (https://hedycode.com/translate/en/nl) which shows only the untranslated fields so it gets easier to keep translations up to date.

**Comment by Felienne** [comment]
Closed by #1418
