### ISSUE TITLE
Allow users to accept an invitation to a class

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#545]
When users click an invite link, these things can happen:

- They are already logged into Hedy -> They go to a landing page with the name of the class, and a confirmation button. If they click ok, they become a member of the class

Landing page:

![image](https://user-images.githubusercontent.com/1003685/124381083-e17f9b00-dcc0-11eb-8434-813bfd42f881.png)

- They are not logged into Hedy, we redirect to: https://www.hedycode.com/login?lang=nl
- If they now login, the are redirected to the landing page and if they click yes, become a member of the class
- If they now create an account, they are redirected to the the landing page and if they click yes and become a member of the class

When they click ok, they are redirected to https://www.hedycode.com/programs (as normal)

**Comment by fpereiro** [comment]
@Felienne I think this can be closed by the recently merged PR
