### ISSUE TITLE
Issue with retrieving string sets from Dynamo

### ISSUE THREAD

**Issue by fpereiro** [Felienne/hedy#554]
Currently, we can store a list of strings in the `experience_languages` field of Profile. When retrieving these, however, an error is thrown, because they are retrieved as a Python set (eg: `{'a', 'b'}`), instead of a list of strings (eg: `['a', 'b']`). When Python tries to convert it to JSON, `GET /profile` throws a 500 if `experience_languages` is set.

We need to fix the Dynamo layer to retrieve string sets as lists rather than Python sets.

@rix0rrr @Felienne I'm glad to pick this up if needed. I believe this is happening since #494 , so it only affects `alpha`, but not `beta`.

**Comment by Felienne** [comment]
I guess we need to fix this before we deploy the new profile creation or it will not work?

@rix0rrr is #494 indeed the source or was this issue always there since the feature was added? If it was the source, can you fix it?

**Comment by fpereiro** [comment]
I just checked and the E2E tests pass. It may well be that I have wrong data on my profile for testing. Let me check further.

**Comment by fpereiro** [comment]
@Felienne @rix0rrr I understand the issue now. With my previous implementation of the feature, I stored these items as a string set. The new Dynamo layer uses lists. This would only generate issues for the three `alpha` users that already have a string set on that field, but it shouldn't generate issues for other users.

I believe we can close this, since it won't affect future users.
