### ISSUE TITLE
When visiting a site from the middle of the quiz, an error occurs (for Lotus)

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#565]
When visiting a site from the middle of the quiz ( so if you haven't started it from the beginning) the session variable session['total_score'] gives a NoneType when it's addes with question['question_score'].

**Comment by Fl0werth** [comment]
What's the expected behavior when you navigate from the middle? 
- You can make the quiz, but the score starts from 0 from the position you started. 
- You can't make the quiz and get an error message.
etc.

**Comment by Felienne** [comment]
I would say you are redirected to the start of the quiz

**Comment by Felienne** [comment]
I guess we can close this since we no longer use the URL to navigate between Q's in the quiz.
