### ISSUE TITLE
Typo in Quiz question 9 

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#568]
"print is regel 2 moet ask zijn" -> "print **in** regel 2 moet ask zijn"

**Comment by LauraTSD** [comment]
![Uploading Screenshot_20210719-105851.png…]()

**Comment by LauraTSD** [comment]
![Screenshot_20210719-105851](https://user-images.githubusercontent.com/23657961/126133987-9b57fb77-b71c-41d9-b652-5c48d7025396.png)
