### ISSUE TITLE
Mistake in timestamps in Mijn Programma's

### ISSUE THREAD

**Issue by LauraTSD** [Felienne/hedy#569]
![IMG_20210719_111724862](https://user-images.githubusercontent.com/23657961/126136696-cc219124-8387-4d50-9202-8fccc75a8bc4.jpg)

Error: timestamp for previous programs says 3 days ago while it was 1,5 hours ago
Error occurred for user: "Patrik de Panda" and "hoi"

**Comment by Felienne** [comment]
This is not a translating issue, in English is occurs in the same way
