### ISSUE TITLE
Hedy sees ask questions with comma's as a list

### ISSUE THREAD

**Issue by LauraTSD** [Felienne/hedy#574]
![IMG_20210719_130748281](https://user-images.githubusercontent.com/23657961/126151579-8a81b1df-d6c1-44c2-8c84-1dba18902742.jpg)
Problem: when using "variable is ask a, b, c?" The code thinks that a, b, c is a list instead of ask question.

Solution: give ask preference over lists.
Entire piece of code after an ask statement should be put as string in the input()

**Comment by LauraTSD** [comment]
![IMG_20210719_130748281](https://user-images.githubusercontent.com/23657961/126152052-edcaa580-442f-418a-8961-946569e8423a.jpg)

**Comment by Felienne** [comment]
Fixed because of the new ask syntax in level 3.
