### ISSUE TITLE
Highlight issue with multiple strings in print statement

### ISSUE THREAD

**Issue by Tazaria** [Felienne/hedy#587]
When there are multiple strings in a print statement from level 3 and up, only the first string is highlighted. Also, any key words in later strings are highlighted as key words while being interpreted as strings. They should just be highlighted as strings and not as key words.
![Highlight is](https://user-images.githubusercontent.com/47422769/126326874-5e59791a-eebf-42ef-b5a3-531a7bfe8e36.png)

**Comment by Felienne** [comment]
Closed by #617
