### ISSUE TITLE
Translate adventures to Spanish

### ISSUE THREAD

**Issue by Sergih28** [Felienne/hedy#641]
Translate [adventures](https://github.com/Felienne/hedy/blob/main/coursedata/adventures/en.yaml) to Spanish.

**Comment by natastro** [comment]
Hello! Happy to help with this, thank you! 😀

**Comment by fpereiro** [comment]
Hi @Sergih28 and @natastro ! I thought maybe it'd be good to coordinate and work on the missing Spanish translations! We also have #262 open which also concerns missing Spanish translations.

The missing translations would be:
- Some of the adventures (https://github.com/Felienne/hedy/blob/main/coursedata/adventures/en.yaml)
- Levels 4-1 and 8 through 22 (https://github.com/Felienne/hedy/blob/main/coursedata/level-defaults/en.yaml)
- @Sergih28 also wanted to improve the UI texts (https://github.com/Felienne/hedy/blob/main/coursedata/texts/es.yaml)

We can coordinate and see how we can divide the work. I'm happy to take on any section or to perform reviews. #262 was on my list forever so I'm super grateful for some help.

**Comment by Sergih28** [comment]
I'd like to take myself the UI texts if that's okay, as I'm still getting experience on translating, but slowly getting the hang of it, and it's easier if I don't do it from scratch on my firsts translations.

Besides that, I'd suggest that we focus only on levels or adventures, whatever you'd like to have finished first.
Another option would be that one of us (@natastro or me) does the adventures and the other one the levels.

Anyhow, I'll be dedicating more time to open source projects in 2 days onwards, so I'll be able to have the translations done faster than before.

**Comment by fpereiro** [comment]
Hi @Sergih28 ! Sounds great. You can go ahead with the UI text improvements and whenever you can/want go ahead with the adventures. If you're OK with it, I'll pick the remaining levels so we can have all the Hedy features in Spanish. I plan to get to it on the second half of this week. I'll keep you updated!

**Comment by natastro** [comment]
Hi @fpereiro ! I apologize for the delay - I just finished moving. I went back through to look at `adventures/en.yaml` and `level-defaults/en.yaml` and it looks like there are Spanish files. I just wanted to check and see if help is still needed or if I'm too late. Thank you! 😊

**Comment by Felienne** [comment]
> Hi @fpereiro ! I apologize for the delay - I just finished moving. I went back through to look at `adventures/en.yaml` and `level-defaults/en.yaml` and it looks like there are Spanish files. I just wanted to check and see if help is still needed or if I'm too late. Thank you! 😊

Hi @natastro! Your help would still be very welcome and I have not seen an update from @Sergih28 so if you could pick it up that would be lovely! Let us know if you need help.

**Comment by Felienne** [comment]
I am cleaning up the issues and I do not think it makes sense to keep issues open for translations (there are too many!)

**Comment by Felienne** [comment]
For sure, we still LOVE translations, just not open issues for them :D

Thanks for working on Hedy!
