### ISSUE TITLE
Change the place of the 'succesfully saved' message?

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#677]
I don't work on a big screen (like most schoolkids I reckon), so I don't see the message that I've succesfully saved my program. I need to scroll down to see it, especially in the higher levels where the instructions are getting longer. 

I would like to see it when I click the button, so I don't click it 5 times.. Would it be possible to move the message closer to the save button?

**Comment by fpereiro** [comment]
I think we can close this after merging #754 :)
