### ISSUE TITLE
port number suggestion

### ISSUE THREAD

**Issue by dvberkel** [Felienne/hedy#7]
Currently `app.py` configures the application to be served on port 5000. I would like to suggest to use port 4339. This spells `hedy` on a phones number keys.

**Comment by dvberkel** [comment]
This might conflict with what Heroku expects

**Comment by HenryLeC** [comment]
Heroku tells you what port to serve on so there would be no way to serve on port 4339. https://stackoverflow.com/a/28707129/14062431

**Comment by fpereiro** [comment]
Given that it doesn't work with Heroku, we'll close this. Thank you for the suggestion though!
