### ISSUE TITLE
random text level 1 NL

### ISSUE THREAD

**Issue by moorlag** [Felienne/hedy#70]
There is random text in a blockquote in NL level 1
I've looked around and I couldn't find the problem 1-2-3. 

This is the first assignment for new users. The user journey can end prematurely. 

[Hedy Level 1 NL](http://www.hedycode.com/hedy/1/uitleg?lang=nl)
![Schermafbeelding 2020-05-06 om 17 07 10](https://user-images.githubusercontent.com/2832006/81193887-40ae2680-8fbc-11ea-9841-cc1cf9f92672.png)

**Comment by Felienne** [comment]
Ah goeie catch Ramon!
