### ISSUE TITLE
[CONTENT] Add more levels of frequently made mistakes in teacher manuals

### ISSUE THREAD

**Issue by MarleenGilsing** [Felienne/hedy#712]
Now the teacher manual has a list of frequently made mistakes till level 5. I (Marleen) can add some more mistakes for the higher levels, but I'd love some input if anyone has some (especially level 7+).

**Comment by Felienne** [comment]
I think when @OnnoEbbens  does a new round with the new level structure he will have some input for this (starting in 2 weeks I think)
