### ISSUE TITLE
Better landing page for new accounts (also for new teachers)

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#722]
Just registered a new account on GitHub and this is just amazing:

![image](https://user-images.githubusercontent.com/1003685/132532566-02439b34-bbec-4f07-85c2-e0fb65214beb.png)

I want something like that!!

For students is should be one or two adventures (like we had way back when with the adventure page) 
For teachers it should be:
* Try Hedy
* Make a class
* Read teacher's material

**Comment by fpereiro** [comment]
Nice!!
