### ISSUE TITLE
Unclear error for `echo`

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#723]
When you call the `echo` command in level 1 without having called an `ask` command you get the error:
`name 'answer' is not defined`

It would be nice to have a more clear error message for this mistake.

**Comment by Felienne** [comment]
Haha this is one of our oldest issues, #12. I will pick it up soon, will try tomorrow (closing this one)

**Comment by Felienne** [comment]
Ah I see this is not the same as #12 but as this one #159 but this one is phrased better and more clearly, so let's keep this one.

**Comment by Felienne** [comment]
Will be addressed soon!

**Comment by Felienne** [comment]
Closed by #725
