### ISSUE TITLE
syntax highlighting after `echo`

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#724]
When you use an `echo` command without any text e.g.:
```
ask yes or no?
echo 
print okay
```

The syntax highlighting does not work for the command after `echo`. So in the example above, `print` is not highlighted.

**Comment by Felienne** [comment]
Ow and @TiBiBa if you are doing the syntax highlighting, maybe you can do this one too?

**Comment by OnnoEbbens** [comment]
I think something was improved but this issue remains.

When I first type the code I get this:
![image](https://user-images.githubusercontent.com/10562903/158571359-52419ae8-ab21-444a-bc37-0807282c8983.png)

Then when I run the code I get this:
![image](https://user-images.githubusercontent.com/10562903/158571427-32b72395-89a4-41c7-af8f-9d4eff1ee580.png)
