### ISSUE TITLE
Send email when teacher is made teacher

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#738]
I can draft the email! Something with: 

* Welcome to Hedy
* What teachers accounts can do
* How to ask for help

**Comment by fpereiro** [comment]
Nice idea! Feel free to assign me the bit that sends the email if you want, once the text is there.

**Comment by Felienne** [comment]
Hi @fpereiro,

Can you work with this text:

----

[Hedy logo]

**Welcome!**

Congratulations with your brand new Hedy teachers account. Welcome to the world wide community of Hedy teachers!

**What teachers accounts can do**

With your teacher account, you have the option to create classes. Your students can than join your classes and you can see their progress. Classes are made and managed though the for teachers page [link].

**How to shares ideas**

If you are using Hedy in class, you probably get ideas for improvements! You can shares those ideas with us on the Ideas Discussion [link: https://github.com/Felienne/hedy/discussions/categories/ideas]

**How to ask for help**

If anything is unclear, you can post in the Q&A discussion [link: https://github.com/Felienne/hedy/discussions/categories/q-a], or send us an email [mailto]

Keep programming!
The Hedy team.


------

And can we send this email with Hedy website fonts instead of plain text? And a bit of Hedy/tailwind coloring too, like a blue bar on the top and the grey sides?

**Comment by fpereiro** [comment]
@Felienne A few points:
- Do we plan on internationalizing this text or just keep it in English?
- We currently store the texts for our current emails in a line-by-line basis here: https://github.com/Felienne/hedy/blob/main/coursedata/texts/en.yaml#L112 . If we want to add custom templating, maybe we should start using an actual Jinja template for emails, starting with this one.
- External stylesheets won't work, but I can embed a minimum amount of inline CSS to give it a Hedy style.

**Comment by Felienne** [comment]
> @Felienne A few points:
> 
> * Do we plan on internationalizing this text or just keep it in English?

English is fine for now.

> * We currently store the texts for our current emails in a line-by-line basis here: https://github.com/Felienne/hedy/blob/main/coursedata/texts/en.yaml#L112 . If we want to add custom templating, maybe we should start using an actual Jinja template for emails, starting with this one.
> * External stylesheets won't work, but I can embed a minimum amount of inline CSS to give it a Hedy style.

Let's start with a bit of inline css than, I think templates for emails would be too much work (not really worth it)
