### ISSUE TITLE
www.hedycode.com works, hedycode.com doesn't

### ISSUE THREAD

**Issue by stroborobo** [Felienne/hedy#74]
Hi,

without the www. prefix there's some default page from the hosting provider. Maybe redirect?

I saw that url in the fsharpConf presentation just a few minutes ago.

Thank you, have a nice day! ❤️

**Comment by moorlag** [comment]
It seems that some people already [found a solution; 
](https://twitter.com/transip/status/629185159665963008)

**Comment by andrekovac** [comment]
Got the same issue

**Comment by fpereiro** [comment]
@stroborobo happy to announce https://hedycode.com works now! We changed our DNS provider to one that supports apex ALIAS/CNAME records.
