### ISSUE TITLE
level 2 error bij gebruik komma in `ask`

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#746]
Deze code in level 2:

`naam is ask Hoe heet jij, hoofdpersoon?`

geeft deze error:

```
We konden je code niet goed lezen.

De code die jij intypte is geen geldige Hedy code. Er zit een foutje op regel 1, op positie 39. Jij typte een vraagteken, maar dat mag op die plek niet.
```

Wanneer je het vraagteken weglaat:

`naam is ask Hoe heet jij, hoofdpersoon`

Krijg je geen error maar de code wordt ook niet uitgevoerd. 

Uiteindelijk werkt het wel als je de komma `,` weglaat:

`naam is ask Hoe heet jij hoofdpersoon?`

**Comment by Felienne** [comment]
Closed by #947
