### ISSUE TITLE
Move next question button into quiz

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#759]
Hi Fl0wert!

We want to make the quiz a bit more compact, to put it into the tabs for kids (see #733 ) You do not have to do 733, @fpereiro will do that, but could you move the button in as a preparation?

Like this:

![image](https://user-images.githubusercontent.com/1003685/133395931-e1e5d008-a03e-4c96-a9ea-8dd64b3b9036.png)

**Comment by Fl0werth** [comment]
Do you mean, the green bar has to be removed upside. Or the button has to be moved from the green bar to the white screen?

**Comment by Felienne** [comment]
Sorry for being unclear. I meant move the button into the white area, and remove the green bar.

But now that you mention it, we could also move the green bar with the button into the white area. That might be prettier!

Let's do that second option.

**Comment by Fl0werth** [comment]
![image](https://user-images.githubusercontent.com/86956321/133757006-3ee4cadd-71c0-4225-9d5e-65de598e22e2.png)
Do you mean like this or shall I move the button more to the center? And shall I fill the white field with green?

**Comment by Felienne** [comment]
Perfect like this!
