### ISSUE TITLE
Add a tiny sleep after turtle.forward

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#765]
So it is more clear the turtle makes multiple steps when repeating forwards

**Comment by thiagoarrais** [comment]
Hi, @Felienne ? Are you working on this? May I try to tackle it?

**Comment by Felienne** [comment]
Hi @thiagoarrais 

Would be great if you could pick this up! Will be your first change to the core language, exciting!! Do let me know if you need any help.
