### ISSUE TITLE
Lexographic comparison of numbers

### ISSUE THREAD

**Issue by thiagoarrais** [Felienne/hedy#788]
On level 16 the start code compares the user's age to 12. But if the answer is anything from 2 to 9 the code breaks and concludes that the user is older than the writer.

I suspect that this is caused by lexographically comparing, say, "2" to "12" due to the string conversions in [ConvertToPython_16](https://github.com/Felienne/hedy/blob/666f1c31a1d/hedy.py#L861). Is this intentional? If not may I try to offer a PR to fix this?

**Comment by Felienne** [comment]
Great find, thanks! Would be lovely if you fix that in a PR!!
