### ISSUE TITLE
unexpected error for `turn` command in level 2

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#792]
Sometimes people combine the `turn right` and `turn 90` commands in level 2:
`turn right 90`

If you do this you will get this error:
```
We can't run your program.
turn is not a Hedy level 2 command. Did you mean print?
```
Which is unclear because `turn` is a Hedy level 2 command.

**Comment by Felienne** [comment]
Hi @boryanagoncharenko!

Not necessary for you to look into this now but this is surely something we could catch with an AST based type system.

**Comment by boryanagoncharenko** [comment]
Now, closed by https://github.com/Felienne/hedy/pull/1125
