### ISSUE TITLE
Error when submitting the 3th wrong answer in the quiz

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#797]
In the quiz when you submit the wrong answer 3 times in a row, you get an `500 Internal Server Error` because the page doesn't exist.

**Comment by Felienne** [comment]
@LotusterHaar Could you see if this a quiz issue?

**Comment by Felienne** [comment]
I just tried and I have this issue too:

![image](https://user-images.githubusercontent.com/1003685/134767520-b62ce881-57d7-4a03-b325-48d43b83e0e9.png)

Interestingly... it happens on beta but not on alpha... @fpereiro Can you investigate see if this is a server/setting issue?

**Comment by Fl0werth** [comment]
> I just tried and I have this issue too:
> 
> ![image](https://user-images.githubusercontent.com/1003685/134767520-b62ce881-57d7-4a03-b325-48d43b83e0e9.png)
> 
> Interestingly... it happens on beta but not on alpha... @fpereiro Can you investigate see if this is a server/setting issue?

I don't have the error anymore. Can it have something today with clearing the cache?

**Comment by Felienne** [comment]
Same for me, for me the error no longer occurs. Can you confirm @OnnoEbbens ?

**Comment by OnnoEbbens** [comment]
Yes I can confirm, thanks for fixing!
