### ISSUE TITLE
Change of YAML structure

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#819]
Hi @LotusterHaar 

We want to be able to use code blocks in answers too, but that does not work, because YAML does not understand code blocks in lists (You can seen @MarleenGilsing's try in #731 for example)

We need to fix the yaml structure a bit for code to work in answers, from this:

```
              - { option_text: "",
                  code: "
                    print 'Welkom bij restaurant Hedy'
                    eten is ask 'Wat wilt u bestellen?
                    print eten",
                  feedback: "Hier zit geen herhaling in, er zijn twee bestellingen."
              },
              - { ...
              }

```

to something like this:

```
mp_choice_options:
              - 1: 
                - option_text: ""
                - code: |-
                      print 'Welkom bij restaurant Hedy'
                      eten is ask 'Wat wilt u bestellen?
                      print eten"
                - feedback: "Hier zit geen herhaling in, er zijn twee bestellingen."
             - 2: ...
```

Can you update your code so we can work with the new yaml structure? It should simplify your code too because you can then simply read the question number from the yaml file instead of having to count answers in app.py.

If this is not clear, let me know!

**Comment by Fl0werth** [comment]
Would it be maybe more efficient if I wrote a small program that transforms the yaml file structure to the one you suggested? I guess that spares time and is error proof. And maybe I can use the code later to automate the process of making yaml files.

**Comment by bjorn3** [comment]
Maybe round tripping it through the yaml parser like using `yaml.dump(yaml.load(the_yaml_string), the_yaml_file)` will write it in the format you want?

**Comment by Felienne** [comment]
This is no longer a priority at the moment because you explained to Marleen how to make the quizzes with code blocks and that works already. It is still a good idea to simplify the code but it may also be done in a later sprint.

**Comment by Felienne** [comment]
> Would it be maybe more efficient if I wrote a small program that transforms the yaml file structure to the one you suggested? I guess that spares time and is error proof. And maybe I can use the code later to automate the process of making yaml files.

I am not sure if it is worth in to rewrite the code with a script, manual might be just as quick but I can see how that is not really fun :)

**Comment by LterHaar** [comment]
The new yaml structure is applied to all the quizzes in #806 . Also there is a small script: convert_to_new_yaml_structure.py that converts all the original quizzes to the new structure
