### ISSUE TITLE
Double print when re-running `ask` command

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#820]
There is a specific pattern that causes my code to run twice. 
1. I run code with an `ask` command in level 1-4
2. I do not answer the question, instead I modify the code a bit so I can re-run it
3. I run the code again, this time I do answer the question
4. Now every print statement in my code is executed twice.

This is not a huge issue but it is confusing for students.

**Comment by Felienne** [comment]
Yeah I have seen something similar before but I was never sure how to reproduce it, so thanks for this!!

@fpereiro could you look into this next week? The trick I think it to flush the "ask buffer" when code is edited but that might be non-trivial?

**Comment by Tazaria** [comment]
This issue has either not been fixed or has resurfaced. Aborting a program while an ask is still open causes the program to print echo and print statements twice, once from where the previous run was aborted and once from the current run

**Comment by Felienne** [comment]
Thanks for letting us know @Tazaria!

I have tried a bunch of times but I was not able to reproduce it. The run button with me always turns into a stop button while an ask is open:


If you remember, can you let us know what steps to take or what program, level and browser you (or the kid, I guess :) ) used:

<img width="1301" alt="image" src="https://user-images.githubusercontent.com/1003685/180617314-7d41b85e-6382-438e-b934-566299d880fc.png">

**Comment by boryanagoncharenko** [comment]
I got it! Open level 2 and put the following code in:
```
name is ask What is your name?
print hi, name
```
Now be careful to follow the instructions: 
1. Press the Run code button
2. Do not answer the question and do not click the Stop program button. Click on the editor where your program is and modify it, e.g. `What is your name again?`. (Note that when you start typing, the green input box on the right hand side will disappear, is this expected?!)
3. Now click the Stop program button.
4. Click the Run program button.
5. Answer the question in the green input box on the right and click Enter. Now the output is doubled:
<img width="1267" alt="Screenshot 2022-07-26 at 12 27 28" src="https://user-images.githubusercontent.com/3010723/180973392-5f54d2a5-3bae-4da5-9ccd-bef9bae1adb9.png">

If you repeat steps 1-4 multiple times, you will get the output printed more than twice.

**Comment by Felienne** [comment]
Ah fantastic detective work @boryanagoncharenko!

> Do not answer the question and do not click the Stop program button. Click on the editor where your program is and modify it, e.g. What is your name again?. (Note that when you start typing, the green input box on the right hand side will disappear, is this expected?!)

Yes, that is expected! If we modify the code, then apparently the kid wants to stop running and make changes so we stop the current execution.

But then what should, of course, also happen is that we cancel all subsequent printing of that run, somehow. I am not really sure how to achieve that on the front-end but maybe you do? (or maybe @TiBiBa does?)

**Comment by arjank** [comment]
I found another way to reproduce this, and that does not require the ask statement.

If you use the program
```
print line 1
sleep 4
print line 2
sleep 4
print line 3
```
and you stop and restart it once it prints "line 2", then the final output is:
```
line 1
line 3
line 2
line 3
```

Note that the success message is shown each time it prints "line 3".
