### ISSUE TITLE
Make a function that automatically removes extra whitespaces.

### ISSUE THREAD

**Issue by Jasper1408** [Felienne/hedy#826]
When a child writes an extra whitespace, there is an alert saying, "you should remove the whitespace at line x at column y". It should be possible to make a function that automatically removes this whitespace for the child in the program. 

Tips from Felienne

**Comment by fRedelaar** [comment]
We have a question regarding this issue @Felienne 
![image](https://user-images.githubusercontent.com/33595265/135483990-a3a2ee0a-cb5b-4efc-a9bf-049b19580ec5.png)
In level 1 when you add whitespace, the code will still execute 

![image](https://user-images.githubusercontent.com/33595265/135484087-e9cce7fb-13b0-4166-96a7-cdff7296f3eb.png)
In level 3 it will not. 

We are assuming right now that this has been done on purpose for educational purposes. (Start easily, then levels becoming harder..)

So our question is, from what level on should we automatically repair and fix the program with the suggestion and running it?

**Comment by fRedelaar** [comment]
Closing this because it has been completed in the merged PR #1287

**Comment by Felienne** [comment]
> We have a question regarding this issue @Felienne ![image](https://user-images.githubusercontent.com/33595265/135483990-a3a2ee0a-cb5b-4efc-a9bf-049b19580ec5.png) In level 1 when you add whitespace, the code will still execute
> 
> ![image](https://user-images.githubusercontent.com/33595265/135484087-e9cce7fb-13b0-4166-96a7-cdff7296f3eb.png) In level 3 it will not.
> 
> We are assuming right now that this has been done on purpose for educational purposes. (Start easily, then levels becoming harder..)
> 
> So our question is, from what level on should we automatically repair and fix the program with the suggestion and running it?

Hi team! Somehow I completely missed this message! It was not really done for educational purposes haha, more because it was easy to do in early levels and harder/more work in later levels. I would be quite ok if we allow spaces in the beginning of lines until level 8 when we introduce indentation.
