### ISSUE TITLE
Make a function that automatically corrects typos in keywords 

### ISSUE THREAD

**Issue by Jasper1408** [Felienne/hedy#830]
This is the same concept as #3, "Make a function that automatically removes extra whitespaces", and #8, "Make a function that adds forgotten quotation marks".

For this function, it should automatically correct these typos. It would involve adding a character (prin -> print), removing a character (printt -> print), or changing a character (primt -> print).

**Comment by fRedelaar** [comment]
Closing this because this has been fixed in PR  #1287
