### ISSUE TITLE
Think of a way to improve the UX of programme repair

### ISSUE THREAD

**Issue by Jasper1408** [Felienne/hedy#831]
How will the programme repair work exactly? What would we like the user to do?

Some suggestions made were the creation of a pop-up. Would this pop-up allow the user to copy the suggestion made, or will they have to retype it? Would the differences be highlighted between the suggestion and the faulty programme?

**Comment by Felienne** [comment]
Hi @Jasper1408 (and other rockets). 

We already have a discussion for this topic, can you move your comments there? https://github.com/Felienne/hedy/discussions/772

Issues are meant for things we are going to fix in a PR, not a place to chat about stuff we do not know how to do yet. 

If you have moved your comments, can you close this issue?

**Comment by bjorn3** [comment]
Moved to https://github.com/Felienne/hedy/discussions/772#discussioncomment-1430695

**Comment by Felienne** [comment]
Thanks for closing and rearranging @bjorn3!
