### ISSUE TITLE
Reduce the options in the error message generated by printing an unquoted string from two to one 

### ISSUE THREAD

**Issue by Jasper1408** [Felienne/hedy#832]
When a kid prints an unquoted string, eg. print naam, there will be an error saying:
"You are trying to print variable name, but you haven't made it yet. OR you forgot the quotation marks."

Reduce these two options to one.

The idea is that we will check before creating the error message if there is a variable that looks a lot like NAAM, and then actually write out "You are trying to print variable name, but you haven't made it yet. " OR "you forgot the quotation marks. " Depending on the situation.

**Comment by Felienne** [comment]
This is a lovely idea, would love to se how you approach this!

**Comment by johannadekker** [comment]
Hi, could I be invited to collaborate again? My invitation has expired

**Comment by Felienne** [comment]
There is already a location in the code where I this could happen, this might help: https://github.com/Felienne/hedy/blob/bbc5f176e0006442959a3a1dd30059205d6ecfda/hedy.py#L760
