### ISSUE TITLE
Missing license file

### ISSUE THREAD

**Issue by braisarias** [Felienne/hedy#84]
First of all: good job :clap: :clap: 
I haven't found the license file so I don't know if this project is free (as in freedom) software or not.
I would like that you think about the possibility of releasing this project under one free and open license. You can find good information about the licenses here: https://www.gnu.org/licenses/ , and in addition, you can choose the EUPL (https://ec.europa.eu/info/european-union-public-licence_en) because it fits best with EU laws.
Thanks for all

**Comment by Felienne** [comment]
Thanks for the tip, I did not know about the EU license.
