### ISSUE TITLE
Ensure HedyException's contain error locations if applicable

### ISSUE THREAD

**Issue by bjorn3** [Felienne/hedy#845]
This will allow for nicer error message. It is also a prerequisite for adding error squigles as suggested in https://github.com/Felienne/hedy/discussions/772#discussioncomment-1413060.

**Comment by Felienne** [comment]
Great idea! 

For simple programs at lower levels we do this by looking at the command number but of course that breaks when we have an if over multiple lines. Would be great to save line info into the syntax tree to use for error messages!

**Comment by Felienne** [comment]
@bjorn3 and friends: @dolfein has a concrete plan to move this forward which will be ready soon so you do not have to pick this up further at this point to avoid double work

**Comment by Felienne** [comment]
Guess this can be closed with #1435!
