### ISSUE TITLE
Where did the quizzes go?

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#865]
There used to be quizes to test your knowledge at each level (at least in Dutch). I can't seem to find them anymore. PR #810 suggests they moved to a seperate tab but I can't find this either. Where did they go?

**Comment by Felienne** [comment]
Ah you are right! Must have happened in a merge, will try to fix asap!

**Comment by Felienne** [comment]
Just deployed quizzes back to Hedycode, sorry @OnnoEbbens!! They are in the tab 'Eind'.
