### ISSUE TITLE
Show quiz score as part of total

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#882]
In the quiz of level 6 the maximum score is lower than in previous quizzes. Students think they did a bad job because they get a lower score. Can we show the score as part of the total points they can get, e.g. score: 50 / 70

**Comment by Felienne** [comment]
Good idea! This can go on @LotusterHaar's next sprint. An easier solution that is quicker to reach (potentially even by you!) is to add some questions to level 6 to even out the points.

**Comment by LterHaar** [comment]
My solution is, showing a percentage of the number of questions answered correctly
