### ISSUE TITLE
trailing space after else

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#891]
When there is a space after the `else` statement I get an error that points to the wrong line and position.

Using this code (with a space after `else`):
```
1. if a is 1
2.     print a
3. else
4.     print 'nee'
```

I get this error:
```
We konden je code niet goed lezen.

De code die jij intypte is geen geldige Hedy code. Er zit een foutje op regel 4, op positie 6. Jij typte , maar dat mag op die plek niet.
```

**Comment by Felienne** [comment]
> Would it be possible to always allow trailing spaces at the end of any line? (I am saying this with very limited knowledge of how the Hedy code is processed.)

This was already allowed in all places... except for after an `else` 🤣 

Fix coming right up!

**Comment by Felienne** [comment]
> > > For example if you use this code in level 4-6 with a trailing space in the second line after `a`
> > > ```
> > > a is 2
> > > if a is 1 print a 
> > > else print 'nee'
> > > ```
> > 
> > 
> > I can't seem to reproduce this issue:
> > ![image](https://user-images.githubusercontent.com/1003685/136261478-d2967b98-83d6-4d99-9412-0c9158b2a1d0.png)
> > Can you show me how to get this error?
> 
> I get an error with this code in level 5 and 6 but not in level 4 for some reason.

Ah got it, will look at levels 5 and 6 then! Should be fixed today.
