### ISSUE TITLE
Simplify grammar for allowing spaces

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#894]
In many places we use things like:

`(_SPACE command)`

f.e. in level 9:

`elses: _EOL _SPACE* _ELSE _COLON _EOL (_SPACE command) (_EOL _SPACE command)* _EOL _END_BLOCK`

But it would be nicer if we move allowing the spaces to the command rule, with something like:

`command: _SPACE_* (print | ifs (elifs)* elses? | ask | for_loop | assign_list | list_access_var | assign) _SPACE_*`

**Comment by Liz433** [comment]
Hi! I would like to work on this issue but I don't fully understand the issue, could you expand more on this?

**Comment by Felienne** [comment]
Ah sorry this has been addressed by https://github.com/Felienne/hedy/pull/2413
