### ISSUE TITLE
Set up translation structure for keywords

### ISSUE THREAD

**Issue by HuibSprangers-leiden** [Felienne/hedy#942]
Currently, even if new keywords were added, the program has no structure in place to translate them. (app.py currently has the functions for other translations)

**Comment by Felienne** [comment]
Good point! This means we will need to make a central location for translations and use that in both app.py and hedy.py.

**Comment by Felienne** [comment]
(alternatively you can also make the issue part of a milestone, that also gives me an overview in the issue list)

**Comment by emil-meyknecht** [comment]
We are currently working on this issue and would like to share our approach.
We are currently working in Hedy,py and are making Transformers to transform a Parse tree for each level, just as is done to convert the Hedy code to python, only this time we translate the Tree to the Hedy code with translated keywords. Then we write tests to see if each level is translated correctly.
We were wondering if this a a good approach and if we should continue with it.
