### ISSUE TITLE
Grammar improvement for level 3 and up

### ISSUE THREAD

**Issue by Felienne** [Felienne/hedy#944]
Since `ask` allows for quotes, there is some duplication between `ask` and `print` in the grammar

`(_SPACE| list_access | quoted_text | var_access)*` could be something like 'print_argument'

**Comment by Felienne** [comment]
> I tried extracting the following rule: `print: _PRINT (_SPACE (_SPACE | print_argument)*)? -> print` `?print_argument: list_access | quoted_text | var_access` But it seems that in certain cases the list_access is parsed as 3 nodes of var_access instead of a single list_access node. Ofc I also tried adding the spaces in the print_argument rule but I hit the same issue. Maybe I am missing something?

It could very well be the case that we use `list_access` inconsistently but form your description it is hard to know the exact issue. Do you have a branch that you could push that I could look at?

**Comment by boryanagoncharenko** [comment]
This is the [branch](https://github.com/Felienne/hedy/tree/issue/944) You can observe the issue by running the test test_print_list_var_random in tests_level_03.py. Thanks a lot for the help.

**Comment by boryanagoncharenko** [comment]
Closed by https://github.com/Felienne/hedy/pull/1181
