### ISSUE TITLE
print works without quotes in level 6 or higher

### ISSUE THREAD

**Issue by OnnoEbbens** [Felienne/hedy#965]
In level 3 quotes are introduced for `print` and `ask`. In level 3-5 you get an error if you don't use quotes. In level 6 or higher you don't get an error if you forget to use quotes, at least not with this code:

`print da bu die da bu dai`

I think we should raise an error when people don't use quotes after print.

**Comment by Felienne** [comment]
Just tested this (and added a test for it in #1488) and this seems to be fixed already! Not sure when but at least it is no longer an issue @OnnoEbbens
