### ISSUE TITLE
Implement landing page when verifying mail address

### ISSUE THREAD

**Issue by TiBiBa** [Felienne/hedy#981]
Currently when verifying your mail address after creating an account you land on the homepage; giving the user no information if the verification of the mail address was successful. It would be nice to return the user with some additional information such as "your account is successful verified". We can implement this by creating an additional "landing" page when clicking the verify link in the mail with (maybe) an automatic re-direct to the homepage after x seconds.

**Comment by Felienne** [comment]
Hi @TiBiBa 

I am browsing old issues and this might be a small one for you to pick up yourself?

**Comment by TiBiBa** [comment]
Yes, will pick this up!
